---
title: "De San Cristóbal de las Casas a Palenque con un chapuzón cristalino"
author: "Black Bird"
date: "2/09/2013"
output: html_document
---

# Generalidades de carretera

La carretera de SC a Palenque es una sierra brava, llena de camiones, curvas y topes, la carretera maltrata cualquier carro por más preparado que esté. Si esto fuera poco, Chiapas, el estado más pobre de la República Mexicana, no destina recursos (por obvias razones) al mantenimiento de la carretera o al menos parece no destinar los recursos suficientes, esto hace que los tramos parezcan auténticas casas de burlesque (por todos lados vez hoyos) -patrocinado por el tío ¿o era abuelo? del buen CastMol- con tantos hoyos y curvas los que van atrás sufren por lo que les recomiendo que, si se marean, hagan como yo y vayan de fiesta el día anterior así, duermen todo el camino o tomen un Dramamine (tal vez sea más sano). Sin embargo, no todo es horror en este trayecto, el paisaje de la carretera (como todos los que he circulado en Chiapas) es verdaderamente maravilloso y se come bien, barato y "limpio" en los restaurantes carreteros (al menos yo tuve suerte), les recomiendo hacer lo que nosotros hicimos, salir muy temprano de SC y desayunar en el primer restaurante carretero donde haya al menos un camión Torton estacionado, recuerden que los locales son la mejor guía turística en estos casos y nos garantizarán algún nivel de limpieza y calidad de comida. Otro tip importante que a estos niveles del campeonato ya deberían de saber es el problema de las gasolineras en Chiapas, claro que no hay una sola PEMEX en toda la carretera así que no se olviden de llenar el tanque en SC, no quieren quedarse varados a la mitad de la carretera.

# Agua Azul (julio)

Unas tres horas después de haber salido de SC (unos 120 klm de ahí) llegamos a la desviación de la Reserva de la Biósfera  Agua Azul, sin duda alguna es un paradero fenomenal, por dos grandes razones:

- 1. Con el denominado calor que hace, un chapuzón en sus cristalinas aguas refresca hasta el alma
- 2. A estas alturas del campeonato el hambre de verdad ya pega y este lugar está lleno de restaurantes locales, recuerden: ¡Siempre hay que tratar de dejar nuestro dinero con los locales!

Pero ¿qué es exactamente este parque? Las cascadas forman parte de un sistema acuífero que junta tres ríos Otulún, Shumuljá y Tulijá, su color azul cristalino se debe a la gran cantidad de sales de carbonatos que contienen las aguas. Este sistema de cascadas tiene 3 principales atractivos:

- 1. la primera "laguna" se encuentra luego llegando, se caracteriza por ser una alberca (hay nula corriente) y estar llena de gente, para los que no saben nadar muy bien, es la zona ideal para bañarse.
- 2. siguiendo el camino de piedra (algo resbalozo, cuidado) llegamos a una segunda parte donde se forman tres pozos de aproximadamente metro y medio de profundidad ahí la corriente es más fuerte así que les recomiendo entrar con cautela, la gran ventaja es que casi nadie se mete ahí.
- 3. Seguimos subiendo unos 45 minutos y llegaremos a la naciente de las cascadas (o al menos algo que parece) aquí, encontramos un lugar mucho más privado ya que nadie se anima asubir 45 minutos a pata (la flojera es mucha).

Elijan su lugar de baño dependiendo del tiempo que quieran destinar en el parque, recuerden de llevar traje de baño, toalla y chanclas, ahí hay vestidores y demás. No recuerdo cuanto cuesta la entrada al parque, se las debo. En este lugar hay cabañas así que no se preocupen si les agarra la noche o el romanticismo.
Palenque

Saliendo de las cascadas, unos 80 kilómetros adelante llegamos a Palenque (sitio), estacionamos (gratis, la propina al "viene-viene" es voluntaria), compramos un agua (porque hace un calor infernal) y entramos al parque. Recuerden llevar credencial de estudiante o maestro ya que la entrada es gratis, si no hay que pagar $57.

Para visitar Palenque requieren como mínimo una hora y media (haciendo un tour express sin visitar el museo de sitio), una visita normal les tomará como dos horas y si son atascados como yo al rededor de 3 horas. Cabe recordar que el sitio cierra a las 6 Pm por lo que el manejo de tiempo en Agua Azul es indispensable si planean hacer todo el mismo día.

Después de visitar el sitio, aterrizamos en Palenque (ciudad) no hay absolutamente nada interesante aquí, es litermalmente, un lugar para hacer base ya que desde aquí se puede ir a Bonampañ y Yaxshilán...

<br>

Hotel casa de Pakal, Av. Juárez al lado del Burger King. Tel. 9161035251 y 916 103 5470 Correo: rigo_yale@live.com.mx
La habitación, con cable aire y dos camas amtrimoniales, está al rededor de $600. bueno bonito y barato.