---
title: "San Cristobal de Las Casas"
author: "Juliano Palacios Abrantes"
date: "09/07/2013"
output: html_document
---

Saliendo del sur de la ciudad de México, son 9 horas hasta San Cristóbal de las Casas, esto en carro a 100 klm por hora de predio sin parar para comer y sin percances en la carretera (difícil en un país donde están en constantes obras)

Hay que tomar la autopista a Puebla, seguí hacia Córdoba y antes de Veracruz (puerto) tomar la desviación  a Minatitlan, tomar dirección Villahermosa y unos 60 klm después bajamos por directo a Tuxtla Gut. La carretera en general esta en buen estado y permite llegar a altas velocidades sin problema alguno, todas las casetas aceptan IAVE. 

No hay mucho que decir de la carretera, lo bonito viene después de Minatitlan, antes de eso sólo un puente MUY alto. Ahora, conforme uno se va alejando de Veracruz y llegando a Chiapas el paisaje va cambiando, la selva va perdiendo la timidez y el Clima va aumentando. Los grandes y caudalosos ríos del sureste mexicano pasan abajo de ti. Es muy impactante como el clima engaña, el ambiente se ve nebuloso, el asfalto y las platas ligeramente mojadas resaltan el verde, un cielo azul artificial se asoma tímidamente entre las nueves blancas y gordas, todo indica que cuando hacemos la parada para descargar el tanque moriremos de frío, pero oh sorpresa, es sólo bajar la ventana que un aire caliente se apodera del microcla del auto y tus sentidos simplemente no logran procesar la información. 

Tip 1. si vas a Chiapas en julio, viaja en bermudas. 
Tip 2. Es altamente recomendado llenar el tanque del auto en Minatitlan antes de la desviación a Tuxtla ya que pasas al rededor de 100 klm sin poder cargar gas. 
Tip 3. Modera tu velocidad que hay muchas patrullas en el camino. 

Por ahora esto es todo amigos, sin duda la entrada a Chiapas y los 45 klm entre Tuxtla y SC son de las carreteras más bonitas que he visto veremos que nos depara el Estado.  

To be continue...