# Education

- **Postdoctoral Researcher** (2022 - Present)
Changing Oceans Research Unit, The Institute for the Oceans and Fisheries, University of British Columbia; Canada; Supervisor, Dr. William Cheung

- **Postdoctoral Researcher** (2021 - 2022)
Jensen’s Lab, Center for Limnology, University of Wisconsin-Madison, USA; Supervisor: Dr. Olaf Jensen
    - *Adaptive Allocation for Transboundary Fish Stocks*  

- **Doctor in Philosophy; Zoology** (September 2016 – March, 2021)  
The Institute for the Oceans and Fisheries, University of British Columbia, Canada; Advisor, Dr. William Cheung
    -	*Transboundary Fish Stocks and their Management Under Climate Change*
    - Semester abroad at the University of Vigo working with Dr. Elena Ojea (August - December, 2019)  

- **Master of Environmental Science and Management** (September 2014 - June 2016)  
  Bren School of Environmental Science and Management, University of California at Santa Barbara, USA; Advisor, Dr. John Melack
    -	*A Citizen Science Monitoring Protocol for the Rocky Intertidal Habitat*
    - Internship at Environmental Defense Fund, Mexico (June - September, 2015)  
- **Bachelor of Science in Biology** (September 2007 - December 2012)  
  Universidad Autónoma Metropolitana campus Xochimilco, México City; Advisor, Dr. Virginia Melo
    -	*Sea Cucumber as a Source of Macronutrients for Low-Income Coastal Communities in Mexico.*
    - Year abroad at the University of São Paulo, Brazil
    
**Keywords:** *Climate change; Fisheries management; Shared fisheries; Data science; Multidisciplinary; Marine science; Sustainability*