# Work in Press, Under Review (R&R) or in Progress

- **Palacios-Abrantes, J.**, Tai, T., *et al.* (eds. **Palacios-Abrantes, J.** and Tai, T.) Rapid changes across Canada's oceans in (ed. Sumaila, U.R.) Ocean Canada Partnership Book *[In press]*

- Steiner, N. *et. al.* (e.d. Steiner, N.) Rapid changes across Canada's oceans in (ed. Sumaila, U.R.) Ocean Canada Partnership Book *[In press]*

- **Palacios-Abrantes, J.**, Badhe, R., Bamford, A., Foden, W., Frazão-Santos, C., Grey, K.A, Kühn N., Maciejewski, K., McGhie, H., Midgley, G.F., Smith, I.P.J., and Pereira, L.M. Managing biodiversity in the Anthropocene: Utilizing the Nature Futures Framework for adaptive decision-making for nature under climate change [*R&R*]

- **Palacios-Abrantes, J.**, Roberts, S. M., Cashion, T., ten Brink, T., Cheung, W.W.L, Mook A., and Nguyen, T. Marine Protected Areas Can Reduce Regional Losses to Fisheries Under Climate Change [*R&R*]

- **Palacios-Abrantes J.**, Crosson S., Dumas C., Fujita R., Levine A., Longo C., Jensen O. Quantifying fish range shifts across poorly defined management boundaries *[In preparation]*

- Cheung W.W.L. *et. al*. Projecting climate adaptation in fisheries production and its limits through eliminating overfishing [*R&R*]

- Tidd, A., Ojea, E., **Palacios-Abrantes, J.** Miss-matches between climate change-driven shifts in fish distribution and the European Union fish stock quota allocation *[In preparation]*