# Workshops Attended or Organized

- Canada's Blue Economy Symposium (June, 2022). Organized by NEXUS program and Memorial University of Newfoundland. St. John's, Canada. *Fully funded by organizers*

- High Seas Nature Futures Framework (NFF) workshop (July - December, 2021). Organized by the Stockholm Resilience Centre, Stockholm University. Cape Town, South Africa. *Fully funded by organizers*

- IPBES Future Nature Scenarios Workshop (July, 2019). Part of the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES) scenario task force. Organized at the Species on the Move conference, Skukuza, South Africa *Co-organized*

- IPBES Future Nature Scenarios Workshop (March, 2019). Organized by the University of British Columbia (UBC) and the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES); Vancouver, British Columbia, Canada *Co-organized*

- Future High Seas Governance Workshop (November, 2018). Organized by the University of British Columbia (UBC) and the International Institute for Environment and Development (IIED). Vancouver, British Columbia, Canada. *Fully funded by organizers*

- IMBeR ClimEco6 Summer School - Interdisciplinary approaches for sustainable oceans (August, 2018). Organized by the Integrated Marine Biosphere Research (IMBER). Yogyakarta, Indonesia. *Fully funded by PICES*

- Graduate Student Workshop on Socio-Environmental Synthesis (January 2018). Organized by the National Socio-Environmental Synthesis Center (SESYNC). Annapolis, Maryland, United States. *Fully funded by organizers*

- UK-Mexico Researcher Links Workshop, Present Status and Horizon Scanning of Sustainable Aquatic Resource Development in Mexico (September, 2017). Organized by the Instituto Tecnologico Superior de Felipe Carillo Puerto, British Council, CONACyT and Researcher links. Felipe Carrillo Puerto, Quintana Roo, Mexico. *Fully funded by organizers*  