# Awards and Honors

- Globalink Research Award for research abroad (August - December 2019). Awarded by Mitacs for the project *Climate change and emerging transboundary fish stocks* developed in collaboration with Dr. Elena Ojea at the University of Vigo

- The Institute for the Oceans and Fisheries Student Society (IOFSS) Travel Grant (July 2019). Awarded to participate in the conference Species on the Move in July of 2019 in Skukuza, South Africa

- SESYNC Graduate Pursuit Award (September 2018 - May 2020). Awarded by the National Socio-Environmental Synthesis Center (SESYNC) to conduct the research *Ch-Ch-Ch-Changes: Using Marine Protected Areas to Investigate Potential Socio-Ecological Impacts of Climate Change in Marine Spatial Planning.* National Science Foundation and the University of Maryland. (Link to project: tiny.cc/lzxv5y) *Role: Principal Investigator*

- Faculty of Science PhD. Tuition Award (September 2016 – September 2020). Awarded by the University of British Columbia to pursue a PhD. In Zoology

- International Tuition Award (September 2016 – September 2020). Awarded by the University of British Columbia to pursue a PhD. In Zoology

- Latin American Fisheries Fellow (LAFF) (August 2014- June 2016). Awarded by The Walton Foundation to pursue a Master of Environmental Science and Management.

- Mobility Program Award (January - December 2010). Awarded by the Universidad Autónoma Metropolitana to go to the São Paulo University, Brazil.