# Administrative experience

- Member of the *Equity, Diversity, and Inclusion Committee (EDI)* committee of the Center for Limnology at the University of Wisconsin (2021-2022).

- Member of the *SCUBA* committee of the Center for Limnology at the University of Wisconsin (2021-2022).

- Founder and member of the steering committee of the Mozilla Science Lab Study Group *Deep Sea Data Squad* of the Institute for the Oceans and Fisheries (2017 - 2021). 
This group meets every week for co-working session in *R* with the idea of helping each other better programming and create a supportive coding community

- Member of the steering committee of *Equity, Diversity, and Inclusion Committee (EDI)* of the Student Society of the Institute for the Oceans and Fisheries Student Society (2018-2020).
The committee as been working to create resources that provide information about EDI policies, initiatives, and support within IOF and across UBC.

- Active member of the Student Society of the Institute for the Oceans and Fisheries