# Professional Experience

- Data analysis for the [FishGlob](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/fishglob/) project (February 2021 – May 2021). Fish biodiversity under global change – a worldwide assessment from scientific trawl surveys, project.

- Intern for Environmental Defense Fund, Mexico (June – September 2015). Analyzed data and worked in the field to see if it was feasible to design a Territorial User Rights for Fisheries (TURF) to manage a high complex system in a bay of Sinaloa, Mexico.

- Dive Center Co-Owner (Jan 2011 - July 2015). Servicios Subacuáticos Medusa. Had different roles: Managed the financial aspects of the business. Coordinated over 30 diving trips both national and international. Instructed SCUBA classes. Managed the Store (sales and inventories).

- Green Business Summit Coordinator (January 2013 - July 2013). Co-designed the agenda of the summit, managed invitations, coordinated a team of 4 people.  Global Institute of Sustainability (GIS), Instituto Tecnológico de Estudios Superiores de Monterrey (ITESM) and Arizona State University (ASU), Mexico City Campus.

<!-- - Contribution to Research as a Scientific Diver (August 2008). Estrada, D. Estudio de la biodiversidad de equinodermos y moluscos, Isla Socorro, Archipiélago de Revillagigedo. Thesis for a bachelor's degree in biology. Universidad Nacional Autónoma de México. Instituto de Ciencias del Mar y Limnología. -->

<!-- - Intern for Espacios Naturales y Desarrollo Sustentable, A.C (September 2007- December 2007). The Worked as an intern for the NGO Espacios Naturales y Desarrollo Sustentable A.C. in México City. Organized, digitalized and analyzed a butterfly data base. -->