# Invited Seminars

<!-- - Marine fish do not need visas: managing shared stocks in a changing world (April, 2022). Seminar Series, The Institute for the Oceans and Fisheries, University of British Columbia, Canada -->

- Challanges of managing transboundary stocks on the move (October, 2021). Seminar Series, Center for Limnology, University of Wisconsin-Madison, United States

- Límites dinámicos como herramientas para la protección marina en océanos cambiantes (September 2021). Webinarios del Laboratorio Nacional de Resiliencia Costera, México. Presentation available at: https://www.facebook.com/LANRESC/videos/4140220856092892

- New Research to Adaptive Allocation for Transboundary Fish Stocks (May, 2021). Lenfest Ocean Program. Presentation available at: https://www.lenfestocean.org/news-and-publications/multimedia/webinar-on-new-research-to-adaptive-allocation-for-transboundary-fish-stocks

- Marine fish do not need visas: Transboundary fisheries management under climate change (March, 2021). Seminar Series, Marine Institute, School of Fisheries, Memorial University, Canada

- Shifting MPAs for conservation and fisheries under a changing climate (March 2021). Open Channel Webinar Series, Octo group. Presentation available at: https://www.openchannels.org/webinars/2021/shifting-mpas-conservation-and-fisheries-under-changing-climate

- Efectos del cambio climático en el manejo de especies transfronterisas (January, 2020). Centro Austral de Investigaciones Científicas (CADIC-CONICET), Ushuaia, Argentina.

- Marine governance in the anthropocene: Lessons from South Africa and Latin America (July 2019). Center for Complex Systems Transition, Stellenbosch Institute for Advanced Study, Mosterdrif, Stellenbosch, South Africa.

- Building capacity for fisheries management under climate change in Latin America (2017). Weekly seminars. The United Nations Environment World Conservation Monitoring Center (UN-WCMC), Cambridge, UK.

- Hacia la creación de una base de metadatos de investigación marina en México. Multiple talks in 2017 and 2018 including Unidad Académica Sisal del Instituto de Ciencias del mar y Limnología de la Universidad Nacional Autónoma de México, Sisal, Yucatán; El Centro de Investigación y de Estudios Avanzados del Instituto Politécnico Nacional, Mérida, Yucatán; Centro Interdisciplinario de Ciencias Marinas del Instituto Politécnico Nacional, La Paz, México and Centro de Investigación Científica y de Educación Superior de Ensenada, Baja California Norte, México, among others.