# Attendance at Conferences

- **Palacios-Abrantes, J.**, Frölicher, T. L., Reygondeau, G., Sumaila, U. R., Tagliabue, A., Wabnitz, C. C. C., and Cheung, W. W. L., 2022. Timing and magnitude of climate-driven range shifts in transboundary fish stocks challenge their management. ICES/PICES Early Caeer Conference, St. John's NL, Canada

- **Palacios-Abrantes, J.**, 2019. Climate change and transboundary fisheries management, examples from North America. Species on the Move, Skukuza, South Africa

- **Palacios-Abrantes, J.**, Cheung, W.L., Sumaila, R. 2019. Challenges to Transboundary Fisheries Management in North America Under Climate Change. IMBeR Future Oceans 2, Brest, France

- **Palacios-Abrantes, J.**, Cheung, W.L., Sumaila, R. 2018. Current State and Future Scenarios for Transboundary Fisheries Management in Changing Oceans of Canada and the United States. The Effects of Climate Change of the World’s Oceans, Washington D.C., USA

- **Palacios-Abrantes, J.**, Cheung, W.L., Sumaila, R. 2017. Current State and Future Scenarios for Transboundary Fisheries Management in Changing Oceans: Gauging the Biological Tides. MARE Conference 2017 People and the Sea IX: Dealing with Maritime Mobilities, Amsterdam, Netherlands

- **Palacios-Abrantes, J.**, Arreguín-Sánchez, F., Cheung, W. W., Cisneros-Mata, M.A., Cisneros-Montemayor, A., Rodriguez, L. 2017. Towards the creation of a metadata of marine research in Mexico: a case study of the Gulf of Mexico. State of the Gulf of Mexico, 2017. Houston, Texas

- Felins, E., Handelman, T., Howard, A., **Palacios-Abrantes, J.**, Liu, R. O., and Melack, J. 2016. A Citizen Science Monitoring Protocol for the Rocky Intertidal Habitat. Multi-Agency Rocky Intertidal Network Annual Meeting, Cabrillo National Monument, San Diego, California.

- **Palacios-Abrantes, J.**, Melo, V., and Urbano, B. 2013. Iron analysis from *Octopus hubbsorum* (Cephalopoda: Octopodidae) for human health. $12^{th}$ International Symposium on Metal Ions, Punta del Este, Uruguay.

- **Palacios-Abrantes, J.**, Melo, V., and Urbano, B. 2013. Star fish source of calcium to prevent this metal’s ion deficiency. $12^{th}$ International Symposium on Metal Ions, Punta del Este, Uruguay.

- **Palacios-Abrantes, J.**, Melo V. y Urbano B. 2012. Análisis proximal de *Octopus hubbsorum* (Cephalopoda: Octopodidae) en Acapulco Guerrero (México). Congreso de la sociedad Mesoamericana para la Biología y la Conservación, Panama City, Panama.

- **Palacios-Abrantes, J.**, Melo V., y Urbano B. 2012. Análisis nutricional de callo de hacha *Atrina sp*. (Mollusca: Pinnidae) en México”. Congreso de la Sociedad Mesoamericana para la Biología y la Conservación, Panama City, Panama.

- **Palacios-Abrantes, J.**, Melo V., Jiménez H, Rivero J. 2011. Estrella de mar, un rico complemento alimenticio para comunidades costeras de bajos recursos. XV Congreso de la sociedad Mesoamericana para la Biología y la Conservación, Mérida, Mexico.

- **Palacios-Abrantes, J.**, Melo V., Jiménez H., Rivero J. 2011. Ración de Malacosoma azteca para animales como estrategia de control de plaga en Xochimilco. XV Congreso de la sociedad Mesoamericana para la Biología y la Conservación, Mérida, México.

- **Palacios-Abrantes, J.**, Luna B., Rivero J., Melo V. 2009. Influencia de factores abióticos en fase larval del Malacosoma azteca. 44º congreso Mexicano de Química. Puebla, México.

- **Palacios-Abrantes, J.**, Luna B., Issac Y., Estrada D., Melo V. 2009 Sea cucumber, underutilized source of macronutrients. 8º Simpósio Latino Americano de Ciência de Alimentos. Campinas, Brasil.

- Melo V., **Palacios-Abrantes, J.**, Rivero J., Herrera M. C., León F. 2009 The aplication of betacyanin natural pigment in food processed. 8º Simpósio Latino Americano de Ciência de Alimentos. Campinas, Brasil.

- Melo V., **Palacios-Abrantes, J.**, Rivero J., Herrera M. C., Schettino B. 2009 Retention of ß carotene and ascorbic acid in fresh and processed vegetables. 8º Simpósio Latino Americano de Ciência de Alimentos. Campinas, Brasil.