# Projects Participation

- [Solving-FCB](https://solvingfcb.org/) (2022-Current). The goal of Solving the Sustainability Challenges at the Food-Climate-Biodiversity Nexus is to support and facilitate the development of viable FCB solutions that explicitly consider their complex social and ecological contexts. PIs: *William Cheung and Rashid Sumaila, University of British Columbia*

-[McGovern]() (2022-Current). This project aims to inform the Mexican fishing industry on how climate change can affect their catches within the current century. PI: *Fabio Favoretto, Centro para la Biodivesidad Marina y la Conservación A.C. (CBMC)*

- [Lenfest](https://www.lenfestocean.org/home/research-projects/new-effort-to-inform-adaptive-allocation-strategies-for-transboundary-fish-stocks) (2021-2022). The Adaptive Allocation for Transboundary Fish Stocks project investigates options for a system of adaptive allocation, including ecological and socioeconomic tradeoffs, for two important fisheries in the U.S. Mid-Atlantic: summer flounder and black sea bass. PIs: *Rod Fujita, Environmental Defense Fund (EDF), and Arielle Levine, San Diego State University*

- [FishGlob](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/fishglob/) (2021-Current). Fish biodiversity under global change – a worldwide assessment from scientific trawl surveys, project. PIs: *Deng Palomares, The University of British Columbia and Bastien Merigot, Montpellier University*

- [MARICA](https://www.niva.no/en/projectweb/marica) (2020-2021). Mapping Patterns and Drivers of Marine Resource Conflicts to Guide Solutions project carries out the first systematic, multi-scale assessment of spatial patterns and drivers of marine resource conflicts across sub-Saharan Africa and in 3 focal case studies in Ghana, Kenya and South Africa. PI: *Elizabeth Selig, Stanford*

- [FishMip](https://www.isimip.org/about/marine-ecosystems-fisheries/) (2019-Current). The Fisheries and Marine Ecosystem Model Intercomparison Project (Fish-MIP) aims to bring together disparate marine ecosystem models to help better understand and project the long-term impacts of climate change on fisheries and marine ecosystems, and to use our findings to help inform policy. PI: *Julia Blanchard, University of Tasmania*

- [SESYNC](https://www.sesync.org/project/graduate-pursuits-request-for-proposals/ch-ch-ch-changes-using-marine-protected-areas-to) (2018-Current) This project aims to quantify the socio-economic implications that shifts in species distribution due to climate change will have on the benefits of marine protected areas worldwide. This research project is part of a [National Socio-Environmental Synthesis Center (SESYNC) - Graduate Pursuit](https://www.sesync.org/opportunities/research-thematic-pursuits/graduate-pursuits-request-for-proposals) project. *PIs: Juliano **Palacios-Abrantes**, Anneloes Mook and Talya Tenbrink*

