# Public engagement and media

- Managing fish stocks shared by nations must focus on the impacts of climate change (2022). The Conversation Canada. Available at: https://theconversation.com/managing-fish-stocks-shared-by-nations-must-focus-on-the-impacts-of-climate-change-181828

- Climate change could spark fish wars around the globe (2021). Radio interview for Quirks and Quarks with Bob McDonald (CBC). Available at: https://www.cbc.ca/listen/live-radio/1-51/clip/15893391

- Are fish on the move due to climate change? (2021). Radio interview for the Mike Smith Show. Available at https://omny.fm/shows/mike-smyth/are-fish-on-the-move-due-to-climate-change

- Fish populations are shifting around the planet and 'someone is going to lose out,' says UBC researcher (2021). Interview for Glacier Media Group. Available at: https://www.timescolonist.com/highlights/fish-populations-are-shifting-around-the-planet-and-someone-is-going-to-lose-out-says-ubc-researcher-4973909

- Climate change could spark international fish fights (2021). Interview for Canada's National Observer. Available at https://www.nationalobserver.com/2022/01/21/news/climate-change-could-spark-international-fish-fights

- The Importance of Giving Back (2021). Interview for COMPASS' Celebrating Latino Conservation Week. Available at: https://www.compassscicomm.org/the-importance-of-giving-back/

- Management of exploited transboundary fish stocks requires international cooperation (2020). Press Release, The Institute for the Oceans and Fisheries, UBC, Available at: https://oceans.ubc.ca/2020/10/21/transboundary/

- La ciencia es parte vital de nuestra visión de conservación ambiental (2019) Blog post for the Environmental Defense Fund - Mexico Blog. Available at: https://mexico.edf.org/blog/2019/06/07/la-ciencia-es-parte-vital-de-nuestra-vision-de-conservacion-ambiental?utm_campaign=edf-de-mexico_none_upd_ocn&utm_id=1559913502&utm_medium=social-media&utm_source=twitter

- Understanding the data about data: How metadatabases could improve Mexico’s ocean management (2019). Press Release, The Institute for the Oceans and Fisheries, UBC, Available at: https://oceans.ubc.ca/2019/06/12/understanding-the-data-about-data-how-metadatabases-could-improve-mexicos-ocean-management/

- Tear Down That Paywall: The Movement to Make Ocean Research Free for All (2018). Interview for *NewsDeeply, Oceans deeply* Available at: https://deeply.thenewhumanitarian.org/oceans/articles/2018/01/18/tear-down-that-paywall-the-movement-to-make-ocean-research-free-for-all

- ¿Cómo afectará el cambio climático las pesquerías del mundo? (2018) News interview for *CONACyT Prensa*. Available at:  http://www.cienciamx.com/index.php/ciencia/ambiente/24771-cambio-climatico-pesquerias-mundo

- Los peces no necesitan Visa (2018). Radio Interview in *Radio El Colégio de Michoacán*

- Crean base de metadatos de investigación marina en México (2017). Interview for *CONACyT Prensa*. Available at: http://www.cienciamx.com/index.php/ciencia/mundo-vivo/13008-crean-base-de-metadatos-de-investigacion-marina-en-mexico