---
title: "CV Juliano E. Palacios Abrantes"
author: "Email: j.palacios@oceans.ubc.ca | Web Page: www.julianopalacios.com"
date: "Las update `r format(Sys.time(), '%B, %Y')`"
site: "bookdown::bookdown_site"
output:
  bookdown::gitbook:
    lib_dir: "book_assets"
  # bookdown::pdf_book:
    # extra_dependencies: xcolor
    # toc: no
---



```{r education, child = 'sections/01-education.Rmd', eval = T}
```

\clearpage

```{r publications, child = 'sections/02-publication.Rmd', eval = T}
```

\clearpage

```{r work_progress, child = 'sections/03-work_progress.Rmd', eval = T}
```

\clearpage

```{r professional_research, child = 'sections/04-professional_research.Rmd', eval = T}
```

\clearpage


```{r workshops, child = 'sections/05-workshop.Rmd', eval = T}
```

\clearpage

```{r awwards, child = 'sections/06-award.Rmd', eval = T}
```

\clearpage


```{r teaching, child = 'sections/07-teaching.Rmd', eval = T}
```

\clearpage


```{r admin, child = 'sections/08-admin.Rmd', eval = T}
```

\clearpage


```{r professional_experience, child = 'sections/09-professional.Rmd', eval = T}
```

\clearpage


```{r Associations, child = 'sections/10-association.Rmd', eval = T}
```

\clearpage


```{r invited_seminars, child = 'sections/11-seminar.Rmd', eval = T}
```

\clearpage


```{r attended_conferences, child = 'sections/12-conference.Rmd', eval = T}
```

\clearpage

```{r projects_participation, child = 'sections/13-project.Rmd', eval = T}
```

\clearpage

```{r peer_review, child = 'sections/14-peer_review.Rmd', eval = T}
```

\clearpage

```{r other, child = 'sections/15-other.Rmd', eval = T}
```

\clearpage

```{r referees, child = 'sections/17-referees.Rmd', eval = T}
```
