---
title: "14 Mil Islas de Viaje Indonesio"
author: "Juliano Palacios Abrantes"
date: "16/01/2020"
output: html_document
---

# La Isla de Java

## Jakarta City, *te recomiendo llevar un pulmón extra*

Nuestro viaje inició en Jakarta la capital de la isla de Java, una de las mayores del país. Jakarta es una ciudad grande, densamente poblada y altamente contaminada. El aire está tan contaminado que a veces no puedes ver la cima de los edificios, la basura está por todos lados y la ciudad tiene un olor bastante desagradable. Sin embargo, Jakarta (e Indonesia en general) es una ciudad bastante segura e interesante. Puedes caminar por todos lados tomando fotos a gusto, con tu carota de turista y preguntándole a todos "do-iu-espic-inglich?" que al menos a nosotros, no nos pasó nada y nunca nos sentimos amenazados. La gente en Jakarta (e Iindonesia en general) es extremadamente amable, siempre dispuesta a ayudar o a explicarte alguna particularidad de su cultura (sobre todo aquellos que hablan inglés) y siempre están sonriendo. Me dió la impresión de que es un pueblo feliz, a pesar de la pobreza.

En un momento de nuestra caminada por Java decidimos "callejonear" y rápidamente nos encontramos en lo que yo llamaría un favela local. Ya estábamos bastante adentro como para volver así que no tuvimos más que seguir adelante. Mientreas pasábamos por una calle de un metro de anchura, a la izquierda teníamos uno de los río más contaminados que he visto en mi vida mientras que a nuestra derecha se asomabam puertas hacia "casas" extremadamente pequeñas y precarias. A la mitad del callejón, las mujeres lavaban ropa, cocinaban y le gritabana a los niños que corrían al rededor de nosotros riendo y apuntnado, como si fuéramos un circo. Ancianos bebían a la mitad del camino, y hombres sentados en tablones de madera (probablemente camas) nos observaban al pasar. El miedo se fué así como llegó e inmediatamente olvidé el peligro sintiéndome invitado a la comunidad de gente que pelea el pan del día a día. Espero no haber caído en el turismo de pobres.

Salimos sólo una noche en Jakarta, al nighs sky bar. 

Una cosa que me gustó mucho de aquí es la tolerancia religiosa. No soy muy ilustre en la historia del país... 

El puerto de Jakarta es un lugar que vale la pena visitar. 

**De cuando fuimos famosos.** Un buen día que estábamos visitando la TORRE ESTA en el centro de Jakarta se nos acercó una familia. El señor eventualmente se acercó a mi y con un ademán me extendió la mano con su cámara, yo, al ver que ellos, como nosotros, se estaban tomando la famosa selfie con LA TORRE de trás, inmediatamente accedí y me puse en posición de tomarles la foto. Después de unos breves instantes en los que mi interlocutor y su familia se veían bastante confudidos y PALABRA, les devolví la cámara y me regresé con mis amigos. Mi interlocutor, al no estar satisfecho con la foto volvió a mi pero de esta vez la Tey me hizo entender la cuestión, querían una foto conmigo, no que yo les tomara la foto. Esta fue la primera de múltiples ocaciones en las que fuimos detenidos por completos extraños para tomarse fotos con nosotros. Fueron tantas las veces que nos pararon que yo empezé a tomar fotos con los extraños para crear mi propio album, si alguien va a Indonesia avísenme si soy famoso, estilo Rodríguez en Sudáfrica. 

Imágen de los selfis. 

## Yogiakarta, templos templos y más templos

#Rice penang pac, si huele a huevo es aquí
