---
title: 'Preparando la gobernanza de los océanos a especies en movimiento:'
author: Malin L. Pinsky, Reygondeau G., Caddell R., Palacios-Abrantes J., Spijkers
  J., Cheung W.L
date: '2018'
output:
  pdf_document: default
  word_document: default
subtitle: El manejo pesquero debe anticipar los cambios en la distribución de las especies
---

- **NOTA: esta es una traducción al español del artículo:** *Preparing ocean governance for species on the move:
Policy must anticipate conflict over geographic shifts*, escrito por Malin L. Pinsky, Gabriel Reygondeau, Richard Caddell, Juliano Palacios-Abrantes, Jessica Spijkers, William W. Cheung y que se puede encontrar en el siguiente [link](http://science.sciencemag.org/cgi/doi/10.1126/science.aat2360).

- **Forma de Citar**: Malin L. Pinsky, Reygondeau G., Caddell R., Palacios-Abrantes J., Spijkers J., Cheung W.L (2018) Preparing ocean governance for species on the move: Policy must anticipate conflict over geographic shifts. Science, Vol. 360, Issue 6394, pp. 1189-1191, DOI: 10.1126/science.aat2360

----------------------------------------------------------------------------------------------------------------------------


El océano es una fuente fundamental de nutrición, dinero y empleo para miles de millones de personas a nivel mundial y con potencial de aumentar esa producción [^1]. Sin embargo, nuevas condiciones oceánicas consecuencia del cambio climático presentan serios desafíos a las pesquerías mundiales ya sea a nivel local, nacional o internacional. Un ejemplo del que ya están habiendo numerosos reportes tiene que ver con las variaciones en la distribución de animales marinos. Distintas especies de peces y otros animales se han trasladado a nuevos territorios a un ritmo promedio de 70 km por década [^2], y se espera que estos cambios continúen o se aceleren[^3]. En el presente trabajo mostramos que en las próximas décadas muchas especies probablemente se desplacen a través de fronteras marinas nacionales (y otras fronteras políticas) y dado que en términos generales las pesquerías no están preparadas para dichos desplazamientos, se esperarían potenciales conflictos entre naciones vecinas sobre los nuevos recursos compartidos.

El cambio en la distribución histórica de un stock de peces (referido desde ahora como “stock cambiante”) exacerba los desafíos pesqueros existentes. Dicho efecto contraviene el principio de "límites claros" para la gobernanza sostenible de los recursos comunes, perjudicando los incentivos para la conservación cuando nuevos *Free riders*, que no tienen responsabilidades acordadas para la conservación y gestión compartida, obtienen acceso al recurso[^4][^5]. Estos cambios también pueden incentivar la sobreexplotación regional a medida que los actores luchan por explotar un recurso que se percibe como desaparecido. Finalmente, un stock al moverse a través de las fronteras nacionales, puede encontrarse en "doble riesgo" de sobreexplotación (ya que se expone a una competencia insostenible)$^5$. Los desafíos de gobernanza generados por stocks cambiantes han sido reconocidos en ciertos casos, sin embargo, la magnitud y alcance de dicho problema no ha sido explorados y pocos esfuerzos se han llevado a cabo para abordar las consecuencias del mismo.

## Evidencias de conflictos a causa de cambios en la distribución de pesquerías 

El derecho internacional reconoce que la cooperación es necesaria para la gestión de stock pesqueros compartidos, sin embargo, desde la Segunda Guerra Mundial las disputas pesqueras han sido una causa principal de discordias militares entre estados democráticos[^6].

La llamada "guerra de la caballa" *(mackerel wars)* estalló en 2007 cuando el stock de caballa del Atlántico nor-oriental (*Scomber scombrus*), gestionado por la Unión Europea, Noruega y las Islas Feroe se trasladó a la Zona Económica Exclusiva (ZEE) de Islandia[^7]. Surgieron conflictos sobre las asignaciones apropiadas entre los actores, agravados por el desacuerdo sobre los impulsores y por lo tanto, la duración esperada del cambio. En ausencia de cooperación, la población de caballa fue sometida a una sobrepesca cada vez más intensa$^7$. 
El cambio en la distribución de especies marinas ha causado conflictos incluso entre países que hubieran cooperado estrechamente en el pasado. Durante las décadas de 1980 y 1990, las temperaturas oceánicas en la región del Pacífico Norte americano se elevaron más que el promedio histórico causando un aumento de más de 10 veces en las capturas de salmón del Pacífico (*Oncorhynchus spp.*) por embarcaciones de Estados Unidos, incrementando a su vez, las capturas de salmón proveniente de aguas canadienses$^5$. Las embarcaciones canadienses respondieron capturando salmón que migra para desovar en los Estados Unidos causando años de desacuerdo y tensiones entre las dos naciones y que sólo se solucionó seis años después con la promulgación de un nuevo acuerdo de manejo pesquero conjunto. 
El cambio en la distribución de especies marinas también presenta desafíos internos para naciones pesqueras. Históricamente en Estados Unidos, los stocks de *Blueline tilefish* (*Caulolatilus microps*) fueron capturados y manejados al sur de la frontera entre Virginia y Carolina del Norte. Cuando el *Blueline tilefish* apareció más al norte, una pesquería explotó el stock durante casi una década sin regulación hasta la creación de reglas de emergencia por parte del Servicio Nacional de Pesquerías Marinas de Estados Unidos en 2015. 
Estos casos ejemplifican un patrón general: la gestión y la gobernanza pesquera existente se basa principalmente en las distribuciones geográficas de stocks que permanecen ampliamente estáticas a través del tiempo. Sin embargo, los desafíos surgen cuando las distribuciones del stock se vuelven menos predecibles y se complican cuando los estados actúan unilateralmente para explotar la inesperable ganancia del evento.

## La Magnitud de los desafíos futuros

Los océanos han absorbido el 93% del calor causado por el cambio climático antropogénico[^8]. Si los cambios futuros en la distribución de especies marinas superan su variación histórica, entonces será necesario ajustar la gobernanza del territorio marino de acuerdo a dichos cambios. Por otro lado, escenarios menos extremos podrían resultar en una retención de las poblaciones marinas dentro de las jurisdicciones encargadas de manejarlas actualmente.
Dado que no está claro hasta qué punto los cambios futuros en la distribución de especies marinas generarán nuevas poblaciones compartidas, aumentando el potencial de conflicto entre la nación que tradicionalmente explota el recurso y la que recibirá un nuevo stock, proyectamos cambios futuros en la distribución de 892 especies de peces marinos e invertebrados comercialmente importantes en relación con las 268 ZEE del mundo.
En lugar de prever con precisión los cambios futuros, las proyecciones ayudan a delinear escenarios plausibles que ilustran el alcance de los desafíos futuros. Comparando el período que comprende entre 1950-2014 con el proyectado para 2090-2100, encontramos que muchas de las ZEE del mundo probablemente recibirán de una a cinco nuevas pesquerías transfronterizas impulsadas por el cambio climático para fines de siglo (ver la Figura). Se proyectaron hasta 10 nuevas poblaciones para algunas ZEE en el este de Asia: una región donde las nuevas poblaciones transfronterizas podrían empeorar las relaciones marítimas ya complicadas por territorios en disputa, superposición de reclamos de ZEE y pesca ilegal.
Más aun, se espera que el número de ZEE con nuevas poblaciones transfronterizas alcance 46 ± 8 (± error estándar) o 60 ± 4 en 2060 ( 57 ± 4 o 85 ± 22 en 2080) bajo escenarios de alta mitigación [Ruta de Concentración Representativa (RCP) 2.6] o sin mitigación (RCP 8.5) de gases de efecto invernadero, respectivamente (ver la figura). Si se limita la emisió de gases de efecto invernadero se reduciría, por lo tanto el potencial de nuevos conflictos pesqueros. En total, se prevé que las nuevas poblaciones transfronterizas estén presentes en un 23% (RCP 2.6) a un 35% (RCP 8.5) de las ZEE globales para el año 2100 (ver la figura). 
En los trópicos, es probable que las pesquerías salgan, pero no entren, un proceso que genera preocupación adicional de seguridad alimentaria. Se proyectó que la mayoría de los países recibirían del 1 al 30% de las capturas pesqueras de nuevas poblaciones para 2100, estando los porcentajes más altos en regiones templadas (ej., Australia o países alrededor de los mares *Báltico* y *Bering*) y el más alto en zonas pesqueras antárticas compartidas (92%). Observamos que los conflictos pasados, incluso sobre una única especie con bajos volúmenes de captura, han sido sustanciales. 

## Mayores problemas en la gobernanza

Actualmente, el marco legal para la regulación internacional pesquera no trata directamente con stocks cambiantes. A nivel mundial, la principal fuente de obligaciones para la gobernanza de los recursos pesqueros sigue siendo la Convención de las Naciones Unidas sobre el Derecho del Mar de 1982 (UNCLOS, por sus siglas en inglés), que entró en vigor en 1994. Bajo UNCLOS, los estados deben garantizar que las pesquerías situadas en sus ZEE no estén en peligro por sobrepesca. Esto último abre la posibilidad a que las regulaciones nacionales actúen como base para un manejo provisorio de posibles stocks cambiantes. UNCLOS obliga a los estados a cooperar en el manejo pesquero de las "poblaciones transfronterizas" que cruzan dos o más ZEE, o entre una ZEE y alta mar. En 1995, el régimen pesquero de UNCLOS fue reforzado por el Acuerdo de las Naciones Unidas sobre Poblaciones de Peces (UNFSA, por sus siglas en inglés), que se aplica específicamente a las poblaciones transfronterizas y altamente migratorias y que entró en vigor en 2001. Dicho acuerdo reforzó las obligaciones nacionales de cooperación aplicando un enfoque precautorio al manejo pesquero. A pesar de su influencia constructiva en la legislación pesquera internacional, el UNFSA no ha centrado la atención en stocks cambiantes que ocuparán territorios aledaños a los históricamente conocidos.

Las organizaciones regionales de ordenación pesquera (RFMOs, por sus siglas en inglés) siguen siendo el principal cuerpo administrativo para especies transfronterizas. Sin embargo, muchas RFMOs gestionan especies únicas como el atún o el salmón, y la afluencia de especies adicionales se encuentra más allá de sus competencias individuales. A pesar de los avances recientes, las poblaciones de peces en grandes partes de los océanos se encuentras sobre un mal manejo-acá podes usar dos puntitos o el guioncito- una tendencia que puede verse exacerbada por el cambio de sus distribuciones. 

Son pocas las organizaciones que han establecido una posición clara sobre la elaboración de regulaciones para nuevas pesquerías, una laguna que a menudo permite que poblaciones emergentes sean fuertemente explotadas antes de que se desarrollen estándares significativos[^9]. Por otra parte, ha habido poca o ninguna cooperación entre distintas RFMOs, interacciones con otros organismos reguladores o tratados internacionales para tratar el potencial de futuras poblaciones compartidas. Finalmente, existe una preocupación general por la falta de gestión basada en ecosistemas (en vez de especies específicas) por parte de las RFMOs, incluyendo la poca consideración del impacto pesquero a especies no gestionadas por la propia RFMO.

Si bien los intentos de resolver conflictos legales actuales no se han concluido en gran medida (por ejemplo, los procesos legales en la disputa por la "caballa" fueron descontinuados), la aparición de nuevos stocks transfronterizos podría acelerar procesos legales en el futuro. Los tribunales internacionales se han mostrado receptivos a las peticiones de una gestión pesquera más responsable y han adoptado prácticas de largo plazo en algunos casos, sin embargo, históricamente han tenido poca consideración por factores ambientales en disputas territoriales, y los stocks cambiantes no ha jugado un rol importante en el diseño de los límites políticos administrativos. Del mismo modo, el marco legal internacional actual no facilita el posible ajuste de límites nacionales en respuesta al cambio climático en los océanos y las decisiones legales no siempre resuelven los conflictos: China se negó a participar en un reciente proceso relacionado con el Mar Meridional de China, lo que hace que las relaciones pesqueras sean vulnerables a acciones unilaterales en torno a los cambios en esta región.

## Soluciones de manejo para stocks cambiantes

Conflictos pasados, la posible existencia de nuevos stocks transfronterizos y la falta de cobertura en los marcos legales actuales sugieren que se necesitan nuevos enfoques sustanciales para evitar futuros conflictos. El primer paso para llegar a estos es la planificación anticipada de una gestión cooperativa por parte de las autoridades, la cual exige un énfasis en la adquisición de proyecciones confiables de cambio en la distribución de las especies y las incertidumbres asociadas. Las negociaciones sobre stocks compartidos son más fáciles cuando existen hechos previamente acordados, que pueden ser facilitados por medio de datos generados por instituciones científicas multilaterales o independientes, como el Panel Intergubernamental sobre Cambio Climático (IPCC, por sus siglas en inglés). Cabe destacar, sin embargo, que todas las proyecciones deben interpretarse con cautela ya que el potencial de incertidumbre existente en la simulación de sistemas ecológicos puede perjudicar las evaluaciones locales de los beneficios y costos de establecer una cooperación[^10][^11]. 

Para las RFMOs, las revisiones de desempeño proporcionan un proceso ya establecido para la consideración de stocks cambiantes, aunque el éxito dependerá no solo de la capacidad, sino que también de la adopción de una cultura de reflexión crítica. El intercambio de datos con otros organismos también es vital para tratar el tema. La Comisión para la Conservación de los Recursos Vivos Marinos Antárticos (CCAMLR, por sus siglas en inglés) ha sido ejemplar a este respecto ya que ha establecido acuerdos de colaboración con las RFMOs vecinas para supervisar el movimiento de poblaciones a través de fronteras regulatorias. La CCAMLR también ha forjado acuerdos con otros organismos sectoriales para considerar la posible huella ecológica de una industria pesquera cambiante.

Para informar una gestión genuinamente colaborativa, la cooperación debe extenderse más allá del intercambio de datos. Por ejemplo, para cumplir con sus responsabilidades bajo UNCLOS y UNFSA, las RFMOs deben aceptar la perspectiva de una supervisión compartida y acordar responsabilidades regulatorias para especies que aumenten su presencia en áreas vecinas. La coincidencia de dos o más stocks en un área determinada ya ha generado tensiones, como las que existieron entre la Organización de Pesquerías del Atlántico Noroccidental (NAFO, por su siglas en inglés) y la Comisión de Pesquerías del Atlántico Nordeste (NEAFC, por su siglas en inglés) en la década de 1990 y que sólo se resolvieron cuando se implementaron responsabilidades compartidas. La CCAMLR ha adoptado un enfoque de cooperación diferente y más constructivo, en parte al imponer una mayor supervisión precautoria de las nuevas pesquerías como es el caso del atún desplazado por el calentamiento de los océanos$^9$.

El intercambio de datos y la gestión colaborativa pueden contribuir a informar en procesos regulatorios vitales para reducir la presión sobre stocks cambiantes. Ejemplos de estos son la implementación de manejo espacial y el establecimiento de zonas de no-pesca. Las mentalidades de gestión también siguen siendo un desafío fundamental que puede socavar la cooperación, especialmente la percepción de que una parte "gana" y la otra "pierde" cuando una población se desplaza geográficamente [^12]. La teoría de juegos proporciona lecciones para incentivar la cooperación como por ejemplo el incluir en las negociaciones recursos no necesariamente relacionados con las pesca$^5$. Negociaciones más generales sin embargo, pueden convertir a las pesquerías en simple monedas de cambio para negociar otras prioridades políticas y económicas, como lo sugieren las negociaciones de Brexit en el Reino Unido. Casos exitosos incluyen el del Tratado del Salmón del Pacífico de EE.UU-Canadá, donde la creación de un fondo de conservación ayudó a estabilizar las relaciones creando una vía alternativa para la compensación, a menudo denominada "pago colateral"[^13]. Enfoques similares son ilustrados por Noruega y Rusia al intercambiar acceso a pesquerías dentro de sus ZEE para equilibrar los cambios en la distribución de los stocks compartidos: un importante ejemplo de flexibilidad en la utilización de los recursos del Ártico. También se ha sugerido comerciar arenque, bacaladilla o acceso a otros recursos pesqueros para ayudar a resolver la disputa sobre la caballa islandesa[^14].

A pesar que en la actualidad los procesos multilaterales generalmente se centran en cuestiones específicos para ayudar a asegurar el apoyo institucional necesario, la utilidad de los pagos colaterales sugiere que nuevos acuerdos bilaterales (o multilaterales) relacionados con stocks cambiantes serán más efectivos si se negocian en altos niveles políticos, en vez de la simple gestión pesquera. Por ejemplo, se debate activamente si las pesquerías deberían incluirse en las negociaciones de las Naciones Unidas sobre Biodiversidad Marina Fuera de Jurisdicciones Nacionales (BBNJ, por sus siglas en inglés), a pesar de que este proceso busca expresamente la integración entre los sectores de gobierno. Una de las principales preocupaciones con este sistema de propiedad recae en que actualmente, el acceso a las RFMOs está restringido a aquellos que tienen un "interés real" en el stock y los derechos participativos están fuertemente guardados por los miembros actuales$^14$[^15]. Las RFMOs del Atlántico Norte, que enfrentan cambios geográficos en varias pesquerías importantes, actualmente están cerradas para nuevos miembros$^9$$^15$.

Hoy en día, muchas pesquerías están manejadas en referencia a principios espaciales y estabilidad relativa del stock, en las que las cuotas nacionales de captura se basan en patrones históricos de presencia del stock en cada país y área geográfica. Un importante primer paso hacia la adaptación a pesquerías en movimiento seria El cambio de dichas políticas hacia una asignación de captura (o esfuerzo) objetiva y regularmente actualizada que refleje cambios en la distribución del stock. Por otro lado,  desarrollar permisos de pesca que sean intercambiables a través de fronteras políticas, como lo considera en cierta medida la Comisión Internacional para la Conservación del Atún Atlántico (ICCAT) y la Organización de Pesquerías del Atlántico Noroccidental (NAFO)$^15$ representaría un enfoque intrigante y alternativo. Las regiones con límites marítimos en disputa seguirán siendo especialmente propensas a conflictos y los cambios de distribución pueden requerir consideración adicional en el proceso de delimitación fronterizo así como en arreglos específicos bilaterales sobre recursos compartidos. 

Los variaciones en distribución de especies marinas impulsados por el cambio climático representan un problema de gobernabilidad creciente que afecta a todas las naciones del mundo. Un futuro alternativo de gestión no cooperativa generalizada de nuevas poblaciones transfronterizas aumenta el riesgo a la sobreexplotación de recursos pesqueros, disminuye el suministro mundial de alimento y medios marinos de subsistencia, perjudica las relaciones internacionales y genera conflictos políticos que podrían extenderse a otras áreas de la política internacional. Sin embargo, los desafíos se pueden mitigar a través de estrategias de gobernabilidad con visión de futuro. Mediante acuerdos adaptables entre los estados esperamos que las pesquerías marinas continúen brindando la gran cantidad de oportunidades nutricionales, de subsistencia y económicas en las que confían miles de millones de personas en todo el mundo.

- **Forma de Citar (Artículo original)**: Malin L. Pinsky, Reygondeau G., Caddell R., Palacios-Abrantes J., Spijkers J., Cheung W.L (2018) Preparing ocean governance for species on the move: Policy must anticipate conflict over geographic shifts. Science, Vol. 360, Issue 6394, pp. 1189-1191, DOI: 10.1126/science.aat2360

[^1]: C. J. Costello et al., Proc. Natl. Acad. Sci. U.S.A. 113, 5125 (2016).
[^2]: E. S. Poloczanska et al., Nat. Clim. Change 3, 919 (2013).
[^3]: W. W. L. Cheung, G. Reygondeau, T. L. Frölicher, Science 354, 1591 (2016).
[^4]: E. Ostrom, J. Burger, C. B. Field, R. B. Norgaard, D. Policansky, Science 284, 278 (1999).
[^5]: K. A. Miller, G. R. Munro, U. R. Sumaila, W. W. L. Cheung, Can. J. Agr. Econ. 61, 309 (2013).
[^6]: S. M. Mitchell, B. C. Prins, Int. Stud. Q. 43, 169 (1999).
[^7]: J. Spijkers, W. J. Boonstra, Reg. Environ. Change 17, 1835 (2017).
[^8]: M. Rhein et al., in Climate Change 2013: The Physical Science Basis. Contribution of Working Group I to the Fifth Assessment Report of the Intergovernmental Panel on Climate Change, T. F. Stocker et al., Eds. (Cambridge Univ. Press, Cambridge, 2013), pp. 255–316.
[^9]: R. Caddell, Int. J. Mar. Coast. Law 33, 199 (2018).
[^10]: K. Miller et al., Prog. Oceanogr. 87, 338 (2010).
[^11]: S. Polasky, S. R. Carpenter, C. Folke, B. Keeler, Trends Ecol. Evol. 26, 398 (2011).
[^12]: G. R. Munro, Can. J. Econ. 12, 355 (1979).
[^13]: K. A. Miller, G. R. Munro, Mar. Resour. Econ. 19, 367 (2004). 
[^14]:P. Ørebech, Int. J. Mar. Coast. Law 28, 343 (2013).
[^15]: A. Serdy, The New Entrants Problem in International Law (Cambridge Univ. Press, Cambridge, UK, 2015).

<!-- Global site tag (gtag.js) - Google Analytics -->
<head>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-105699898-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-105699898-3');
</script>
</head>
