---
title: Evaluación bioeconómica del plan de recuperación de la pesquería de callo de
  hacha (Atrina maura, Atrina tuberculosa & Pinna rugosa) de la bahía de La Paz, Baja
  California Sur
author: Juliano Palacios Abrantes, Juliana Herrera Correal, Salvador Rodríguez, Jacy
  Brunkow y Renato Molina
date: "11/20/2018"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
---

- **NOTA: esta es una traducción al español del artículo** *Evaluating the bio-economic performance of a Callo de hacha (Atrina maura, Atrina tuberculosa & Pinna rugosa) fishery restoration plan in La Paz, Mexico.* escrito por Juliano Palacios Abrantes, Juliana Herrera, Salvador Rodríguez, Jacy Brunkow y Renato Molina y que se puede encontrar en el siguiente [link](https://doi.org/10.1371/journal.pone.0209431).

- **Palacios-Abrantes J**, Herrera-Correal J, Rodríguez S, Brunkow J, Molina R (2018) Evaluating the bio-economic performance of a Callo de hacha (*Atrina maura, Atrina tuberculosa & Pinna rugosa*) fishery restoration plan in La Paz, Mexico. *PLoS ONE* 13(12): e0209431. https://doi.org/10.1371/journal.pone.0209431

<center>
<a span class="label label-success" href= "Translations/Callo_de_Hacha_Esp.pdf" >Descargar traducción en PDF</span></a>
</center>
------------------------

# Introducción 

Las pesquerías artesanalas (*menor escala*) de América Latina han sido reonocidas por su aportación a las economías regionales y su importancia en el bienestar de las comunidades costeras [1], desafortunadamente, las propias características de dichas pesquerías representan un reto al manejo pesquero adecuado [2]. Este es el caso de las pesquerías de México, uno de los mayores productores de pescados y mariscos de América Latina donde el 97% de los barcos pesqueros son artesanalas [2] y donde hay evidencia clara de sobreexplotación y mal manejo de recursos pesqueros [3,4]. Algunos ejemplos de dicho mal manejo en la costa del Pacífico inluyen la almeja chocolarta (*Megapitaria squalida*) [5]; el abulón azul (*Haliotis fulgens*) y amarillo (*Haliotis corrugata*) [6]; mientras que en la costa del Atlántico, se encuentran peces pelágicos como **macarela?** (*Scomberomorus maculatus*) y *red snapper* el guachinango? (*Lutjanus campechanus*) [3]. En respuesta, la recuperación de pesquerias deterioradas se vuelve una prioridad para que las comunidades que dependen de éstas puedan obtener los beneficios de la pesquería a través de un manejo pesquero sustentbale que asegure el bienestar de futuras generaciones [4,7,8]

El presente estudio examina un esfuerzo comunitario para recuperar una pesquería artesanal de la ensenada de La Paz, Baja California Sur, México. La pesquería de callo de hacha se compone de tres especies disferentes: *Atrina maura, Atrina tuberculosa* and *Pinna rugosa* y representa uno de los productos mejor valorados de la pesca artesanal de la región [9]. Con precios históricos de hasta US 23 por kg en La Paz [10], los pescadores reportaron un precio en abril de 2018 de US 21 por kg de callo. Dicho precio es 50% más alto que otros moluscos del mismo estilo en el mercado de mariscos del país [10]. 
El manejo paesquero en México se encuentra bajo la gestión de varios sub-organismos dentro del Ministerio de Agricultura, Ganadería, Desarrollo Rural, Pesca y Alimentación ("Secretaría de Agricultura, Ganadería, Desarrollo Rural, Pesca y Alimentación"; SAGARPA). La principal ley de manejo pesquero en México es la "Ley General de Pesca y Acuacultura Sustentables (LGPAS)" [11], que establece las obligaciones y pautas para la mayoría de las pesquerías en el país a través de la "Carta Nacional Pesquera" [12]. Por ley, el Instituto Nacional de Pesca (INAPESCA) está encargado de recomendar cuotas de pesca al Consejo Nacional de Pesca (CONAPESCA), que luego es responsable de implementar las acciones de manejo necesarias para cumplir con esa recomendación. La vigilancia y monitoreo de las actividades pesqueras son responsabilidad de CONAPESCA y de la Secretaría de Marina (SEMAR) [11]. A pesar de estos requisitos, las pesquerías como el callo de hacha carecen de un plan de manejo adecuado o de una norma oficial [12], lo que hace que la mayoría de las pesquerías artesanales del país operen bajo acceso abierto [13,14]. En 2018, prácticas insustentables llevaron a la pesquería de callo de hacha de la encenada de La Paz al colapso [15,16]. Según los locales, los años de mal manejo pesquero, corrupción y falta de monitoreo y vigilancia llevaron el recurso a tal grado de sobreexplotación que tuvo que cerrarse la pesquería [15,16]. Esto hizo que los pescadores se enfrentaran a una falta importante de ingresos lo que creó un fuerte incentivo para no respetar la veda y seguir pescando el recurso tanto en la ensenada como en otros lugares [15,16].

Esta situación llevó a un esfuerzo local para recuperar la pesquería y, con ello, la estabilidad de la comunidad pesquera. Una ONG local, Noroeste Sustentable (NOS), se asoció con la comunidad pesquera del Manglito en la ensenada de La Paz para lanzar un plan conjunto de restauración de la pesquería de callo de hacha y la ensenada. La iniciativa buscaba aumentar la biomasa hasta cantidades necesarias para realizar una pesca comercial sustentable y, al mismo tiempo, ayudar a la comunidad a obtener derechos de propiedad sobre el recurso e incentivar una administración sustentable del recurso [17,18]. La obtención de derechos de propiedad sobre el recurso era esencial para la comunidad si querían beneficiarse del plan de restauración y garantizar la pesca sustentable [4]. NOS pudo financiar a los pescadores para que participaran en varias actividades relacionadas con el plan de recuperación, lo que se tradujo en más de cuatro años de monitoreo de la biomasa del callo de hacha en la ensenada. El plan de recuperación fue cuidadoso al considerar no solo las condiciones biológicas del stock, sino también los marcos económicos y legales que rigen a la pesquería, así como la dinámica social de la comunidad pesquera; todas identificadas previamente como componentes importantes de la restauración de la pesca [16,19-21].

Crear capital social, es decir, determinar reglas dentro de comunidades estrechamaente unidas, ha sido clave para el desarrollo comunitario de manejo pesquero en América Latina [22].

El programa de recuperación incorporó con éxito esta noción y trabajó para construir capital social al involucrarse con la comunidad para desarrollar conjuntamente sus objetivos sociales, económicos y ambientales. El programa se centró en promover la autoorganización y la aplicación de la ley, así como en la organización de campañas de información que se utilizaron para difundir prácticas de pesca sostenibles. Los talleres dirigidos por NOS también brindaron un espacio para discutir la organización de la comunidad, solucionar problemas internos y determinar estrategias de manejo y políticas de pesca. Estas actividades les dieron a los pescadores un sentido de propiedad sobre el recurso, les permitieron establecer sus propias reglas internas para la aplicación y promovieron métodos de captura sostenibles. Finalmente, el proceso también ayudó a superar las diferencias dentro de la comunidad y dio como resultado que los pescadores formaran un colectivo cooperativo. El colectivo u organización ("Organización de Pescadores Rescatando la Ensenada"), fue clave para controlar la cosecha ilegal, así como para garantizar los derechos de propiedad sobre un recurso que finalmente se recuperó. Esta transición condujo a la pesquería, al menos desde la perspectiva de los pescadores, desde el acceso abierto de facto a un sistema basado en el derecho de propiedad [17,18].

Si bien existen varios casos exitosos de restaruación de pesquerías a nivel mundial para distintas especies como el jurel (*Scomberomorus cavalla*), el bajo puntiagudo (*Marone saxatilis*) y las vieiras (*Placopecten magellanicus*) [21], muy poco ha sido documentado referente al desempeño de pesquerías mexicanas [3], como al del callo de hacha en La Paz. 

Dado el potencial de reabrir una pesquería de alto valor, el objetivo del presente estudio fue evaluar el desempeño del plan de restauración del callo de hacha en términos de biomasa y su equivalencia económica. El análisis se basó en los datos biológicos colectados desde el cierre de la pesquería, así como una evaluación de las mejores variables económicas disponibles para su operación. Los resultados sugieren que, después de cuatro años (2011-2014), el recurso se recuperó sustancialmente lo que hace de la pesquería un potencial negocio rentable con beneficios significativos para la comunidad. Sin embargo, la alta incertidumbre en las muestras biológicas dificulta el análisis económico, ya que, si bien la pesquería podría ser rentable, los escenarios más pesimistas proporcionan una advertencia contra expectativas altamente positivas, ocultando los verdaderos beneficios de la pesquería de callo de hacha de la ensenada de La Paz.

# Materiales y Métodos

En el presente estudio se utilizó la biomasa de callo de hacha y valor económico de la pesquería para determinar el éxito del plan de recuperación por lo que los métodos se dividen en tres secciónes: estimación de biomasa, análisis económico y fuente de datos.

## Estimación de biomasa

La biomasa total de callo de hacha en la ensenada fue estimada a partir de abundancias promedio considerando la estructura de tallas de la población [23]. Inicialmente se estimó el peso de cada individuo medido (*W*) utilizando una ecuación de crecimiento alométrico [24]: 

$$W = a (L^b)$$

donde *a* es una constante, *L* es el tamaño del individuo y *b* es el crecimiénto intrínsico de la espécie. Los valores de *a* y *b* fueron tomados de Serrano-Guzmán (2004) [24]. Posteriormente se estimó el peso promedio (*$\bar{W}$*) de acuerdo a la siguiente ecuación [23]:

$$\bar{W} = \sum^n_{i=1}\frac{X_i}{n_i}$$

donde *$X_i$* es el peso agregado de todos los individuos del cuadrante *i* y *n* es el area muestreada en cada cuadrante. El peso promedio fue utilizado para estimar la biomasa pomedio (*B*) multiplicando *$X_i$* por el área total ocupada por el recurso en la ensenada, así mismo, se estimó la varianza del peso y biomasa promedio con intervalos de confianza (95%) utilizando el método descrito por DeLong et al (1988) [25]. La biomasa extraíble fue estimada utilizando únicamente individuos mayores a 14 cm, la talla mínima determinada por la ley mexicana [12] y se asumió que lo que se vende principalmente es el músculo abductor del callo de hacha, estimado en 25% del peso total del individuo [26].

La limitatne principal de este análisis fue la imposibilidad de proyectar la dinámica poblacional debido a restricciones en los datos y el número de observaciones disponibles. Un intento inicial de establecer una relación entre la biomasa reproductora y nuevos reclutas tuvo que ser descartado debido al bajo número de observaciones disponibles (Fig. S1). Además, existe un conocimiento biológico limitado de la población lo que impidió determinar si ésta era autosuficiente (en términos de crecimiento poblacional) o si las larvas de nuevos reclutas provenían de fuentes externas. 

Para lidiar con esta limitación pero aún proporcionar información sobre la viabilidad económica de la pesquería se asumió que la población estaba en equilibrio en el último año muestreado debido al bajo grado de variación con respecto al año anterior. Posterioremtne se realizaron proyecciones asumiendo que el stock estará en equilibrio y sometida a una mortalidad pesquera fija. Así, para cada año la biomasa capturable disponible (*H*) se proyectó aleatoriamente a partir de una distribución normal con un componente de ruido de la siguiente manera:

$$H{(\pi|\mu,\sigma^2)} = \frac{1}{\sqrt{2\pi\sigma^2}}e^\frac{R-\mu^2}{2\sigma^2}$$


donde *π* es una variable aleatoria con distribución normal, ($\mu$) es la biomasa media en equilibrio de individups mayores a 14 cm y ($\sigma$) es la desviación estándar. Para todos los años, la mortalidad poblacional por pesca se estableció en 20% de *H*, según lo recomendado por la carta nacional pesquera mexicana [12] y utilizada en otras pesquerías similares [23]. Al incluir un componente aleatorio en la estimación de biomasa, el análisis captura posibles variaciones poblaionales que puedieran influenciar la disponibilidad anual de biomasa capturable. 

Dados los supuestos utilizados en el análisis (Tabla S1), es probable que las estimaciones presentadas en este artículo sean conservadoras ya que, si el stock aún está en vías de recuperación hacia un nivel mayor a la biomasa en equilibrio, un punto de producción más bajo podría sostenerse en el futuro.

## Análisis económico

El modelo económico fue desarrollado para estimar la rentabilidad de la pesquería del callo de hacha, sin embargo éste se puede adaptar a otras pesquerías (Archivo S2, *Excel*). El análisis funciona como un simulador de escenarios y considera diferentes pasos a lo largo del proceso de pesca (desde la biomasa capturable disponible, hasta variables económicas como precio de venta y costos de pesca). Para calcular los beneficios económicos generados por la pesquería, la captura (*C*) se estimó en cada simulación a partir de un valor aleatorio de distribución normal de la siguiente manera:

$$C = (H*F) *CF$$

donde *F* es la mortalidad por pesca y *CF* es el factor de conversión del músculo individual. El costo total de la acividad pesquera (*Tc*) se estimó a partir de los costos fijos que fueron divididos en costos operacionales y específicos de la embarcación y costos variables divididos en costo por viaje y por unidad de captura. Esta diferenciación se hizo ya que la pesquería del callo de hacha tiene costos fijos anuales asociados con la operación de la embarcación y el acceso a la pesquería, y costos variables asociados con el esfuerzo de pesca y el manejo del producto. Por ejemplo, cada pescador debe pagar un permiso anual de pesca y embarcación (costo fijo anual) y para cada embarcación utilizada (unidad de esfuerzo) el pescador debe cubrir el combustible y aceite (costo fijo por viaje). Una vez que se lleva a cabo la operación de pesca, los costos como bolsas de hielo y los costos de combustible utilizados en el traslado del producto (si este nos e vende en playa) dependen de la cantidad de captura (unidad de captura). De esta manera, el costo operacional de la actividad pesquera (*OFC*) se calculó a partir de:

$$OFC = \sum_{j=1}^{n} Yc$$


donde *Yc* es igual a los costos anuales relacionados con la operación de la pesquería, y *j* representa las diferentes fuentes de costo. El índice de tiempo se ha omitido para mayor claridad. El costo fijo de la embarcación (*VFC*) fue estimado a partir de:

$$VFC = (\sum_{j=1}^{n} Bc)*Bu$$

donde *Bc* representa los costos fijos anuales relacionados únicamente con la disponibilidad de la embarcación y *Bu* representa la fracción relativa de la capacidad total de la embarcación utilizada para pescar callo de hacha. Finalmente, el costo variable (*VC*) se computó como:

$$ VC = - (E *Ce) + (C * Cc)$$

donde *E* es el esfuerzo (número de viajes necesarios para la captura *C*), *Ce* es el costo por unidad de esfuerzo, definido por la suma de los costos por viaje de pesca, y *Cc* es el costo por unidad de captura. El costo total de pesca (*Tc*) es el resultado de la suma de *OFC*, *VFC* y *Vc.*

El ingreso pesquero (*R*) se estimó multiplicando *C* por la proporción del músculo abductor del callo multiplicado, a su vez, por el precio de venta. El Valor Presente Neto (*NPV*) se descontó y proyectó durante un período de 10 años de la siguiente manera:

$$ NPV = \sum_{y=0}^{y=10}\frac{R- (Tc - Tax)}{(1+r)^y} $$

donde *Tax* son impuestos, *y* representa el año en curso y *r* es la tasa de descuento. Se asumió que la tasa de descuento era del 10%. Se utilizaron tasas de descuento adicionales (20, 30, 40 y 50%) para probar la sensibilidad del modelo a este supuesto.

Se llevó a cabo una simulación de Monte Carlo con un total de 1000 ejecuciones por escenario. Para cada año de simulación, el modelo determinó aleatoriamente la biomasa de disponible para captura a partir del promedio de la biomasa en equilibrio (± s.d). Todas las demás variables se mantuvieron constantes a lo largo de las simulaciones.

## Fuentes de datos

El análisis del presente trabajo se realizó a partir de los datos biológicos de *Atrina maura, A. tuberculosa* y *Pinna rugosa* que constituyen la pesquería de de callo de hacha en la Ensenada de La Paz. Los datos fueron recopilados por los pescadores con el apoyo de NOS a través de una campaña de monitoreo anual desde 2011 hasta 2014 (datos sin procesar en datos S1). Dado que estas tres especies comparten características biológicas similares, toda la población muestreada fue considerada como un solo stock [27]. Este supuesto es factible ya que el análisis no modela la dinámica poblacional de la especie y a pesar de que se perdió especificidad, dicho supuesto permitió tener una idea más amplia de la rentabilidad de la pesquería de callo de hacha.

El área habitable total del recurso en la ensenada de La Paz es de 1,330 ha, sin embargo el muestreo biológico se limitó a 176 ha, dividido en cuadrantes de una hectárea. En cada cuadrante, los pescadores midieron hasta 114 individuos y luego contaron el resto (sin medirlos). Una densidad superior a 114 individuos por cuadrante solo se encontró en las muestras de 2013 y 2014 (Tabla 1).
Los datos sin procesar presentaron varias inconsistencias a lo largo de los años de monitoreo que tuvieron que ser consideradas al realizar el análisis. Primero, para estimar el tamaño de los individuos que se contaron pero no se midieron, se utilizó una proporción del peso bruto medido (Ec. 1). Se asumió que la estructura de tallas de la población medida representaba de manera adecuada la estructura general de todo el cuadrante. Por ejemplo, si el 10% de los individuos medidos de un cuadrante tenían 18 cm de longitud y, por lo tanto, cada uno pesaba 100 g, entonces el 10% de los individuos de dicho cuadrante que fueron contados (pero no medidos) tenían la misma longitud y, por lo tanto, el mismo peso individual. 

#### AQUI ####
En segundo lugar, 16 cuadrantes, cuatro en 2013 y 12 en 2014, presentaron una biomasa consistentemente mayor que todos los demás cuadrantes de la muestra para esos años. Para lidiar con este patrón, asumimos que había dos subpoblaciones en el stock, una en la que los cuadrantes presentaban densidades altas y otra en las que las cuadradas tenían densidades bajas. Tercero, y final, el área de muestreo fue inconsistente a lo largo de los años debido a los diferentes métodos utilizados (es decir, transectos de 5 m frente a transectos de 50 m por cuadrante) y un número diferente de cuadrantes muestreados. Por lo tanto, para determinar la biomasa total, extrapolamos de la muestra a todo el cuadrante y a la cala, teniendo en cuenta, como parte del método, las diferentes áreas que fueron muestreadas.
Para capturar la incertidumbre asociada con los métodos de muestreo, así como la abundancia general informada por sus resultados, subdividimos los datos en cuatro muestras (Fig. 1). Cada una de estas muestras representa una estimación de biomasa potencial diferente dentro de la cala, que luego utilizamos para estimar los parámetros aleatorios utilizados en el análisis económico (μ ± σ Eq 3). La muestra 1 da cuenta de todo el conjunto de datos, incluidos los individuos contados y medidos, así como todos los cuadrantes. La muestra 2 incluye solo los cuadrantes con alta biomasa durante los últimos dos años de monitoreo. La muestra 3 excluye los cuadrantes de la muestra 2 y explica tanto los individuos medidos como los contados. Finalmente, la Muestra 4 incluye solo aquellos cuadrantes donde se midieron los individuos, pero no se contaron. Las muestras 1, 3 y 4 se extrapolaron a 1330 ha, mientras que la muestra 2 se extrapolaron a 4 ha en 2013 y 12 ha 2014, según la cantidad de cuadrantes muestreados con alta biomasa.
Sobre la base de las cuatro muestras, desarrollamos cuatro escenarios económicos para establecer la rentabilidad de la pesquería del callo de hacha (Fig. 1). Cada escenario difiere del otro únicamente por la biomasa del equilibrio. Por lo tanto, todas las variables económicas y suposiciones de gestión permanecieron fijas a lo largo del análisis. Pesca y parámetros económicos directamente relacionados con el callo de hacha la pesca se obtuvo de entrevistas informales con pescadores, administradores y personal de NOS. La literatura gris también se usó cuando no había literatura científica o documentos legales disponibles (Tabla 2). Para todos los valores, el tipo de cambio del dólar se tomó de Banamex Bank el 26 de abril de 2016.

# Resultados

## Resultados biológicos

Según nuestro análisis, la biomasa aumentó significativamente en las cuatro muestras biológicas como resultado del cierre en la cala (Tabla 3). En particular, para las muestras 1 y 2, la biomasa total y extraíble se triplicó de 2013 a 2014. Como se esperaba, nuestras estimaciones arrojaron el valor más alto de la biomasa total para la Muestra 1. Para las muestras 3 y 4, la biomasa total aumentó ligeramente con el tiempo Sin embargo, los valores no cambiaron tan dramáticamente como sugerirían las primeras dos muestras (Tabla 3). Las muestras 1 y 2 mostraron la misma tendencia hasta 2013, cuando la pesquería comenzó a mostrar signos de recuperación, ya que la biomasa alcanzó 4,44 toneladas para la muestra 3 y 5,98 toneladas para la muestra 4, casi el doble de los valores de 2011. En general, la muestra 4 mostró la más baja La biomasa aumenta con el tiempo.

## Resultados económicos

Después de realizar las simulaciones de Monte Carlo utilizando cada uno de los parámetros estimados de las submuestras, nuestros resultados sugieren que la pesquería del callo de hacha es una actividad rentable (VPN positivo) en dos de los cuatro escenarios económicos (Fig. 2). Los resultados indican que la rentabilidad neta se obtiene para los escenarios 1 y 2, mientras que los escenarios 3 y 4 conducirán a pérdidas netas.
A pesar de tener un VAN positivo, en términos de distribución, los escenarios 1 y 2 también presentan un alto grado de dispersión. Para ambos, el VPN máximo posible es más de 2 veces el promedio, mientras que la diferencia para los escenarios 3 y 4 es relativamente pequeña. Además, la desviación estándar para los escenarios 1 y 2 es mayor en proporción a la media que para los escenarios 3 y 4 (Tabla 4). Este resultado sugiere que los escenarios más optimistas, a pesar de predecir NPV positivos, también tienen un mayor grado de incertidumbre asociada con su rentabilidad.

El estudio de la sensibilidad de los resultados a la tasa de descuento también brindó información importante (Fig. 3). Mientras que los escenarios 1 y 2 pudieron mantenerse positivos en promedio, incluso con tasas de descuento relativamente altas, los escenarios 3 y 4 pintan una situación grave para la pesquería: la pesquería no es rentable ni siquiera por un año. En una pesquería rentable, el descuento disminuye la magnitud de los beneficios positivos a largo plazo. Este es el patrón observado para los escenarios 1 y 2, donde el valor actual neto de la pesquería disminuye hacia cero a medida que aumenta la tasa de descuento. Cuando las actividades de pesca no pueden cubrir los costos de monitoreo y cumplimiento, el efecto se revierte. A medida que disminuye el descuento, la magnitud de cualquier pago o gasto a largo plazo, cada año las pérdidas de una pesquería no rentable se vuelven menos negativas, y los valores actuales negativos aumentarán hacia cero a medida que aumenta la tasa de descuento. Este es el caso de los escenarios 3 y 4. En otras palabras, en las estimaciones menos optimistas, la pesquería ni siquiera puede compensar la inversión inicial asociada con el monitoreo y los respectivos costos de cumplimiento.

# Discusión

Después de cuatro años de cierre, los esfuerzos de recuperación de NOS y la comunidad pesquera de El Manglito llevaron a un aumento general de la biomasa y la abundancia de las especies del callo de hacha en la Ensenada de La Paz. Los resultados de este estudio muestran que la biomasa aprovechable, basada en el escenario más conservador, mostró un crecimiento del 260 por ciento en una ventana de cuatro años. Este tipo de recuperación está sorprendentemente en línea con lo que se ha visto en otros esfuerzos de recuperación de vieiras, como la vieira del Atlántico (Placopecten magellanicus) [30]. No obstante, no hay datos disponibles antes del cierre de la cala de pesca, lo que hace imposible establecer dónde se encuentra la población estimada en comparación con la población antes del colapso. Como resultado de este esfuerzo, las autoridades mexicanas reabrieron la pesquería en octubre de 2017, permitiendo que se extrajeran 3,1 toneladas de callos de la cala en ese año, y 7 toneladas posteriores en 2018 [31]. Este nivel de producción solo podría alcanzarse con nuestras muestras (y, por lo tanto, con los escenarios) 1 y 2, aunque existe una alta incertidumbre.
La recuperación de la población no es necesariamente sorprendente. Si una pesquería se declara en moratoria, se espera que la población se recupere con el tiempo. Esta recuperación, sin embargo, es una función de cuán efectiva es la medida para detener la pesca. Lo que hace de este caso un valioso ejemplo para Los datos nos permiten visualizar algunas de estas dinámicas en juego. Por ejemplo, los años iniciales de bajos niveles de población podrían atribuirse a la persistencia de las actividades pesqueras. Después del cierre de la pesquería con escaso cumplimiento en 2008 [15,16], y debido a que todavía existía un mercado activo para el producto, el impulso del acceso abierto limitó el esfuerzo de recuperación. Cuando comenzó la participación de la comunidad, los pescadores se involucraron en las actividades de monitoreo y pudieron haber comenzado a desarrollar un sentido de valor para recuperar la pesquería. Con el paso del tiempo, este valor percibido se extendió a través de la comunidad, lo que aumentó el cumplimiento y convirtió la moratoria en efectiva.
Es posible que las condiciones biológicas y ambientales también contribuyan a este patrón. Por ejemplo, como estas vieiras tienden a agregarse, no fue hasta que se acumuló suficiente densidad que el reclutamiento no pudo aumentar [32]. A medida que este mecanismo se desarrolla a lo largo del tiempo y en el espacio, es solo cuando la cantidad suficiente de individuos se concentra en parches reducidos que la biomasa es capaz de despegar. Sin embargo, la efectividad de este proceso todavía depende de los pescadores Respetando la moratoria. Por lo tanto, se confirma nuestra intuición con respecto a la importancia de la participación de la comunidad en todo el proceso.
En este documento, hemos utilizado datos recopilados por la comunidad pesquera para documentar la efectividad del esfuerzo de recuperación, pero nuestro análisis no está exento de advertencias. Un tema importante a destacar es la amplia diferencia en las estimaciones de biomasa entre las muestras 1 y 2, y las muestras 3 y 4 (Tabla 2). Las muestras difieren en la inclusión de los 16 cuadrantes que presentaron alta abundancia. Cuando preguntamos a las partes interesadas directamente sobre estos lugares, los pescadores identificaron estos cuadrantes como áreas con parches de densidad históricamente alta donde el lecho marino presenta irregularidades. Estas irregularidades han sido reconocidas como mecanismos naturales para el hundimiento de las larvas y podrían explicar esas diferencias en la biomasa [33]. Una característica ambiental adicional del sistema es la división entre el flujo de entrada / salida del interior del Golfo de California, que crea un entorno heterogéneo para el recurso [33]. Es posible que la gran abundancia observada en las muestras 1 y 2 sea el resultado de una combinación entre estos procesos ambientales de macro y micro escala. Los esfuerzos futuros para un manejo adecuado de la cala y otras áreas donde se extrae el callo de hacha se beneficiarán de tener en cuenta estas dinámicas oceánicas.
Dado nuestro diseño de investigación, estas disparidades en la estimación de la biomasa impregnaron directamente los escenarios económicos. Según nuestro modelo, si el callo de hacha se cosechara y se manejara adecuadamente en el momento del presente estudio, solo sería rentable en los escenarios 1 y 2 (Fig. 2). Estimamos que la pesquería solo podría proporcionar empleo a 104 (Escenario 1) y 81 (Escenario 2) pescadores con un salario mínimo por temporada de pesca [34], respectivamente. Sin embargo, es importante tener en cuenta que estos niveles de ganancias reflejan una proporción fija de músculo individual (parte comestible), y las ganancias pueden aumentar si los pescadores atacan animales con músculos aductores más grandes. Las estrategias de gestión que tengan en cuenta las consideraciones económicas también se beneficiarían de tener en cuenta este supuesto.
Para los escenarios 3 y 4, que no consideran los cuadrantes de alta densidad, nuestros resultados sugieren que la pesquería podría no ser rentable. La razón principal de este resultado es la baja biomasa aprovechable que proporcionan estos escenarios y el alto costo fijo de hacer cumplir el área. Eliminar este costo hace que los escenarios 3 y 4 sean rentables con un VAN promedio de US $ 55 y 40 mil, respectivamente (Fig. S2). La alta sensibilidad de los resultados económicos es un resultado importante de este documento. La aplicación de actividades de pesca ilegal es responsabilidad del gobierno mexicano por ley [11]. Sin embargo, los problemas de gestión, la escasez de fondos públicos y la falta de infraestructura han reducido en gran medida la capacidad de las autoridades para llevar a cabo estos deberes [13,14]. A medida que la comunidad se ve obligada a realizar tareas de cumplimiento por su cuenta, el valor del recurso se reduce de manera efectiva y los incentivos para seguir prácticas de manejo sensatas comienzan a desaparecer. Es natural sugerir que esta línea de incentivos es lo que llevó a la pesquería a un colapso en primer lugar.
Reconocer esta realidad es crucial para el éxito de cualquier esfuerzo de recuperación. En el caso del callo de hacha, los fondos externos han ayudado a cubrir el esfuerzo de recuperación en la comunidad, pero el éxito a largo plazo depende en gran medida de mantener la rentabilidad de la actividad y los incentivos alineados en toda la comunidad. Si el stock recuperado de hecho cae en nuestros escenarios más pesimistas, ya sea la ejecución gubernamental adecuada o los fondos provistos externamente serán clave para mantener la participación de la comunidad en prácticas sostenibles. De lo contrario, el valor potencial de la pesquería comienza a disiparse y los pescadores perderán cualquier incentivo para mantener la población en niveles sostenibles. La autosuficiencia de estos esfuerzos de recuperación debe ser una de las discusiones más importantes cuando se trata del diseño y la implementación de planes de recuperación. Este requisito es especialmente cierto cuando se discuten los beneficios potenciales con los pescadores involucrados.

Sin embargo, tener una discusión abierta sobre los beneficios y costos asociados con la recuperación de una pesquería también requiere un buen conjunto de información sobre el cual construir esa discusión. Desafortunadamente, muchas de las pesquerías que se encuentran en problemas a menudo carecen de los datos requeridos asociados con este proceso [35]. Nuestro caso no es diferente. Si bien este análisis solo fue posible gracias a los datos recopilados por los propios pescadores, hay muchas cosas que pueden mejorarse. Los futuros esfuerzos de monitoreo en Ensenada y otras pesquerías similares se beneficiarán al reducir la variación dentro de los datos muestreados. Algunos enfoques incluyen métodos de estandarización y su mantenimiento a lo largo del tiempo. Los esfuerzos en la cala se dirigen en esa dirección. Los datos de desove empezaron a recopilarse en 2014, lo que permitirá una mejor evaluación de la dinámica de la población (por ejemplo, ¿la población se mantiene a sí misma ?; S1 Fig.). La mejora de estos aspectos reducirá la incertidumbre en la estimación de la biomasa y en cualquier análisis económico futuro.
El aumento de la biomasa en la cala y la rentabilidad potencial de la pesquería destacan varios componentes que pueden informar los futuros esfuerzos de recuperación en otras pesquerías de pequeña escala. Reducir la mortalidad por pesca a cero no siempre es sencillo. A menudo, los pescadores dependen en gran medida de la extracción y, siguiendo sus propias necesidades personales y válidas, finalmente se ven obligados a seguir pescando durante los cierres [21,36]. Para nuestro estudio de caso, hemos sugerido que invertir en la participación de la comunidad no solo fue fundamental para garantizar el cumplimiento, sino que también permitió el monitoreo del proceso de recuperación [22,37,38]. Además, el esfuerzo de más de cuatro años de planes de restauración también resultó en la Organización de Pescadores Rescatando la Ensenada. Al adoptar esta estructura cooperativa única, los pescadores pudieron solicitar una concesión exclusiva para el recurso, cambiando el estado de gestión del acceso abierto de facto a un sistema basado en el derecho de propiedad [12]. Esta transición crea incentivos para maximizar y mantener el valor del recurso, que se espera que fomente prácticas sostenibles a largo plazo.
Teniendo pruebas de la restauración biológica y la rentabilidad de la pesquería, las autoridades mexicanas reabrieron la pesquería en 2017 después de su propia evaluación. La organización de pescadores fue consignada con un total de 3,1 toneladas de callos asignados para ser cosechados en la cala [31]. Esta experiencia ha brindado muchos puntos de aprendizaje a los pescadores en Ensenada, incluyendo cómo cumplir con los cierres, cómo monitorear el estado del recurso y cómo organizar y asegurar los derechos de propiedad sobre un recurso. Más importante aún, estas experiencias también arrojan luz sobre posibles enfoques para otras comunidades artesanales en México y el resto del mundo.

# Conslusión

Después de más de cuatro años de gestión de la restauración, la comunidad de pescadores de El Manglito comenzó a cooperar y juntos lograron recuperar la pesquería del callo de hacha. La participación de la ONG Noroeste Sustentable con la comunidad apoyó no solo la recuperación del capital natural, sino que también creó un impulso para construir capital social y cultural. La combinación de estos factores ha permitido a la comunidad una nueva oportunidad para obtener beneficios del recurso de una manera sostenible. Si bien estos resultados son prometedores, todavía hay trabajo que se puede hacer en las etapas de muestreo y manejo para reducir la incertidumbre. Tomar en consideración la alta sensibilidad económica de esta pesquería a los costos de cumplimiento ayudará a la comunidad a aprovechar al máximo la pesquería recientemente reabierta. No hace falta decir que un incremento en la magnitud observada en esta pesquería es definitivamente un signo de mejora. La restauración de la población del callo de hacha en la Ensenada de La Paz resultó ser un ejemplo exitoso de restauración de la pesca basada en un enfoque bio-social que podría ser adoptado por comunidades pesqueras de pequeña escala similares en América Latina y el mundo.

# Agradecimientos
# Referencias



