---
title: 'Iron Profile of Octopus hubbsotum (Celphalopoda: Octopodidae) from the Pacific
  Ocean, Acaoulco, Guerrero, Mexico'
author: "Palacios-Abrantes J.*, Melo-Ruiz V., Diaz-Garcia R., Gazga-Urioste C. & Urbano B"
date: "2016"
output: pdf_document
---

[^*]:Traducción del texto original

- **NOTA: esta es una traducción al español del artículo** *Iron Profile of Octopus hubbsorum (Cephalopoda: Octopodidae) for Enrichment of the Mexican Diet* escrito por Juliano Palacios-Abrantes, Virginia Melo-Ruiz, Ricardo Diaz-Garcia, Carlos Gazga-Urioste y Brian Urbano y que se puede encontrar en el siguiente [link](http://www.davidpublisher.org/index.php/Home/Article/index?id=28446.html).

- **Forma de Citar**: Palacios-Abrantes J., Melo-Ruiz V., Diaz-Garcia R., Gazga-Urioste C. & Urbano B. (2016). Iron Profile of Octopus hubbsorum (Cephalopoda: Octopodidae) for Enrichment of the Mexican Diet, 10, 1–4. doi.org/10.17265/1934-7375/2016.05.008


# Introducción 
Los minerales son esenciales para los humanos y la falta de ellos está relacionada con muchas enfermedades degenerativas [1]. El hierro (Fe) es un mineral importante que debe incluirse en la dieta ya que está implicado en varias funciones [2], tales como: funciones químicas como el transporte de electrones, la regulación génica y la regulación del sistema inmune y del sistema nervioso central. También es un elemento esencial que actúa como un componente clave para las proteínas transportadoras de oxígeno; está involucrado en el crecimiento y la diferenciación celular y es un jugador vital en el metabolismo celular [2, 3]. Para un adulto, el contenido de hierro del cuerpo debe ser de 50 mg / kg [1] debido a su alta relación de almacenamiento, aproximadamente 1 a 2 mg se pierden del cuerpo por día [1, 4]. Con la excepción de las pérdidas causadas por la menstruación y el embarazo, las necesidades diarias son considerablemente bajas para los humanos [5]. Hierro
Autor correspondiente: Palacios Abrantes Juliano, maestro en ciencias, campo de la investigación: mariscos.
la anemia es la deficiencia nutricional más común en todo el mundo [6], pero no es la única enfermedad causada por la falta de este metal [2]. La deficiencia materna de hierro es la causa más común de deficiencia de hierro en el mundo [7], afecta del 30% al 50% de los embarazos en todo el mundo y si la ingesta es baja durante los primeros seis meses del embarazo, el aumento de la preparto Las actividades, el bajo peso al nacer e incluso la mortalidad materna neonatal tienden a aumentar [8].
Para los seres humanos, la absorción de hierro incluido en los alimentos de origen animal tiene una mayor tasa de absorción que la de las plantas vegetales comestibles [1]. Sin embargo, la mayoría de los mexicanos satisfacen sus necesidades de hierro a partir de vegetales (que tienen tasas de absorción pobres) y la población costera incluye a los peces escasamente en su dieta [9], lo cual es insuficiente para cubrir los requerimientos humanos de hierro hemo. Además, se ha mencionado que el consumo de fibra afecta la absorción de hierro, 12 g / día de salvado
en una comida disminuye la absorción de hierro en un 51% a 74%, lo cual es importante para la población mexicana cuya nutrición básica es rica en cereales [9, 10].
Los cefalópodos son uno de los recursos marinos más importantes a nivel mundial y México no es la excepción [11]. Durante 2010, se produjeron 169.500 toneladas de alimentos marinos (sin incluir peces), de los cuales 23.167 toneladas fueron pulpos, ocupando el décimo lugar entre las pesquerías de especies marinas de México y el cuarto lugar de las pesquerías de moluscos [12]. Debido a su importancia económica, Octopus maya en el Caribe y Octopus vulgaris en el Golfo de México son las principales poblaciones de la pesca [11, 13].
En el Océano Pacífico, las pesquerías se centran principalmente en O. hubbsorum, O. macrocopus y, por último, O. bimaculatus. Octopus hubbsorum B, es un cefalópodo endémico mexicano que solo se puede encontrar en el Océano Pacífico, desde el Golfo de California (norte) hasta la costa del mar del estado de Oaxaca (sur).
El objetivo de este estudio es investigar el contenido de hierro de tres organismos Octopus hubbsorum B de diferentes regiones de México y utilizar esta información para mejorar la salud, la nutrición, la seguridad alimentaria y la sostenibilidad ecológica de las personas.
2. Materiales y métodos
2.1 Colección de muestras
El proceso de muestra se logró durante agosto de 2013. Octopus hubbsorum B se obtuvo de un pescador de dos localizaciones diferentes; Bahía de Acapulco en el estado de Guerrero (16 ° 51 '0' 'S, 99 ° 55' 0 '' O) y Los Cabos San José en el estado de Baja California (16 ° 51 '0' 'S, 99 ° 55' 0 '' W), ambos ubicados en el Océano Pacífico. Las muestras se identificaron taxonómicamente in situ [14] y se introdujeron inmediatamente en un recipiente de plástico a -4 ° C para el transporte terrestre a la Ciudad de México.
2.2 Configuración experimental
Se cortaron los tentáculos del "manto", se seleccionó aleatoriamente un tentáculo de cada animal y se depositó en alcohol al 70% para análisis molecular adicional y registro
identificación, el resto se cortó en partes cúbicas de 4 cm y luego se utilizó para determinar el contenido de humedad mediante el método de secado directo. El material de pulpo se secó durante 24 h en un horno de aire ajustado a 60 ° C hasta que se obtuvo el peso constante de la muestra; El producto se molió y pasó a través de un tamiz de malla 60 para homogeneizar la muestra. La cantidad de ceniza se determinó mediante el método de ceniza seca. Las muestras se incineraron en un horno de mufla fria a 650 ° C durante 2 horas o hasta que se obtuvo ceniza blanquecina / grisácea. La materia orgánica se quemó y el material inorgánico restante se usó para la determinación de hierro disolviendo cenizas en 100 ml de ácido clorhídrico 1 N y la cuantificación del hierro se realizó mediante espectrofotometría de absorción atómica. Todas las muestras se realizaron por triplicado.
3. Resultados y discusión
3.1 Resultados
Los pulpos estudiados están ampliamente distribuidos en la zona costera del Océano Pacífico (Fig. 1).
El pulpo se puede encontrar durante todo el año; sin embargo, existe un período de cierre entre agosto y octubre, por lo que la temporada principal de pesca es entre abril y julio (Tabla 1).
X = Meses del año en que se puede producir el recurso del pulpo.
X = Meses del año en que la producción es considerablemente mayor.

he studied specie was Octopus hubbsorum B, an endemic Mexican cephalopod (Table 2).
Laboratory results showed that Acapulco’s Octopus hubbsorum has a very high moisture rate, being this twice as much as the moisture found in the samples collected at Los Cabos (Table 3).
The total amount of inorganic matter determined by the dry ashing method was 7.78%. Regarding iron content (Table 4), the analysis by atomic spectrophotometry showed that the amount of iron found in samples from Acapulco and from the south area of Los Cabos are pretty similar due to the similarities of these regions’ environments. The environment at the north area of Los Cabos is slightly different, which explains the variation of iron content depending on the characteristics of the zone where octopuses live.
Iron deficiency anemia is still a major nutritional problem in vulnerable population worldwide because it can lead to negative changes in psychomotor and
Table 2 Taxonomic determination.
Table 5 Iron dietary requirements in humans. RDA (recommended daily allowance). Data from Food and Nutrition Board institute of Medicine, 2001.
 Age
50 + years 50 + years
Gender mg/day Adult men 6 Adult women 8.1
    Taxonomic category Kingdom
Phylum
Class
Subclass Superorder Order SubOrder Family Genus Species
Animalia
Mollusca
Cephalopoda
Coleoidea
Octobranchia
Octopoda
Incirrina
Octopodidae
Octopus
Octopus hubbsorum Berry, 1953
mental development, which may be irreversible due to the vital functions of this mineral on the body. The amount of iron in octopus samples represents a good source of this essential element that could be of great help to cover the requirements for human daily diet (Table 5). In this context, octopus consumption may be considered as an option for the improvement of human health, due to the important functions that iron plays within the body’s metabolism and other important processes.
In addition to the aforementioned, octopus provide heme iron that is readily absorbed (about 30%), in contrast to the non-heme iron found in vegetable sources whose absorption is pretty low (about 5% if it is consumed with vitamin C). However, the absorption is influenced by iron storage as ferritin, by the dietary content, and by iron bioavailability on the daily diet [15].
4. Conclusions
The iron provided by Octopus hubbsorum, B to human nutrition is vital, therefore is recommended to consume more of this resource to diminish iron deficiency, a world-wide problem, and to improve human health and well-being.

References
[1] Reilly, C. 2006. The Nutritional Trace Metals. Oxford: Blackwell Publishing. 35-70.
[2] Beard, J. 2006. “Iron.” In Present Knowledge in Nutrition, 9th ed, edited by Bowman, B., & Russell, R. Washington DC: International Life Sciences Institute, 430-44.
[3] Nemeth, E., and Ganz, T. 2006. “Regulation of Iron Metabolism by Hepcidin.” Annu. Rev. Nutr. 26: 323-42.
[4] Hunt, J. R., Zito, C. A., and Johnson, L. 2009. “Body Iron Excretion by Healthy Men and Women.” Am J Clin Nutr 89 (6): 1792-8
[5] Ray, Yip. 2003. Hierro. In Barbara Bowman & Robert Russell Ed. Conocimientos Actuals Sobre Nutrición. Organización Panamericana de la Salud. Washington, DC. 340-59.
[6] Martínez-Salgado, H., Casanueva, E., Rivera-Dommarco, J., Viteri, J., and Bourgues-Rodríguez, H. 2008. “La Deficiencia de Hierro y la Anemia en Niños Mexicanos. Acciones Para Prevenirlas y Corregirlas.” Bol. Med. Hosp. Infant. Mex. 65: 86-99.
[7] WHO (World Helath Organization). 2008. “Micronutrient Deficiences.” http://www.who.int/nutrition/topics/ida/en/.
[8] Khan, L., Wojdya, D., Say, I., Gulmezoglu, A. M., and
Van Look P. F. 2006. “WHO Analysis of Causes of Maternal Death: A Systematic Review.” Lancet. 367: 1066-74.
[9] Martínez, I., and Villezca, P. 2003. “La Alimentación en México: un Estudio a Partir de la Encuesta Nacional de Ingresos y Gastos de los Hogares.” Rev. Info, y Anal. 21: 26-37.
[10] Vieteri, F. E., and Torum, B. 1974. “Anemia and Physical Work Capacity.” Clin Hematol. 3: 609-26.
[11] Alejo-Plata, C. R., Gómez-Márquez, J. L., Ramos, S., and Herrera-Galindo, J. E. 2009. “Reproducción, Dieta y Pesquería Del Pulpo Octopus (Octopus) Hubssorum (Mollusca:Cephalopoda) en la Costa de OAXACA.” Revista Biología Tropical 57(1-2): 63-78.
[12] SAGARPA. 2004. Anuario Estadístico de Pesca. Secretaría de Agricultura, Ganadería, Desarrollo Rural, Pesca y Alimentación. México, D.F. 266.
[13] Arreguín-Sánchez, F., Solís-Ramírez, M., and Gonsales de la Rosa, M. 2000. “Population Dynamics and Stock Assessment of Octopus Maya (Cephalopoda: Octopodidae) Fishery in the Campeche Bank, Gulf of México.” Rev. Biol. Trop. 48(2-3): 323-31.
[14] Roper, C. L., Sweeney, M. J., and Nauen, C. E. 1984. Species Catalog. Vol 3. Cephalopods of the World. An Annotated and Illustrated Catalogue of Species of Interest to Fisheries. FAO Fisheries Synopsis.
[15] FAO/WHO (Food and Agricultural Organization of the United Nations/World Health Organization). 2004. Vitamin and Mineral Requirements in Human Nutrition. Geneva, Switzerland.

<!-- Global site tag (gtag.js) - Google Analytics -->
<head>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-105699898-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-105699898-3');
</script>
</head>