---
title: "Análisis nutricional de *Octopus hubbsorum B* (Cephalopoda: Octopodidae) del Océano Pacífico, Acapulco, Guerrero, México"
author: "Palacios-Abrantes*, V. Melo-Ruiz, B. Urbano, N. Vargas-Martínez, J. J. Falcón-Gerónimo y C. Gazga-Urioste"
date: "2017"
output: html_document
---

- **NOTA: esta es una traducción al español del artículo** *Nutritional Analysis of Octopus hubbsorum B (Cephalopoda: Octopodidae) from the Pacific Ocean, Acapulco, Guerrero, México* escrito por Juliano Palacios-Abrantes, Virginia Melo-Ruiz, Brian Urbano, Jimena Falcón-Gerónimo J. y César Gazga-Urioste y que se puede encontrar en el siguiente [^link](http://doi.org/10.9734/JALSI/2017/31031).

- **Forma de Citar**: **Palacios-Abrantes J.**, Melo-Ruiz V., Urbano B., Falcón-Gerónimo J. & Gazga-Urioste C. (2017). Nutritional Analysis of Octopus hubbsorum B (Cephalopoda: Octopodidae) from the Pacific Ocean, Acapulco, Guerrero, México. Journal of Applied Life Sciences International, 10(3), 1–6.

------------------------

# 1. INTRODUCCIÓN

México es un país con problemas relacionados con la nutrición, principalmente en relación con el déficit de proteínas y energía y el bajo consumo de minerales y vitaminas. Esto ha contribuido a que México ocupe el segundo lugar en obesidad adulta dentro de los países de la OCDE (30% de la población) [1]. La mayoría de las veces, este déficit se abastece con un alto consumo de carbohidratos, que las calorías de baja calidad dan como resultado la malnutrición y otros problemas de salud [2]. Esto también genera dificultades durante las primeras etapas de crecimiento y tiene un impacto importante en la sociedad [3,4]. 

El pulpo ha demostrado ser una buena fuente de nutrientes [5]. México, con una línea costera de 11,200 km [6], ha explotado al pulpo desde 1980 [7]. La pesquería ha tenido una expansión progresiva, convirtiéndose en la cuarta pesquería más rentable del país. En el litoral mexicano, existen muchos cefalópodos, pero solo unos pocos octópodos se usan para el consumo humano. Según las autoridades mexicanas, solo se pescan cuatro especies de octopodos, aunque hay 15 de estos organismos de la zona bentónica que pueden utilizarse para muchos fines [8-11]. La principal pesquería de pulpo en México pertenece a la especie caribeña O. maya seguida del Pacífico *O. vulgaris* [12]. La riqueza de los octopodos del Pacífico mexicano está comprendida entre seis y nueve especies, de las cuales se pescan dos especies principales: *O. bimaculatus* y *O. hubbsorum B* [11]. Sin embargo, también es común capturar *O. macropus* [13]. *O. hubbsorum B* representa la principal pesquería de pulpo en la costa del Pacífico mexicano [14], aunque muchas veces es una pesquería de subsistencia. La pesquería se realiza por inmersión entre 0-10 metros de profundidad y los especímenes se capturan manualmente [13]. La temporada de pesca es de marzo a octubre, pero varía a nivel local, presentando una mayor actividad pesquera de abril a mayo [12]. *O. hubbsorum B* se describió primero en el área sur del Golfo de California. Se distribuye desde Los Cabos en el estado de Baja California Sur hasta el estado de Nayarit [9]. Recientemente se informó en Salina Cruz, dentro del Estado de Oaxaca [15]. Sin embargo, hay muchas razones para creer que también podría estar en Chiapas o más al sur [16]. Es una especie semelparous, con un tamaño promedio de 9 cm de longitud del manto; su cuerpo está redondeado con brazos fuertes que pueden ser de tres a cuatro veces más grandes que la cabeza [9]. La temporada reproductiva varía localmente, generalmente asociada a aguas cálidas [16].

La mayoría de los estudios están dirigidos a comprender la biología y la pesca de estos organismos [12, 13]. Sin embargo, no hay estudios que se enfoquen en *O. hubbsorum B* como fuente de proteína y como una alternativa para la dieta de la población mexicana. Por lo tanto, el objetivo de este estudio es establecer los valores micro y macronutrientes de *O. hubbsorum B* y evaluar su contribución potencial a la dieta mexicana.

# 2. MATERIALES Y MÉTODOS
## 2.1 Colección de muestras

Cinco especímenes de *O. hubbsorum B* se obtuvieron inmediatamente después de la captura en noviembre (2016) del pescador local de Acapulco, estado de Guerrero, México. Los organismos fueron identificados utilizando literatura estándar [8] y transportados por tierra sobre hielo a -2ºC al laboratorio de bromatología de la Universidad Autónoma Metropolitana (Xochimilco), Ciudad de México, donde se mantuvieron refrigerados hasta la preparación de la muestra.

## 2.2 Preparación de la muestra

Los ocho tentáculos de cada espécimen fueron cortados del manto y cortados en cuadrados de aproximadamente 4 cm (400 g) para realizar el análisis proximal para la cuantificación química de macronutrientes y micronutrientes.

## 2.3 Contenido de humedad

El contenido de humedad de la muestra se determinó usando el método de secado directo. Una muestra homogeneizada (400 g) se secó en un horno a 60 ° C durante 36 h. La muestra se trituró en un *Willey Mill* y luego se pasó a través de una malla 60. El polvo fino obtenido se utilizó para un análisis posterior [17].

## 2.4 Contenido de proteína

El contenido de proteína de la muestra se determinó de acuerdo con el método de *Kjeldahl*  [18]. La muestra (1 g) se digirió con 15 ml de H2SO4 concentrado, usando un digestor de bloques de aluminio calentado eléctricamente. El digesto resultante se diluyó y luego se alcalinizó con 50 ml de NaOH al 40%. Esto fue seguido por la destilación rápida de vapor de amoniaco del digesto diluido en 25 ml de ácido bórico al 4% para la titulación manual con HCl 0,2N. Se usó un factor de conversión de 6,25 para convertir el contenido de nitrógeno medido en contenido de proteína. Todas las muestras se analizaron por triplicado y los resultados se expresaron como g / 100 g de base seca de la muestra [19,20] .2.5 Contenido de lípidos La determinación del contenido de lípidos se llevó a cabo mediante el método de extracción semicontinua con disolventes de la siguiente manera: La muestra (10 g) extraído con 180 ml de éter de petróleo en un aparato Soxhlet (Sigma-Aldrich, México, México) durante 10 h. El éter de petróleo se eliminó por evaporación y el residuo de lípido se pesó. Todas las muestras se analizaron por triplicado y los resultados se expresaron como g / 100 g de base seca de la muestra [17] .2.6 Contenido de fibra La determinación de la fibra bruta en la muestra (10 g) se realizó mediante digestión con hidrólisis ácida con H2SO4 0.255 N seguido de alcalina digestión de hidrólisis con NaOH 0.313 N en un aparato Labconco (corporación Labconco, ciudad de Kansas, Mo. USA). El residuo insoluble se recogió por filtración, se secó y se pesó. La muestra se analizó por triplicado y los resultados se expresaron como g / 100 g de base seca [17] .2.7 Contenido de Minerales El contenido de Ash se determinó usando un método de cenizas en seco. La muestra (10 g) se incineró en un horno de mufla frío ajustado a 600 ° C durante 8 horas hasta que se obtuvo una ceniza blanquecina / grisácea. La materia orgánica se quemó y el material inorgánico remanente se enfrió y se pesó. La solución de ceniza para la determinación de la composición mineral se preparó disolviendo la ceniza resultante en 100 ml de HCl1N [21]. 50 ml para la determinación del contenido de calcio y hierro por espectroscopía de absorción atómica [22]. Todas las muestras se analizaron por triplicado. Los resultados se expresan en mg / 100 g de muestra para contenido de ceniza y mg / 100 g de muestra para cada elemento mineral. El fósforo se determinó por colorimetría [23] .2.8 Contenido de carbohidratos disponible total La cantidad de carbohidratos se determinó por diferencia de acuerdo con la ecuación 1.% de carbohidratos = 100% - [(proteína%) + (lípidos%) + (minerales%) + (fibra %)] (1) 3. RESULTADOS Y DISCUSIÓN3.1 Contenido de humedad El análisis de humedad mostró que O. hubbsorum B tiene 64.15% de agua, siendo 35.85% de materia seca (Tabla 1). En comparación con otros estudios realizados por Cabello et al.; [5] y Valenzuela et al., [24] sobre diferentes especies de moluscos, O. hubbsorum B contiene menos humedad que cualquier molusco analizado por estos autores cuyos resultados mostraron que O. Vulgaris contiene 79.65% de agua. Esto significa que la cantidad de nutrientes contenidos en O. hubbsorum B es mayor por unidad de peso que la que podría encontrarse en otras especies, lo que representa una ventaja ya que sería posible obtener niveles más altos de nutrientes con porciones de alimentos más pequeñas. 3.2 Contenido de proteína El contenido de proteína fue 69.38% (Tabla 1), por lo que O.hubbsorum B puede considerarse una buena fuente de proteínas en comparación con otras especies como O. vulgaris del Pacífico colombiano o diferentes moluscos estudiados previamente para otros autores [5,24]. Esto sugiere, no solo el alto valor nutricional de esta especie, sino también una gran diferencia dentro de las especies de pulpo [5]. Esto ha sido estudiado previamente, donde los hallazgos tienenPalacios-Abrantes et al .; JALSI, 10 (3): 1-6, 2017; El artículo nº JALSI.310313 mostró que los valores nutricionales de los animales tienden a cambiar según variables como el hábitat, la estación, el sexo y la dieta [5,25-27]. Además de lo anterior, O. hubbsorum B tiene más proteína que la carne de vaca o pollo [28,29]. Por lo tanto, como parte de la dieta, O. hubbsorum B representa un alimento altamente nutritivo que podría ayudar a disminuir la incidencia y la prevalencia de desnutrición proteicocalórica.3.3 Contenido de lípidos Como se puede ver en la Tabla 1, el contenido de lípidos es bajo (2.77%) . Sin embargo, O. hubbsorum B tiene el doble de lípidos en comparación con los datos obtenidos por Cabello et al. [5] para O. vulgaris. Por otro lado, según otros autores, la carne de vaca y el pollo contienen 5 y 7,75% de lípidos, respectivamente. Es importante recordar que ningún alimento tiene todos los nutrientes necesarios para una dieta sana y equilibrada. Sin embargo, los resultados obtenidos demuestran que O. hubbsorum B podría considerarse una alternativa para proporcionar una dieta adecuada y variada con el fin de mejorar y mantener la salud.3.4 Contenido de fibrahubbsorum B es bajo (1,4 mg / 100 g), este animal podría ser una buena fuente para este mineral.Tabla 1. Análisis proximal de O.hubbsorum B. De acuerdo con elO.hubbsorum B no tiene fibra, por lo que sería necesario suministrar fibra de otra fuente. Esto es importante debido a los valiosos beneficios que este componente puede proporcionar. En este contexto, los estudios epidemiológicos sugieren que el riesgo de contraer cáncer de colon disminuye por el consumo de fibra y, por lo tanto, entre 20 y 30 g por persona.
día de fibra se recomiendan. Además; algunas fuentes de fibra absorben los ácidos biliares, el principal metabolito del colesterol, por lo que el consumo de fibra puede ser útil para disminuir los niveles de colesterol en la sangre. Además, otros estudios demostraron que el consumo de fibra puede ser un medio eficaz para reducir la presión arterial y disminuir los riesgos de enfermedad coronaria [30,31] .3.5 Contenido de minerales En la Tabla 2, se puede observar que el contenido de minerales como ya que el hierro es más bajo que el requerido para humanos (6-8 mg / día). Sin embargo, aunque el hierro es un mineral importante para el desarrollo del cuerpo humano y la prevención de la anemia [32], no es necesario consumirlo en grandes cantidades [33,34] porque está muy almacenado en el cuerpo humano. Por lo tanto, incluso el valor de hierro reportado para O. * Los valores son la media de la determinación por triplicado expresada en base seca.Proteína = Nitrógeno (tot) x 6.25E aunque la cantidad de hierro encontrada es baja, los resultados mostraron niveles adecuados de minerales para los humanos en comparación con otros grupos de moluscos [5,24]. Por otro lado, la cantidad de calcio en O. hubbsorum B es suficiente para satisfacer las necesidades de la dieta humana (1,2 mg / día), que es de gran importancia debido a las valiosas funciones de este mineral, como su participación como primer y segundo mensajero, que está relacionado con muchos procesos importantes como la regulación del calcio intracelular y la activación de muchas respuestas fisiológicas que implican la contracción muscular, la liberación de hormonas y neurotransmisores, el metabolismo del glucógeno y la diferenciación celular. También activa diferentes enzimas como proteasas y deshidrogenasas [35]. Finalmente, la cantidad de fósforo en O. hubbsorum B no será suficiente para satisfacer los requerimientos humanos (580 mg / día) [36]. Sin embargo, como se mencionó anteriormente, no hay alimentos capaces de proporcionar todos los nutrientes e incluso menos en las proporciones adecuadas. Por lo tanto, es necesario agregar algunas otras fuentes para obtener el fósforo necesario. En este contexto, la dieta mexicana incluye frijoles, un alimento con alto contenido de fósforo [4] que podría ayudar a superar la falta de éste en O. hubbsorum B. Tabla 2. Contenido de minerales de O. pubsorum B. Contenido mineral (mg / 100 g) Ca 24.33 ± 3.06 Fe 1.40 ± 0.26P 120.67 ± 1.153.6 Contenido total disponible de carbohidratos. La cantidad total de carbohidratos solubles encontrados es de 20. 53 g / 100 g, sin embargo, debido al alto análisis realizado, Palacios-Abrantes et al.; JALSI, 10 (3): 1-6, 2017; Artículo n. JALSI.31031 NutrientMoistureDry materia Protein * Materia inorgánica * Fibra * Lípidos * Hidratos de carbono solubles * Contenido (g / 100g) 64.1535.8569.38 ± 0.97 7.32 ± 0.68 0 ± 0.02.77 ± 0.24 20.53 ± 1.39 4 cantidad de proteína encontrada (69.38 g / 100 g); El exceso de proteínas podría transformarse por gluconeogénesis en carbohidratos que actuarán como fuente de energía. Por lo tanto, las fuentes de energía inmediatas como los carbohidratos podrían obtenerse a través de procesos metabólicos. CONCLUSIÓN El pulpo hubbsorum B puede considerarse una fuente bastante buena de proteínas. Esto podría ser útil para disminuir la desnutrición proteicocalórica de las personas que viven en las zonas costeras. Sin embargo, a pesar de su riqueza nutricional, el pulpo debe consumirse junto con otras fuentes nutricionales para obtener una dieta balanceada. DECLARACIÓN ÉTNICA Los autores han obtenido la aprobación ética necesaria de un comité institucional o estatal o nacional o internacional adecuado. INTERPRETACIÓN DE INTERESES Los autores han declarado que no hay intereses en conflicto existe.



<!-- Global site tag (gtag.js) - Google Analytics -->
<head>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-105699898-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-105699898-3');
</script>
</head>