---
title: "Participation in Conferences"
---

## Conferencias Académicas

- Projected consequences of climate change to commercially important species in the Marine Corridor of the Eastern Tropical Pacific (CMAR). One Ocean Science Conference, Nice France (2025)

- The role of the Interdisciplinary Marine Early Career Network (IMECaN) in supporting capacity building, ocean literacy, and collaborative leadership of early career researchers. Xiamen Symposium on Marine Environmental Sciences, Xiamen, China (2025)

- Efectos del cambio climático en los stocks y el manejo regional de peces transfronterizos de América del sur. Simposio Argentino de Ictiología, Ushuaia, Argentina (2024)

- Fostering climate-resilient biodiversity and fisheries in the eastern tropical Pacific marine protected areas. International Marine Conservation Conference, Cape Town, South Africa (2024)

- Addressing shifts in the distribution of internationally shared marine fish stocks for achieving a sustainable deep-sea blue economy. International Marine Conservation Conference, Cape Town, South Africa (2024)

- Fomentando biodiversidad y pesca resilientes al clima en el pacífico este tropical, Congreso de Integració de Saberes para un Océano Sostenible, San José, Costa Rica (2024)

- Quantifying fish range shifts across poorly defined management boundaries. World Fisheries Congress, Seattle, WA, USA (2024) 

- Transboundary fish stocks challenges under climate change. Species on The Move Conference, Florida, US (2023)

- Marine Protected Areas Can Reduce Regional Losses to Fisheries Under Climate Change. ECCWO5 conference, Bergen Norway (2023)

- Timing and magnitude of climate-driven range shifts in transboundary fish stocks challenge their management. ICES/PICES Early Career Conference, St. John's NL, Canada (2022)

- Climate change and transboundary fisheries management, examples from North America. Species on the Move, Skukuza, South Africa (2019)

- Challenges to Transboundary Fisheries Management in North America Under Climate Change. IMBeR Future Oceans 2, Brest, France (2019)

- Current State and Future Scenarios for Transboundary Fisheries Management in Changing Oceans of Canada and the United States. The Effects of Climate Change of the World's Oceans, Washington D.C., USA (2018)

- Current State and Future Scenarios for Transboundary Fisheries Management in Changing Oceans: Gauging the Biological Tides. MARE Conference 2017 People and the Sea IX: Dealing with Maritime Mobilities, Amsterdam, Netherlands (2017)

- Towards the creation of a metadata of marine research in Mexico: a case study of the Gulf of Mexico. State of the Gulf of Mexico, Houston, Texas (2017)

- A Citizen Science Monitoring Protocol for the Rocky Intertidal Habitat. Multi-Agency Rocky Intertidal Network Annual Meeting, Cabrillo National Monument, San Diego, California (2016)

- Análisis proximal de *Octopus hubbsorum* (Cephalopoda: Octopodidae) en Acapulco Guerrero (México). Congreso de la sociedad Mesoamericana para la Biología y la Conservación, Panama City, Panama (2012)

- Análisis nutricional de callo de hacha *Atrina sp*. (Mollusca: Pinnidae) en México". Congreso de la Sociedad Mesoamericana para la Biología y la Conservación, Panama City, Panama (2012)

- Estrella de mar, un rico complemento alimenticio para comunidades costeras de bajos recursos. XV Congreso de la sociedad Mesoamericana para la Biología y la Conservación, Mérida, Mexico (2011)

- Ración de Malacosoma azteca para animales como estrategia de control de plaga en Xochimilco. XV Congreso de la sociedad Mesoamericana para la Biología y la Conservación, Mérida, México (2011)

- Influencia de factores abióticos en fase larval del Malacosoma azteca. 44o congreso Mexicano de Química. Puebla, México (2009)

- Sea cucumber, underutilized source of macronutrients. $8^o$ Simpósio Latino Americano de Ciência de Alimentos. Campinas, Brasil (2009)

## Talleres

- C2-BioME: Climate change & Biodiversity in Marine Ecosystems (2025). Workshop organized by Conservation International. Quadra, Canada. [*Fully funded by organizers*]

- Adapting Maritimes Fisheries to a Changing Climate (2024). Workshop organized by Fisheries and Oceans Canada (DFO) [*Webinar*]

- Adapting British Columbia’s Fisheries to a Changing Climate (2024). Workshop organized by Fisheries and Oceans Canada (DFO) [*Webinar*]

- C2-BioME: Climate change & Biodiversity in Marine Ecosystems (2023). Workshop organized by Conservation International. Boston, US. [*Fully funded by organizers*]

- Deep-sea blue-economy workshop (2023). Workshop Organized by the National Geographic Society and in partnership with SpeSeas, the Nippon Foundation-University of Edinburgh Ocean Voices Programme, the Benioff Ocean Science Laboratory, and the Deep-Ocean Stewardship Initiative. Saint Vincent and the Grenadines [*Invited speaker*]

  - *Climate change effects on deep-sea blue-economy*

- Workshop A global ensemble of comparable marine ecosystem models to project climate risk to species and human communities (2023). Part of the Effects of Climate Change on the World's Oceans meeting (ECCWO) in bergen, Norway. [*Invited speaker*] 

  - *Using modelling to inform transboundary fisheries management under climate change*. 

- New Species Distributions Under Climate Change (2023). Workshop Organized by Environmental Defense Fund and Lenfest Ocean Program. Seattle, WA, USA [*Fully funded by organizers*]

- FishMIP workshop on climate change modelling groups (2023). Organized by NOAA's National Ecosystem Modeling Workshop (NEMoW) and FishMIP. Honolulu, HI, USA [*Fully funded by organizers*]

- Workshop on climate change impacts on sustainable seafood (2022). Workshop organized by Marine Stewardship Council (MSC) and the United Nations Food and Agricultural organization (FAO). Rome, Italy. [*Co-funded by FAO and MSC*]

- Global-scale scientific and technical workshop to review and assess EBSAs in ABN (2022). Workshop organized by the Global Ocean Initiative Programe (GOBI). Santa Cruz, California. [*Fully funded by organizers*]

- FishMIP 2022 Hybrid Workshop (2022). Workshop to discuss FishMIP-related projects in St. John's Canada. [*Fully funded by organizers*]

- Finding solutions in the tropics: Tropical ocean science for people, biodiversity, and climate resilience (2022). Organized by Smithsonian Tropical Research institute and Oregon State University. Webinar.

- Canada's Blue Economy Symposium (2022). Organized by NEXUS program and Memorial University of Newfoundland. St. John's, Canada. [*Fully funded by organizers*]

- High Seas Nature Futures Framework (NFF) workshop (2021). Organized by the Stockholm Resilience Centre, Stockholm University. Cape Town, South Africa. [*Fully funded by organizers*]

- Future High Seas Governance Workshop (2018). Organized by the University of British Columbia (UBC) and the International Institute for Environment and Development (IIED). Vancouver, British
Columbia, Canada. [*Fully funded by organizers*]

- IMBeR ClimEco6 Summer School - Interdisciplinary approaches for sustainable oceans (August, 2018). Organized by the Integrated Marine Biosphere Research (IMBER). Yogyakarta, Indonesia. [*Fully funded by SCOR/PICES*]

- Graduate Student Workshop on Socio-Environmental Synthesis (2018). Organized by the National Socio-Environmental Synthesis Center (SESYNC). Annapolis, Maryland, United States. [*Fully funded by organizers*]

- UK-Mexico Researcher Links Workshop, Present Status and Horizon Scanning of Sustainable Aquatic Resource Development in Mexico (2017). Organized by the Instituto Tecnologico Superior de Felipe Carillo Puerto, British Council, CONACyT and Researcher links. Felipe Carrillo Puerto, Quintana Roo, Mexico. [*Fully funded by organizers*]

## Sesiones Organizadas

-  Managing Fisheries in a World of Shifting Stocks: Integrating Biological, Policy, Behavioural, Social and Economic Aspects (2024). Session on the World Fisheries Congress, Seattle, US. [*Co-organized*]

- Fostering Diversity, Equity and Inclusion (DEI) into interdisciplinary marine research (2022). Workshop aimed to gather inputs for a scientific manuscript on the challenges and opportunities for progressing DEI in interdisciplinary marine sciences. Organized by the Interdisciplinary Marine Early Career Network (IMECaN). [*Co-organized*]

- IPBES Future Nature Scenarios Workshop (2019). Part of the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES) scenario task force. Organized at the Species on the Move conference, Skukuza, South Africa. [*Co-organized*]

- IPBES Future Nature Scenarios Workshop (2019). Organized by the University of British Columbia (UBC) and the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES); Vancouver, British Columbia, Canada. [*Co-organized*]

## Reuniónes de Políticas

- Multiple workshops (n = 4) with park managers on the impacts of climate change on the Marine Corridor of the Eastern Tropical Pacific (CMAR). Organized by *Fundación MarViva*, San José, Costa Rica; Panamá City, Panamá; Cali, Colombia; Galápagos, Ecuador (2025) [*Co-organized*]

- 62nd sessions of the UNFCCC Subsidiary Body for Implementation (SBI) and Subsidiary Body for Scientific and Technological Advice (SBSTA), SB62. Bonn, Germany (2025) [*Participation*]

- UN Ocean Conference, Nice, France (2025) [*Participation*]

- Preparatory Meeting for the 2025 UN Ocean Conference, San José, Costa Rica (2024) [*Participation*]