---
title: "Community Service"
---

## Participación en Comités Scientíficos

- Great Bear Sea MPA Network (2025-2027). Rol: *Miembro del Comité Asesor de Conocimiento*. Más información disponible en: https://www.greatbearsea.ca/
	•	Fresh Eyes on CMIP, Subgrupo de Acceso a Datos (2023-2025). Rol: *Miembro del Comité*. Más información disponible en: https://wcrp-cmip.org/fresh-eyes-on-cmip/
	•	Interdisciplinary Marine Early Career Network (IMECaN) (2024-2027). Rol: *Coprensidencia del Comité Directivo*. Más información disponible en: https://imber.info/imecan-interdisciplinary-marine-early-career-network/
	•	Conferencia Species on the Move (SOTM), Comité Directivo (2022-2022). Rol: *Miembro del Comité Directivo*. Más información en: https://pwd.aa.ufl.edu/sotm/2023-conference/committee/

## Comités no científicos
	-	Miembro del Comité de Equidad, Diversidad e Inclusión (EDI) del Center for Limnology de la Universidad de Wisconsin (2021-2022).
	-	Miembro del Comité de Buceo SCUBA del Center for Limnology de la Universidad de Wisconsin (2021-2022).
	-	Fundadora y miembro del comité directivo del Mozilla Science Lab Study Group Deep Sea Data Squad del Institute for the Oceans and Fisheries (2017-2021). Este grupo se reunía semanalmente para sesiones de trabajo colaborativo en R, con el objetivo de mejorar las habilidades de programación y crear una comunidad de codificación solidaria.
	•	Miembro del comité directivo de Equidad, Diversidad e Inclusión (EDI) de la Student Society of the Institute for the Oceans and Fisheries (2018-2020). El comité trabajó en la creación de recursos que brindan información sobre políticas, iniciativas y apoyos relacionados con EDI dentro del IOF y en toda la UBC.

## Redes Profesionales
	-	Leaders for Sea Change Fellowship (COMPASS). Rol: Becaria. Más información disponible en: https://www.compassscicomm.org/wp-content/uploads/2020/07/Leaders-for-Sea-Change-Cohort-2020.pdf
	-	Voceros del Cambio Climático (EDF-México). Rol: Miembro.

## Peer Review

- Ecography, 2023
- Ecosystems and People, 2020
- FACETS, 2022, 2023
- Fish and Fisheries, 2020
- Frontiers of Marine Science, 2021
- Global Change Biology, 2022
- Helion, 2023
- ICES, 2024
- Marine Policy, 2018, 2023
- NPJ Sustainability, 2023
- Proceedings of the National Academy of Sciences of the United States of America (PNAS), 2024
- Revista de Biología Marina y Ocenaografia, 2021 
- Regional Environmental Change, 2022
- Reviews in Fish Biology and Fisheries, 2020
- Science Advances, 2022