---
title: "Annex Teaching Experience and Mentoring"
---

##  Projects funded

- Funding to work on marine extremes impacts to blue food security (2024). Project funded by the *Walton Family Foundation* in partnership with the *World Wildlife Fund* [CAD $94,000].

- The potential for transboundary marine protected areas to build climate-resilience for biodiversity conservation and fisheries sustainability in the Eastern Tropical Pacific Ocean (2023-2025). Project funded by *Lenfest Ocean Program*. Role: *Co-applicant* [CAD $528,500]

- Projecting the impacts of changing species biogeography on Marine Protected Areas in the Canadian Arctic (2022-2025). Project funded by DFO. Role: *Co-applicant* [CAD $273,000]

- Sistema de Información satelital como soporte a la producción pesquera argentina (2022-2023). Project funded by the *International Development Bank (IDB)*. Role: *Co-applicant* [CAD $40,700]

- Identifying Adaptation Needs and Opportunities for Fisheries Management Operations in Response to Space-based Management for Non-Fishery specific Objectives (2022-2023). Project funded by *Fisheries and Oceans Canada (DFO)*. Role: *Co-applicant*. [CAD $9,450]

- Contributions of marine capture fisheries to the domestic livelihoods and seafood consumption of Brazil, Chile, and Peru. Project funded by *Oceana* (2018-2019). Role: *Co-applicant*. [CAD $95,000]

- SESYNC Graduate Pursuit Award (September 2018 - May 2020). Awarded by the National Socio- Environmental Synthesis Center (SESYNC) to conduct the research Ch-Ch-Ch-Changes: Using Marine Protected Areas to Investigate Potential Socio-Ecological Impacts of Climate Change in Marine Spatial Planning. National Science Foundation and the University of Maryland. (Link to project: tiny.cc/lzxv5y) Role: *Co-applicant* [CAD $2,718]

- Impactos potenciales del cambio climático en las pesquerías mexicanas: Consideraciones para su manejo (2017-2018). Project funded by *Environmental Defense Fund de México*. Role: *Co-applicant*. [CAD
$15,000]

## Awards

- PDF Travel Awards competition (2023). Awarded by the University of British Columbia Faculty of Science of attending the Effects of Climate Change on the World's Oceans in Bergen, Norway.

- Globalink Research Award for research abroad (2019). Awarded by Mitacs for the project Climate change and emerging transboundary fish stocks developed in collaboration with Dr. Elena Ojea at the University of Vigo.

- The Institute for the Oceans and Fisheries Student Society (IOFSS) Travel Grant (2019). Awarded to participate in the conference Species on the Move in July of 2019 in Skukuza, South Africa.

- Faculty of Science PhD. Tuition Award (2016). Awarded by the University of British Columbia to fully fund a PhD. In Zoology

- International Tuition Award (2016). Awarded by the University of British Columbia to fully fund a PhD. In Zoology

- Latin American Fisheries Fellow (LAFF) (2014). Awarded by The Walton Foundation to fully fund a Master of Environmental Science and Management at the University of California, Santa Barbara.

- Mobility Program Award (2010). Awarded by the Universidad Autónoma Metropolitana to go to the São Paulo University, Brazil.