---
title: "Annex Professional Experience"
---


## Professional Research

- Support to create the Climate and Blue Foods Security (Oceans Futures). Project commissioned by World Wildlife Fund (2024). Role: *Principal Investigator*

- Support to project Climate Change Impacts on Blue Foods commissioned by Elizabeth Sight, Stanford university (2024). Role: *Principal Investigator*

- Fortalecimiento de la conservación marina y el desarrollo costero sostenible entre el litoral del Pacífico Central y el Área de Conservación Marina Cocos (ACMC) en Costa Rica (2023). Project commissioned by Fundacion MarViva. Role: *Data analysis*

- Identifying Adaptation Needs and Opportunities for Fisheries Management Operations in Response to Space-based Management for Non-Fishery specific Objectives (2023). Project commissioned by Fisheries and Oceans Canada (DFO). Role: *Co-lead*

- Northern Shelf Bioregion MPAs and climate change (2023-2024). Project commissioned by The Canadian Parks and Wilderness Society (CPAWS) in partnership with the University of British Columbia (UBC) lead by Dr. Colette Wabnitz. Role: *Data analysis*

- The McGovern Mexican project lead by Flavio Favoretto (2022-2023). Project supported by Patrick J. McGovern Foundation. Role: *Data analysis*

- The FishGlob project (2021–2021). Fish biodiversity under global change – a worldwide assessment from scientific trawl surveys, project. Role: *Data analysis*

- Literature review in Portuguese for the MARICA project (2020). Project lead by Elizabeth Selig, Stanford.

- Illuminating Hidden harvest: Mexico (2019). Report commissioned by The Food and Agricultural Organization of the United Nations (FAO). Role: *Data analyst*

- Callo de hacha: restoration program and sustainable fishery in La Paz, BCS, Mexico (2016). A report commissioned by Noroeste Sustentable, A.C. 33 pp. Role: *Co-lead*

- Status and management scenario for the mollusk fisheries of Altata Bay, Sinaloa, Mexico (2016). Report was commissioned by Environmental Defense Fund-Mexico. Pp 37. Role: *Co-lead*

- Peruvian Anchovy Stock Assessment Tool (2016). Member of a team tasked to develop a tool for better manage the Anchovy fishery in Peru. A project in collaboration with The Nature Conservancy and the government of Peru. Role: *Team member*

- TURF Legal Framework Analysis (2015). Reviewed and analyzed the legal framework of Territorial Rights Use for Fisheries (TURFs) of Brazil, Chile and Spain. A report commissioned by Environmental Defense Fund, Mexico. 9 pp. Role: *Principal investigator*

## Other Relevant Work

- Internship (2015) Environmental Defense Fund, Mexico. Analyzed data and worked in the field to see if it was feasible to design a Territorial User Rights for Fisheries (TURF) to manage a high complex system in a bay of Sinaloa, Mexico.

- Dive Center Co-Owner and instructor (2011-2015) Servicios Subacuáticos Medusa. Had different roles: Managed the financial aspects of the business. Coordinated over 30 diving trips both national and international. Instructed SCUBA classes. Managed the Store (sales and inventories).

- Green Business Summit Coordinator (2013) Co-designed the agenda of the summit, managed invitations, coordinated a team of 4 people. Global Institute of Sustainability (GIS), Instituto Tecnológico de Estudios Superiores de Monterrey (ITESM) and Arizona State University (ASU), Mexico City Campus.