---
title: "Annex Invited Seminars"
---

- Impactos das mudanças climáticas nos estoques pesqueiros compartilhados. Invited to speak at XII Oceano Júnior in the *Universidade Estadual do Rio de Janeiro, Campus Maracanã*, Brasil (2024)

- Peixes não precisam de visto: Impactos das Mudanças Climáticas nos Estoques Pesqueiros Compartilhados. Invited to speak at the *Universidade Federal do Rio Grande do Norte*, Brasil (2024)

<!-- - Climate change effects on deep-sea blue-economy. Invited speaker at Deep-Sea Blue Economy Workshop in Saint Vincent and the Grenadines (2023) -->

<!-- - Using modelling to inform transboundary fisheries management under climate change. Invited speaker at Workshop 4 (A global ensemble of comparable marine ecosystem models to project climate risk to species and human communities) of the Effects of Climate Change on the World's Oceans meeting (ECCWO), to be held in Bergen Norway (2023) -->

- Marine fishes do not need visas: managing shared fish stocks in a changing world. Invited speaker at the NWFSC Monster Jam Seminar Series (2023)

- An overview of Canada's changing oceans. Blue Economy Symposium, St. John's, Newfoundland, Canada (2023)

- Challenges of managing transboundary stocks on the move. Seminar Series, Center for Limnology, University of Wisconsin-Madison, United States (2021)

- Límites dinámicos como herramientas para la protección marina en océanos cambiantes. Webinarios del Laboratorio Nacional de Resiliencia Costera, México (2021). Available at: https://www.facebook.com/LANRESC/videos/4140220856092892

- New Research to Adaptive Allocation for Transboundary Fish Stocks. Lenfest Ocean Program (2021). Available at: https://www.lenfestocean.org/news-and-publications/multimedia/webinar-on-new-research-to-adaptive-allocation-for-transboundary-fish-stocks

- Marine fish do not need visas: Transboundary fisheries management under climate change. Seminar Series, Marine Institute, School of Fisheries, Memorial University, Canada (2021)

- Shifting MPAs for conservation and fisheries under a changing climate. Open Channel Webinar Series, Octo group (2021). Available at: https://www.openchannels.org/webinars/2021/shifting-mpas-conservation-and-fisheries-under-changing-climate

- Efectos del cambio climático en el manejo de especies transfronterisas. Centro Austral de Investigaciones Científicas (CADIC-CONICET), Ushuaia, Argentina (2020)

- Marine governance in the anthropocene: Lessons from South Africa and Latin America. Center for Complex Systems Transition, Stellenbosch Institute for Advanced Study, Mosterdrif, Stellenbosch, South Africa (2019)

- Building capacity for fisheries management under climate change in Latin America. Weekly seminars. The United Nations Environment World Conservation Monitoring Center (UN-WCMC), Cambridge, UK. (2017)

- Hacia la creación de una base de metadatos de investigación marina en México. Multiple talks in 2017 and 2018 including Unidad Académica Sisal del Instituto de Ciencias del mar y Limnología de la Universidad Nacional Autónoma de México, Sisal, Yucatán; El Centro de Investigación y de Estudios Avanzados del Instituto Politécnico Nacional, Mérida, Yucatán; Centro Interdisciplinario de Ciencias Marinas del Instituto Politécnico Nacional, La Paz, México and Centro de Investigación Científica y de Educación Superior de Ensenada, Baja California Norte, México, among others.