---
title: "Scientific publications"
---

<!-- OJO Harvard Bou style -->

## Peer Review Articles

44 - **Palacios-Abrantes, J.**, Santos, B. S., Frölicher, T. L., Reygondeau, G., Sumaila, U. R., Wabnitz, C. C. C. and Cheung, W. W. L., 2025. Climate change drives shifts in straddling fish stocks in the world’s ocean. *Science Advances*, adq5976 (11).

43 - Sora, K. J., Wabnitz, C. C. C., Steiner, N. S., Sumaila, U. R., Hoover, C., Niemi, A., Loseto, L., Lea, E. V., Breiter, C. C., **Palacios-Abrantes, J.**, Reygondeau, G., Farnole, P., Sou, T. and Cheung, W. W. L., 2025. Assessing vulnerability of Arctic fish species to climate change. *Discover Oceans*, 2 (1), 32.

42 - Kitchel, Z. J., Maureaud, A. A., Fredston, A., Shackell, N., Mérigot, B., Thorson, J. T., Pécuchet, L., **Palacios-Abrantes, J.**, Palomares, M. L. D., Acón, A. E., Belchier, M., Bono, G., Carbonara, P., Collins, M. A., Cubillos, L. A., Fairweather, T. P., Follesa, M. C., Ruiz, C. G., Garau, M. T. F., Garofalo, G., Isajlović, I., Kathena, J. N., Koen-Alonso, M., Maiorano, P., Manfredi, C., Mifsud, J., O’Driscoll, R. L., Sbrana, M., Sólmundsson, J., Spedicato, M. T., Stephenson, F., Werner, K.-M., Yepsen, D. V., Zupa, W. and Pinsky, M. L., 2025. Marine communities do not follow the paradigm of increasing similarity through time. *PLOS Climate*, 4 (7), e0000659.

41 - Gallo, N. D., Metaxas, A., Lidström, S., Hetherington, E., Alfaro-Lucas, J. M., Amon, D., Barry, J., Bax, N., Boyd, P. W., Colaço, A., Elegbede, I., Escobar-Briones, E., Halfter, S., Hilario, A., Hilmi, N., Huffard, C. L., Iglesias-Rodriguez, M. D., Levin, L. A., McCauley, D. J., Mestre, N. C., Mwangi, P. N., **Palacios-Abrantes, J.**, Rangani, E., Thurber, A. R. and Yasuhara, M., 2025. Illuminating deep-sea considerations and experimental approaches for mCDR proposals. *Environmental Research Letters*, 20 (6), 061003.

40 - Maureaud, A. A., Kitchel, Z., Fredston, A., Guralnick, R., **Palacios-Abrantes, J.**, Palomares, M. L. D., Pinsky, M. L., Shackell, N. L., Thorson, J. T., Alemany, D., Amador, K., Bandara, R. M. W. J., Belmaker, J., Beukhof, E. D., Bograd, S. J., Camara, M. L., Carbonara, P., Chaikin, S., Collins, M. A., Eddy, T. D., Edelist, D., Fock, H. O., Frelat, R., Friedland, K., Grüss, A., Hidalgo, M., Jouffre, D., Kidé, S. O., Koen-Alonso, M., Knuckey, I., Kotwicki, S., Lavender, E., Lindegren, M., Llope, M., Mannocci, L., Mason, J. G., Masski, H., McLean, M., Merillet, L., Mihneva, V., Nunoo, F. K. E., O’Driscoll, R. L., O’Leary, C., Pecuchet, L., Petrova, E., Ramos, J. E., Sobrino, I., Sólmundsson, J., Soni, V., Spies, I., Spedicato, M. T., Stephenson, F., Thiam, N., Tserkova, F., Tserpes, G., Tzanatos, E., Denderen, D. van, Vasilakopoulos, P., Webb, T., Yepsen, D. V., Ziegler, P., Zupa, W. and Mérigot, B., 2025. FISHGLOB: A collaborative infrastructure to bridge the gap between scientific monitoring and marine biodiversity conservation. *Conservation Science and Practice*.

39 - Fredston, A., Tingley, M., Neate-Clegg, M., Evans, L., Antão, L., Ban, N., Chen, I.-C., Chen, Y.-W., Comte, L., Edwards, D., Evengard, B., Fadrique, B., Falkeis, S., Guralnick, R., Klinges, D., Lembrechts, J., Lenoir, J., **Palacios-Abrantes, J.,** Pauchard, A., Pecl, G., Pinsky, M., Senior, R., Smith, J., Soifer, L., Sunday, J., Tape, K., Washam, P. and Scheffers, B., 2025. Reimagining species on the move across space and time. *Trends in Ecology & Evolution*.

38 - **Palacios-Abrantes, J.**, B. S. Dias, I. Gianelli, M. Strand, S. Li, and G. A. Yeboah. 2025. The Role of the Interdisciplinary Marine Early Career Network (IMECaN) in Supporting Capacity Building, Ocean Literacy, and Collaborative Leadership of Early Career Researchers. *Limnol. Oceanogr. Bull.*

37 - Eddy, T. D., Heneghan, R. F., Bryndum-Buchholz, A., Fulton, E. A., Harrison, C. S., Tittensor, D. P., Lotze, H. K., Ortega-Cisneros, K., Novaglio, C., Bianchi, D., Büchner, M., Bulman, C., Cheung, W. W. L., Christensen, V., Coll, M., Everett, J. D., Fierro-Arcos, D., Galbraith, E. D., Gascuel, D., Guiet, J., Mackinson, S., Maury, O., Niiranen, S., Oliveros-Ramos, R., **Palacios-Abrantes, J.**, Piroddi, C., Pontavice, H. du, Reum, J., Richardson, A. J., Schewe, J., Shannon, L., Shin, Y., Steenbeek, J., Volkholz, J., Walker, N. D., Woodworth-Jefcoats, P. and Blanchard, J. L., 2025. Global and Regional Marine Ecosystem Models Reveal Key Uncertainties in Climate Change Projections. *Earth’s Future*, 13 (3).

36 - Murphy, K., Fierro-Arcos, D., Rohr, T., Green, D., Novaglio, C., Baker, K., Ortega-Cisneros, K., Eddy, T. D., Harrison, C. S., Hill, S. L., Eskuche-Keith, P., Cataldo-Mendez, C., Petrik, C. M., Pinkerton, M., Spence, P., Stollberg, I., Subramaniam, R. C., Trebilco, R., Tulloch, V., **Palacios-Abrantes, J.**, Bestley, S., Bianchi, D., Boyd, P., Buchanan, P. J., Bryndum-Buchholz, A., Coll, M., Corney, S., Datta, S., Everett, J. D., Forestier, R., Fulton, E. A., Luzinais, V. G. de, Heneghan, R., Mason, J. G., Maury, O., McMahon, C. R., Murphy, E., Richardson, A. J., Tittensor, D. P., Spillias, S., Steenbeek, J., Veytia, D. and Blanchard, J., 2025. Developing a Southern Ocean Marine Ecosystem Model Ensemble to Assess Climate Risks and Uncertainties. *Earth’s Future*, 13 (3).

35 - Blanchard, J. L., Novaglio, C., Maury, O., Harrison, C. S., Petrik, C. M., Fierro-Arcos, D., Ortega-Cisneros, K., Bryndum-Buchholz, A., Eddy, T. D., Heneghan, R., Roberts, K., Schewe, J., Bianchi, D., Guiet, J., Denderen, P. D. van, **Palacios-Abrantes, J.**, Liu, X., Stock, C. A., Rousseau, Y., Büchner, M., Adekoya, E. O., Bulman, C., Cheung, W., Christensen, V., Coll, M., Capitani, L., Datta, S., Fulton, E. A., Fuster, A., Garza, V., Lengaigne, M., Lindmark, M., Murphy, K., Ouled-Cheikh, J., Prasad, S. S., Oliveros-Ramos, R., Reum, J. C., Rynne, N., Scherrer, K. J. N., Shin, Y., Steenbeek, J., Woodworth-Jefcoats, P., Wu, Y. and Tittensor, D. P., 2024. Detecting, Attributing, and Projecting Global Marine Ecosystem and Fisheries Change: FishMIP 2.0. *Earth’s Future*, 12 (12).

34 - Kaikkonen, L., Shellock, R. J., Selim, S. A., Ojwala, R. A., Dias, B. S., Li, S., Addey, C. I., Gianelli, I., Maltby, K. M., Garcia-Morales, S., **Palacios-Abrantes, J.**, Jiang, S., Albo-Puigserver, M., Alonso, V. A. G., Baker, C. A., Bove, C. B., Brodie, S., Dahlet, L. I., Das, J., Dunne, A., Ferse, S. C. A., Johannesen, E., Jung, J., Garcia, E. M., Karcher, D. B., Mahadeo, S., Millan, L., Lawal, K. O., Oloko, A., Ortega-Cisneros, K., Otoabasi-Akpan, S., Roy, D., Rouf, S. S., Smoliński, S., Vaidianu, N., Whidden, C. and Strand, M., 2024. Fostering diversity, equity, and inclusion in interdisciplinary marine science. *npj Ocean Sustainability*, 3 (1), 49.

33 - Cappa, P., Andreoli, V., La, C., **Palacios-Abrantes, J.**, Reygondeau, G., Cheung, W. W. L. and Zeller, D., 2024. Climate change undermines seafood micronutrient supply from wild-capture fisheries in Southeast Asia and Pacific Island countries. *Science of The Total Environment*, 177024.

32 - Mason, J. G., Bryndum-Buchholz, A., **Palacios-Abrantes, J.**, Badhe, R., Morgante, I., Bianchi, D., Blanchard, J. L., Everett, J. D., Harrison, C. S., Heneghan, R. F., Novaglio, C. and Petrik, C. M., 2024. Key Uncertainties and Modeling Needs for Managing Living Marine Resources in the Future Arctic Ocean. *Earth’s Future*, 12 (8).

31 - Vogel, J. M., Levine, A., Longo, C., Fujita, R., Alves, C. L., Carroll, G., Craig, J. K., Dancy, K., Errend, M., Essington, T. E., Farchadi, N., Glaser, S., Golden, A. S., Jensen, O. P., LeFlore, M., Mason, J. G., Mills, K. E., **Palacios-Abrantes, J.**, Rogers, A., Samhouri, J. F., Seeley, M., Selig, E. R., Trudeau, A. and Wabnitz, C. C. C., 2024. Fisheries in flux: Bridging science and policy for climate-resilient management of US fisheries under distributional change. *Marine Policy*, 170, 106385.

30 - Beaty, F., Domínguez-Sánchez, P. S., Nalven, K. B., **Palacios-Abrantes, J.**, Oken, K. L., Ban, N. C., Nickols, K. J., Juanes, F., Okey, T. A., Spalding, A. K., Morzaria-Luna, H. N., Jenkins, L. D., Tulloch, V. and McKechnie, I., 2024. Centering relationships to place for more meaningful research and engagement. *Proceedings of the National Academy of Sciences*, 121 (25), e2306991121.

29 - Cheung, W. W. L., **Palacios-Abrantes, J**. and Roberts, S. M., 2024. Projecting contributions of marine protected areas to rebuild fish stocks under climate change. *npj Ocean Sustainability*, 3 (1), 11.

28 - Maureaud, A. A., **Palacios-Abrantes, J.**, Kitchel, Z., Mannocci, L., Pinsky, M. L., Fredston, A., Beukhof, E., Forrest, D. L., Frelat, R., Palomares, M. L. D., Pecuchet, L., Thorson, J. T., Denderen, P. D. van and Mérigot, B., 2024. FISHGLOB_data: an integrated dataset of fish biodiversity sampled with scientific bottom-trawl surveys. *Scientific Data*, 11 (1), 24.

27 - **Palacios-Abrantes, J.,** Crosson, S., Dumas, C., Fujita, R., Levine, A., Longo, C., Jensen, O.P., 2023. Quantifying fish range shifts across poorly defined management boundaries. *Plos One* 18, e0279025.

26 - **Palacios-Abrantes, J.,** Roberts, S.M., Brink, T. ten, Cashion, T., Cheung, W.W.L., Mook, A., Nguyen, T., 2023. Incorporating protected areas into global fish biomass projections under climate change. *FACETS* 8, 1–16.

25 - Amon, D. J., **Palacios-Abrantes, J.**, Drazen, J. C., Lily, H., Nathan, N., Grient, J. M. A. van der and McCauley, D., 2023. Climate change to drive increasing overlap between Pacific tuna fisheries and emerging deep-sea mining industry. *npj Ocean Sustainability*, 2 (1), 9.

24 - Spalding, A. K., Grorud-Colvert, K., Allison, E. H., Amon, D. J., Collin, R., Vos, A. de, Friedlander, A. M., Johnson, S. M., Mayorga, J., Paris, C. B., Scott, C., Suman, D. O., Cisneros-Montemayor, A. M., Estradivari, Giron-Nava, A., Gurney, G. G., Harris, J. M., Hicks, C., Mangubhai, S., Micheli, F., Naggea, J., Obura, D., **Palacios-Abrantes, J.**, Pouponneau, A. and Thurber, R. V., 2023. Engaging the tropical majority to make ocean governance and science more equitable and effective. *npj Ocean Sustainability*, 2 (1), 8.

23 - Fredston, A. L., Cheung, W. W. L., Frölicher, T. L., Kitchel, Z. J., Maureaud, A. A., Thorson, J. T., Auber, A., Mérigot, B., **Palacios-Abrantes, J**., Palomares, M. L. D., Pecuchet, L., Shackell, N. L. and Pinsky, M. L., 2023. Marine heatwaves are not a dominant driver of change in demersal fishes. *Nature*, 1–6.

22 - Vogel, J. M., Longo, C., Spijkers, J., **Palacios-Abrantes, J.**, Mason, J., Wabnitz, C. C. C., Cheung, W., Sumaila, U. R., Munro, G., Glaser, S., Bell, J., Tian, Y., Shackell, N. L., Selig, E. R., Billon, P. L., Watson, J. R., Hendrix, C., Pinsky, M. L., Putten, I. van, Karr, K., Papaioannou, E. A. and Fujita, R., 2023. Drivers of conflict and resilience in shifting transboundary fisheries. *Marine Policy*, 155, 105740.

21 - Bryndum-Buchholz, A., Blanchard, J. L., Coll, M., Pontavice, H. D., Everett, J. D., Guiet, J., Heneghan, R. F., Maury, O., Novaglio, C., **Palacios-Abrantes, J.**, Petrik, C. M., Tittensor, D. P. and Lotze, H. K., 2023. Applying ensemble ecosystem model projections to future-proof marine conservation planning in the Northwest Atlantic Ocean. *FACETS*, 8, 1–16.

20 - Pereira, L.M., Crespo, G.O., Amon, D.J., Badhe, R., Bandeira, S., Bengtsson, F., Boettcher, M., Carmine, G., Cheung, W.W.L., Chibwe, B., Dunn, D., Gasalla, M.A., Halouani, G., Johnson, D.E., Jouffray, J.-B., Juri, S., Keys, P.W., Lübker, H.M., Merrie, A.S., Obaidullah, F., **Palacios-Abrantes, J.**, Shannon, L.J., Sumaila, U.R., Superchi, E., Terry, N., Wabnitz, C.C.C., Yasuhara, M., Zhou, W., 2023. The living infinite: Envisioning futures for transformed human-nature relationships on the high seas. *Marine Policy* 153, 105644.

19 - **Palacios-Abrantes, J.**, Frölicher, T. L., Reygondeau, G., Sumaila, U. R., Tagliabue, A., Wabnitz, C. C. C., and Cheung, W. W. L., 2022. Timing and magnitude of climate-driven range shifts in transboundary fish stocks challenge their management. *Global Change Biology*, 28, 2312-2326.

18 - **Palacios-Abrantes, J.**, Badhe, R., Bamford, A., Cheung, W.W.L., Foden, W., Santos, C.F., Grey, K.-A., Kühn, N., Maciejewski, K., McGhie, H., Midgley, G.F., Smit, I.P.J. and Pereira, L.M. 2022. Managing biodiversity in the Anthropocene: discussing the Nature Futures Framework as a tool for adaptive decision-making for nature under climate change, *Sustainability Science*, pp. 1–17.

17 - Cheung, W.W.L., **Palacios‐Abrantes, J.**, Frölicher, T.L., Palomares, M.L., Clarke, T., Lam, V.W.Y., Oyinlola, M.A., Pauly, D., Reygondeau, G., Sumaila, U.R., Teh, L.C.L. and Wabnitz, C.C.C. 2022. Rebuilding fish biomass for the world's marine ecoregions under climate change, *Global Change Biology*

16 - Cinner, J. E., Caldwell, I. R., Thiault, L., Ben, J., Blanchard, J. L., Coll, M., Diedrich, A., Eddy, T. D., Everett, J. D., Folberth, C., Gascuel, D., Guiet, J., Gurney, G. G., Heneghan, R. F., Jägermeyr, J., Jiddawi, N., Lahari, R., Kuange, J., Liu, W., Maury, O., Müller, C., Novaglio, C., **Palacios-Abrantes, J.**, Petrik, C. M., Rabearisoa, A., Tittensor, D. P., Wamukota, A. and Pollnac, R. 2022. Potential impacts of climate change on agriculture and fisheries production in 72 tropical coastal communities. *Nature Communications*, 13(1), p. 3530.

15 - Tittensor, D. P., Novaglio, C., Harrison, C. S., Heneghan, R. F., Barrier, N., Bianchi, D., Bopp, L., Bryndum-Buchholz, A., Britten, G. L., Büchner, M., Cheung, W. W. L., Christensen, V., Coll, M., Dunne, J. P., Eddy, T. D., Everett, J. D., Fernandes-Salvador, J. A., Fulton, E. A., Galbraith, E. D., Gascuel, D., Guiet, J., John, J. G., Link, J. S., Lotze, H. K., Maury, O., Ortega-Cisneros, K., **Palacios-Abrantes, J.**, Petrik, C. M., du Pontavice, H., Rault, J., Richardson, A. J., Shannon, L., Shin, Y.-J., Steenbeek, J., Stock, C. A. and Blanchard, J. L., 2021. Next-generation ensemble projections reveal higher climate risks for marine ecosystems. *Nature Climate Change*.

14 - Sala, E., Mayorga, J., Bradley, D., Cabral, R. B., Atwood, T. B., Auber, A., Cheung, W. W. L., Costello, C., Ferretti, F., Friedlander, A. M., Gaines, S. D., Garilao, C., Goodell, W., Halpern, B. S., Hinson, A., Kaschner, K., Kesner-Reyes, K., Leprieur, F., McGowan, J., Morgan, L. E., Mouillot, D., **Palacios-Abrantes, J.**, Possingham, H. P., Rechberger, K. D., Worm, B., and Lubchenco, J., 2021. Protecting the global ocean for biodiversity, food and climate. *Nature*, 1–6.

13 - Outeiro, L., Otero, J., Alonso-Fernández, A., Bañón, R., and **Palacios-Abrantes, J.**, 2021. Quantifying abundance trends and environmental effects on a population of queen scallop Aequipecten opercularis targeted by artisanal fishers in a coastal upwelling area (Ría de Arousa, NW Spain) using a Bayesian spatial model. *Journal of Environmental Economics and Management*, 240, 105963.

12 - Heneghan, R.F., Galbraith, E., Blanchard, J.L., Harrison, C., Barrier, N., Bulman, C., Cheung, W., Coll, M., Eddy, T.D., Erauskin-Extramiana, M., Everett, J.D., Fernandes-Salvador, J.A., Gascuel, D., Guiet, J., Maury, O., **Palacios-Abrantes, J.**, Petrik, C.M., du Pontavice, H., Richardson, A.J., Steenbeek, J., Tai, T.C., Volkholz, J., Woodworth-Jefcoats, P.A., Tittensor, D.P., 2021. Disentangling diverse responses to climate change among global marine ecosystem models. *Progress in Oceanography* 198, 102659.

11 - **Palacios-Abrantes, J.**, Reygondeau, G., Wabnitz, C. C. C., and Cheung, W. W. L., 2020. The transboundary nature of the world's exploited marine species. *Scientific Reports*, 10 (1), 415–12.

10 - **Palacios-Abrantes, J.**, Sumaila, U. R., and Cheung, W. W. L., 2020. Challenges to transboundary fisheries management in North America under climate change. *Ecology and Society*, 25 (4), art41–17.

9 - Sumaila, U. R., **Palacios-Abrantes, J.**, and Cheung, W. W. L., 2020. Climate change, shifting threat points, and the management of transboundary fish stocks. *Ecology and Society*, 25 (4), art40–9.

8 - Cashion, T., Nguyen, T., Brink, ten, T., Mook, A., **Palacios-Abrantes, J.**, and Roberts, S. M., 2020. Shifting seas, shifting boundaries: Dynamic marine protected area designs for a changing climate. *PLoS ONE*, 15 (11), e0241771.

7 - Andrews, E. J., Harper, S., Cashion, T., **Palacios-Abrantes, J.**, Blythe, J., Daly, J., Eger, S., Hoover, C., Talloni-Álvarez, N., Teh, L., Bennett, N., Epstein, G., Knott, C., Newell, S. L., and Whitney, C. K., 2020. Supporting early career researchers: insights from interdisciplinary marine scientists. *ICES Journal of Marine Science*, 77 (2), 476–485.

6 - Cisneros-Montemayor, A. M., Abas, M., **Palacios-Abrantes, J.**, and González-Espinosa, P. C., 2020. Spatial analysis of anticipated climate change effects on fisheries in Mexico: An overview for adaptation. *Ciencia Pesquera*, 28 (1-2), 31–44.

5 - **Palacios-Abrantes, J.**, Cisneros-Montemayor, A. M., Cisneros-Mata, M. A., Rodriguez, L., Arreguín-Sánchez, F., Aguilar, V., Domínguez-Sánchez, S., Fulton, S., López-Sagástegui, R., Reyes-Bonilla, H., Rivera-Campos, R., Salas, S., Simoes, N., and Cheung, W. W. L., 2019. A metadata approach to evaluate the state of ocean knowledge: Strengths, limitations, and application to Mexico. *PLoS ONE*, 14 (6), e0216723.

4 - **Palacios-Abrantes, J**., Herrera-Correal, J., Rodriguez, S., Brunkow, J., and Molina, R., 2018. Evaluating the bio-economic performance of a Callo de hacha (*Atrina maura, Atrina tuberculosa and Pinna rugosa*) fishery restoration plan in La Paz, Mexico. *PLoS ONE*, 13 (12), e0209431.

3 - Pinsky, M. L., Reygondeau, G., Caddell, R., **Palacios-Abrantes, J**., Spijkers, J., and Cheung, W. W. L., 2018. Preparing ocean governance for species on the move. *Science*, 360 (6394), 1189–1191.

2 - **Palacios-Abrantes, J.**, Melo-Ruiz, V., Urbano, B., Vargas, N., Falcón-Gerónimo, J., and Gazga-Urioste, C., 2017. Nutritional Analysis of *Octopus hubbsorum* B (Cephalopoda: Octopodidae) from the Pacific Ocean, Acapulco, Guerrero, México. *Journal of Applied Life Sciences International*, 10 (3), 1–6.

1 - **Palacios-Abrantes, J.**, Melo-Ruiz, V., Diaz-Garcia, R., Gazga-Urioste César, and Urbano, B., 2016. Iron Profile of *Octopus Hubbsorum* (Cephalopoda: Octopodidae) for Enrichment of the Mexican Diet. *Journal of Chemistry and Chemical Engineering*, 10 (5), 1–4.

## Book Chapters

4b - Amon, D. and **Palacios-Abrantes, J.**, 2024. Dumping, pillaging and slavery - why exploitation of the high seas must end. *Nature*, 629 (8013), 751–753.

3b - **Palacios-Abrantes, J.**, Tai, T., *et al.* (eds. **Palacios-Abrantes, J.** and Tai, T.) Rapid changes across Canada's oceans in (ed. Sumaila, U.R.) Ocean Canada Partnership Book *[UBC Prints - 2024]*

2b - Steiner, N. *et al.* (e.d. Steiner, N.) Rapid changes across Canada's oceans in (ed. Sumaila, U.R.) Ocean Canada Partnership Book *[UBC Prints -2024]*

1b - **Palacios-Abrantes, J.** and Cisneros-Montemayor, A. Tendencias de la investigación pesquera en México: necesidades y oportunidades para la adaptación al cambio climático. 2020. In (eds. Tapia, P. and Urrea, U.) Pescadores en México y Cuba retos y oportunidades ante el cambio climático. Ciudad de México, 225

## Contributing Author

3c - Queirós A.M., Cheung W.C., and **Palacios-Abrantes J**. 2025. Contributing author of the chapter Climate-smart MPAs – a tool for addressing ocean climate change in Millington-Drake, M., S. Locke, S. Regalado, and A. M. Queirós (Authors). Navigating change the role of climate-smart MPAs in achieving 30x30. Report commissioned by Blue Marine Foundation. Available at:https://www.bluemarinefoundation.com/wp-content/uploads/2025/04/Climate-Smart-Report-Blue-Marine.pdf

2c - Waldron, A., et al. 2020. Contribution towards the report, Protecting 30% of the planet for nature: costs, benefits and economic implications. Working paper analyzing the economic implications of the proposed 30% target for area protection in the draft post-2020 Global Biodiversity Framework. Report commissioned by Campaign for Nature. Available at https://www.conservation.cam.ac.uk/files/waldr on_report_30_by_30_publish.pdf

1c - Wabnitz, C. and **Palacios-Abrantes, J**. 2019. Contributing author of the transboundary resource management section of the International Dimensions Chapter for *NRCan's National Knowledge Assess- ment of Climate Change Impacts and Adaptation*. Available at https://changingclimate.ca/National- Issues/chapter/9-0/

## Work in Press or Under Review (R&R)
*Note that any work in progress is not listed here*

- **Palacios-Abrantes J.**, Clarke T, Beita A, RomeroR, Villalobos-Rojas F., Sánchez C., and  Cheung W.L. (In prep). Projected consequences of climate change to commercially important species in the Marine Corridor of the Eastern Tropical Pacific (CMAR)  *In preparation*

