---
title: "conferences"
---

*Participated in 48 international academic events including 22 scientific conferences, 5 policy conferences, and 18 workshops from which I co-organized 8.* **See [Annex Conferences and Workshops](#an_conference) for full list**

- Multiple workshops (n = 4) with park managers on the impacts of climate change on the Marine Corridor of the Eastern Tropical Pacific (CMAR). Organized by *Fundación MarViva*, San José, Costa Rica; Panamá City, Panamá; Cali, Colombia; Galápagos, Ecuador (2025) [*Co-organized*]

- 62nd sessions of the UNFCCC Subsidiary Body for Implementation (SBI) and Subsidiary Body for Scientific and Technological Advice (SBSTA), SB62. Bonn, Germany (2025) [*Participation*]

- Efectos del cambio climático en los stocks y el manejo regional de peces transfronterizos de América del sur. Simposio Argentino de Ictiología, Ushuaia, Argentina (2024) [*Presentation*]

- Managing Fisheries in a World of Shifting Stocks: Integrating Biological, Policy, Behavioural, Social and Economic Aspects. Session on the World Fisheries Congress (2024) [*Co-Organizer*]

- Using modelling to inform transboundary fisheries management under climate change. Invited speaker at the ECCWO5 conference, Bergen Norway (2023).

