---
title: "Knowledge movilization"
---

*Engaged in over 20 events including interviews for news outlets and radio, co-elaboration of press releases and non-scientific documents as well as talks in both Spanish and English.* **See [Annex Knowledge Mobilization](#an_knowledge_mob) for full list of engagement activities***

- 'Light of hope': B.C. researchers say some fish surviving heat waves better than once thought (2023). Interview for The Times Colonist. Available at: https://www.timescolonist.com/local-news/light-of-hope-bc-researchers-say-some-fish-surviving-heat-waves-better-than-once-thought-7493628)

- El Espectador Colombia (2023) ¿Se avecina el primer proyecto de minería en el mar? Available at: https://www.elespectador.com/ambiente/se-avecina-el-primer-proyecto-de-mineria-en-el-mar/

- Managing fish stocks shared by nations must focus on the impacts of climate change (2022). The Conversation Canada. Available at: https://theconversation.com/managing-fish-stocks-shared-by- nations-must-focus-on-the-impacts-of-climate-change-181828

- Climate change could spark fish wars around the globe (2022). Radio interview for Quirks and Quarks with Bob McDonald (CBC). Available at: https://www.cbc.ca/listen/live-radio/1-51/clip/15893391

- CONACyT Prensa  México (2018)- ¿Cómo afectará el cambio climático las pesquerías del mundo? Available at: http://www.conacytprensa.mx/index.php/ciencia/ambiente/24771-cambio-climatico-pesquerias-mundo)