---
title: "Seminar"
---

*Invited to give over 10 seminars at different institutions and international meetings.* **See [Annex Invited Seminars](#an_seminar) for full list**

- Impactos das mudanças climáticas nos estoques pesqueiros compartilhados. Invited to speak at XII Oceano Júnior in the Universidade Estadual do Rio de Janeiro, Campus Maracanã, Brasil (2024)

- Peixes não precisam de visto: Impactos das Mudanças Climáticas nos Estoques Pesqueiros Compartilhados. Invited to speak at the Universidade Federal do Rio Grande do Norte, Brasil (2024)

- Using modelling to inform transboundary fisheries management under climate change. Invited speaker at Workshop 4 (A global ensemble of comparable marine ecosystem models to project climate risk to species and human communities) of the Effects of Climate Change on the World's Oceans meeting (ECCWO),Bergen Norway (2023)

- Hacia la creación de una base de metadatos de investigación marina en México. Multiple talks in 2017 and 2018 including Unidad Académica Sisal del Instituto de Ciencias del mar y Limnología de la Universidad Nacional Autónoma de México, Sisal, Yucatán; El Centro de Investigación y de Estudios Avanzados del Instituto Politécnico Nacional, Mérida, Yucatán; Centro Interdisciplinario de Ciencias Marinas del Instituto Politécnico Nacional, La Paz, México and Centro de Investigación Científica y de Educación Superior de Ensenada, Baja California Norte, México, among others.