---
title: "Teaching Experience and Mentoring"
---

*Imparted several courses and guess lectures over the last 10 years in topics related to fisheries management, climate change, and data analysis and computed modelling.* **See [Annex *Teaching Experience and Mentoring*](#an_teaching) for full list**

- Curso de limpeza e análise de dados para realizar modelos de distribuição de espécies. Co-production with Burnno Oliveira. Full one week course a the *Universidade Federal do Rio Grande do Norte* (2024)

- Fisheries management under a changing climate. Guest lecture on climate change and fisheries for University of Victoria 4th year class lead by Dr. Julia K. Baum (2024, 2023)

- Introduction to fisheries management. Guest lecture on EOSC 478 Introduction to Fisheries Science of the University of British Columbia lead by Yevhenii Pakhomov (2023, 2022)

- Mentoring of 7 undergrad students from The University of British Columbia (2021-2022) through the Biology Undergraduate Diversity in Research Program (BUDR), a program designed to support students from historically marginalized and disenfranchised backgrounds.