---
title: "La gobernanza oceánica integrada es necesaria en el Océano Atlántico Sudoccidental para fomentar las pesquerías, la conservación y la resiliencia al cambio climático"
subtitle: "Juliano Palacios-Abrantes, Facundo Llompart, Omar Defeo, Ignacio Gianelli, Andrés J. Jaureguizar, Priscila F. M.  Lopes1, José Angel A. Perez, Natali I. P. Piccolo, Alberto R. Piola, Andrei Polejack, Luciana F. Prado, Martin Saraceno"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
lang: es
---


-   **NOTA: esta es una traducción al español del artículo:** Integrated ocean governance is needed in the Southwest Atlantic Ocean to foster fisheries, conservation and resilience to climate change, escrito por Palacios-Abrantes J.y colaboradores y que se puede encontrar en la siguiente [liga](https://doi.org/10.1007/s44289-026-00134-4).

    -   Traducido por Juliano Palacios. Revisión técnica de ... Traducido con ayuda de *Perplexity*



## Resumen

El Océano Atlántico Sudoccidental (OASO) es una región de importancia mundial, donde diversas masas de agua convergen y se mezclan, regulando el clima terrestre a la vez que sostiene pesquerías productivas y una alta biodiversidad marina. La conectividad ecológica también es considerable, con múltiples especies y ecosistemas compartidos a través de diversas jurisdicciones y fronteras internacionales. Sin embargo, a pesar de los esfuerzos históricos y de los llamados más recientes a una gestión regional, el OASO es una de las pocas grandes regiones oceánicas que carece de un órgano dedicado a la gobernanza oceánica que cubra todos los recursos compartidos. Esta desconexión resulta particularmente alarmante frente al cambio climático, que está alterando la distribución y abundancia de los stocks pesqueros, desplazando los rangos de distribución de las especies hacia los polos e intensificando la incertidumbre en la gestión de los recursos marinos. Un marco regional colaborativo, fundamentado en la gestión basada en ecosistemas, es urgentemente necesario para fomentar una gestión sostenible y reforzar la resiliencia ante los impactos del cambio climático. A medida que Brasil acoge una serie de reuniones de las Naciones Unidas sobre temas ambientales, la región enfrenta un momento decisivo: bien mantenerse reactiva ante las estructuras de gobernanza externas, o bien diseñar proactivamente marcos que reflejen las prioridades regionales, equilibren las preocupaciones de soberanía e integren mejor la evidencia científica en la toma de decisiones. Por ello, invitamos a tomadores de decisiones, gestores y científicos a aprovechar el impulso político en América Latina para avanzar hacia una gobernanza oceánica integrada y multiescalar, al tiempo que se fortalece la diplomacia científica oceánica en el OASO. Este es un llamado a contribuir a navegar un futuro incierto abordando los desafíos compartidos y priorizando la sostenibilidad oceánica en el OASO.

---

## Introducción

### El Océano Atlántico Sudoccidental: Una región de importancia ecológica y socioeconómica

Con una extensión de 17,65 millones de km² entre los 5°N y los 60°S, el Océano Atlántico Sudoccidental (OASO) engloba diversas características oceánicas, biogeográficas y ecológicas que sustentan una biodiversidad excepcional y pesquerías de alto valor socioeconómico (Fig. 1). Distribuida dentro y más allá de las jurisdicciones nacionales, la región alberga puntos críticos de biodiversidad, corredores migratorios y hábitats críticos que sostienen funciones de desove, apareamiento, crianza y alimentación de múltiples especies importantes y vulnerables, incluyendo peces, tiburones, cefalópodos y mamíferos marinos como las ballenas jorobadas y australes, y orcas [1--3]. Estas características son el resultado de rasgos geomorfológicos, hidrográficos y biogeoquímicos que delimitan provincias biogeográficas y ecoregiones distintas, con altos niveles de endemismo y cohesión ecológica [4,5].


**Figura 1. El Océano Atlántico Sudoccidental.** La batimetría muestra las regiones someras en amarillo y las más profundas en morado. El cuadro negro representa el Área de Pesca Mayor 41 de la Organización de las Naciones Unidas para la Alimentación y la Agricultura. Las líneas blancas representan las Zonas Económicas Exclusivas de Brasil (continental), Uruguay y Argentina. Las líneas de contorno azules representan las distintas ecoregiones consideradas, mientras que las rojas representan ecoregiones fuera del OASO, según Spalding et al. 2007 [4]. Las líneas negras discontinuas representan las principales corrientes. NBC, Corriente del Norte de Brasil. SEC, Corriente Ecuatorial del Sur. BC, Corriente de Brasil. MC, Corriente de Malvinas. ACC, Corriente Circumpolar Antártica. SAC, Corriente de América del Sur. ZG, Giro de Zapiola.

La importancia ecológica del OASO se extiende igualmente a las pesquerías (Fig. 2). Designado por la Organización de las Naciones Unidas para la Alimentación y la Agricultura (FAO) como Área de Pesca Mayor 41 (Fig. 1), el OASO cuenta con más de 32.000 embarcaciones artesanales e industriales, que emplean a 896.000 personas. En 2021, las capturas en estas pesquerías multiespecíficas se estimaron en 2 millones de toneladas, con un valor de 5.000 millones de dólares [6]. En el norte de Brasil (al norte de los 20°S), la plataforma continental sustenta pesquerías multiespecíficas de pequeña escala, aunque a menudo con una cobertura estadística limitada. Más al sur, las pesquerías industriales se han desarrollado a lo largo de las plataformas de Brasil, Uruguay y Argentina, dirigidas a stocks compartidos de alto valor comercial [7--9]. Además, en el OASO, la conectividad entre regiones es marcada. Por ejemplo, en invierno, los stocks de peces, camarón y calamar se desplazan hacia el norte desde las plataformas patagónica septentrional y uruguaya hacia la plataforma sur de Brasil, donde representan un componente sustancial de la industria pesquera en esta productiva e importante región económica del país [10,11]. Esta conectividad resulta en un elevado número de stocks compartidos (transfronterizos, solapantes y altamente migratorios solapantes, Cuadro 1) en la composición de capturas de estos países (Fig. 2b) [12--14].

**Cuadro 1. Glosario de terminología incluida en el presente artículo.**

| **Término** | **Definición** |
|---|---|
| Circulación meridional de retorno del Atlántico (AMOC) | Un gran sistema de corrientes oceánicas en el Océano Atlántico que transporta aguas superficiales cálidas y salinas hacia el norte y devuelve aguas más frías y profundas hacia el sur. Desempeña un papel crítico en la regulación del clima global al redistribuir el calor, influyendo en los patrones climáticos y afectando el ciclo del carbono y el nivel del mar. |
| Gestión basada en ecosistemas (GBE) | Gestión de recursos que considera la totalidad del ecosistema socioecológico (es decir, incluidas las actividades humanas y los factores sociales y económicos) para mantener la integridad ecológica y el bienestar humano. |
| Escenario de alto nivel de emisiones de cambio climático (SSP5-8.5) | Escenario de cambio climático que representa un futuro con alta forzante radiativa debido al aumento de las emisiones de gases de efecto invernadero, que conduce a un calentamiento global sustancial. |
| Pesca ilegal, no declarada y no reglamentada (INDNR) | Actividades pesqueras que violan las leyes nacionales, regionales o internacionales, o que se producen al margen de dichas leyes, socavando la sostenibilidad de los ecosistemas marinos. |
| Gobernanza oceánica | El marco colectivo de políticas, instituciones, procesos y prácticas a través de los cuales las sociedades gestionan el uso, la conservación y el desarrollo sostenible de los océanos y sus recursos. |
| Diplomacia científica oceánica | Término paraguas para clasificar los fenómenos resultantes de las múltiples interacciones de la ciencia con las relaciones internacionales, incluyendo el asesoramiento científico en asuntos oceánicos, la cooperación científica que orienta la política exterior y la diplomacia que apoya la ciencia para abordar desafíos humanitarios. |
| Organización Regional de Ordenación Pesquera (OROP) | Organismos internacionales donde los países colaboran para gestionar y conservar los stocks pesqueros de valor que cruzan fronteras nacionales, como los stocks transfronterizos, solapantes y altamente migratorios. |
| Stocks altamente migratorios solapantes | Stocks de peces (p. ej., pelágicos) ampliamente distribuidos entre aguas internacionales y Zonas Económicas Exclusivas (ZEE) no adyacentes. |
| Stocks solapantes | Stocks de peces que cruzan el límite de ZEE vecinas y la alta mar. |
| Stocks transfronterizos | Stocks de peces que se distribuyen, en la totalidad o en parte de su ciclo de vida, entre dos o más ZEE vecinas. |

La importancia ecológica y la rica productividad pesquera del OASO están sustentadas por condiciones oceanográficas únicas y complejas (Fig. 1). Bajo la influencia de corrientes de frontera occidental relativamente intensas, a saber, la Corriente del Norte de Brasil (NBC), la Corriente de Brasil (BC) y la Corriente de Malvinas (MC) (Fig. 1), la región se caracteriza por una intensa mezcla entre aguas subtropicales y subantárticas [15,16]. En combinación con zonas frontales, remolinos, surgencias y las descargas de las principales cuencas fluviales, estos procesos son responsables de ecosistemas de elevada productividad [17--20]. La marcada variabilidad espacial y temporal de la región moldea la distribución y abundancia de las comunidades marinas, situando al OASO entre las regiones marinas más productivas del mundo [6,8,21,22].


**Figura 2. Riqueza de especies y capturas en el Océano Atlántico Sudoccidental. a)** Riqueza de especies para todos los taxa (datos de AquaMaps/AquaX, [www.aquamaps.org](http://www.aquamaps.org)). Los polígonos en blanco y negro representan las áreas marinas protegidas de la región (datos del Centro Mundial de Monitoreo de la Conservación de las Naciones Unidas [23] y del Instituto Chico Mendes de Conservação da Biodiversidade [24]). **b)** Capturas en la ZEE de cada país procedentes de todos los stocks y de los stocks compartidos (datos de The Sea Around Us, [www.searoundus.com](http://www.searoundus.com) según [25]).

---

## Gobernanza oceánica en el OASO

Brasil, Uruguay y Argentina son signatarios de diversas convenciones y tratados de las Naciones Unidas relacionados con la gobernanza oceánica y han colaborado ampliamente en la aplicación de estas disposiciones a nivel regional. Por ejemplo, los tres países son signatarios de la Convención de las Naciones Unidas sobre el Derecho del Mar (CONVEMAR), del Convenio sobre la Diversidad Biológica (CDB) y del Acuerdo sobre la Conservación y el Uso Sostenible de la Diversidad Biológica Marina de las Áreas Fuera de la Jurisdicción Nacional (Acuerdo BBNJ), aunque aún no han ratificado este último. A nivel regional, mantienen un sólido historial de cooperación en el marco de la Comisión Internacional para la Conservación del Atún Atlántico (CICAA), en particular mediante análisis conjuntos y contribuciones coordinadas a las evaluaciones de stocks (p. ej., [26,27]). Asimismo, son signatarios de la Zona de Paz y Cooperación del Atlántico Sur (ZOPACAS), una alineación política orientada a promover la paz, la seguridad y la solidaridad regional entre las naciones costeras del Atlántico Sur en África y América del Sur.

Sin embargo, los esfuerzos integrados en materia de conservación y gobernanza pesquera siguen siendo limitados, como lo ilustra el Acuerdo sobre Medidas del Estado Rector del Puerto (AMERP). El AMERP es un acuerdo vinculante e instrumento clave del Código de Conducta para la Pesca Responsable. Exige a las Partes que refuercen la supervisión de los buques pesqueros extranjeros para combatir la pesca ilegal, no declarada y no reglamentada (INDNR) por parte de las flotas de pesca de aguas distantes. Su objetivo es reducir el incentivo de los buques que realizan pesca INDNR mediante la prohibición de desembarcar sus capturas en los puertos de las Partes del AMERP, al tiempo que se protegen los mercados nacionales e internacionales [28]. Sin embargo, en la actualidad, Uruguay es la única Parte del OASO que ha ratificado el AMERP. El mejor ejemplo de cooperación trilateral fue quizás la *Comisión Asesora Regional de Pesca para el Atlántico Sudoccidental* (CARPAS), establecida por la FAO en 1962 [8]. CARPAS desempeñó un papel importante como Comisión Asesora Regional de Pesca para el Atlántico Sudoccidental, coordinando estadísticas pesqueras, promoviendo la investigación biológica y realizando evaluaciones de stocks. Sin embargo, CARPAS fue oficialmente abolida por la Resolución 13/97 de la Conferencia de la FAO en 1997, tras la creación de las ZEE y el establecimiento en 1976 de la Comisión Técnica Mixta del Frente Marítimo (CTMFM). La CTMFM evalúa el estado de los recursos pesqueros y propone medidas de gestión dentro de la Zona Común de Pesca Argentino-Uruguaya (ZCPAU). En la actualidad, la ZCPAU funciona como un área de soberanía compartida para los recursos pesqueros transfronterizos de Argentina y Uruguay. La CTMFM es reconocida por la FAO como el único organismo pesquero regional en el Atlántico Sudoccidental. Aunque existen sólidos arreglos bilaterales entre Argentina y Uruguay, la participación de Brasil ha permanecido comparativamente incipiente desde el fin de CARPAS, con la mayor parte de los esfuerzos impulsados por la cooperación científica clásica en una variedad de temas de investigación marina [2,7,8].

---

## Los desafíos abundan en el OASO

Las bien documentadas tensiones geopolíticas en el OASO continúan moldeando los enfoques regionales para la gobernanza oceánica y la gestión sostenible de los recursos marinos, con dinámicas que son agravadas de manera creciente por las presiones combinadas de la pesca INDNR y el cambio climático. Las iniciativas de conservación también siguen siendo limitadas, fragmentadas y frecuentemente desconectadas de la gestión pesquera, lo que socava la capacidad de salvaguardar los servicios ecosistémicos y de responder eficazmente a las presiones acumuladas, incluidas la sobrepesca, la degradación de hábitats y la variabilidad impulsada por el clima.

### Desafíos de gobernanza

Las pesquerías del OASO ilustran las tensiones entre gobernanza, competencia económica y sostenibilidad. La creciente presencia de flotas de aguas distantes con tecnologías de explotación de vanguardia, particularmente procedentes de Asia y Europa, que apuntan a recursos de alto valor como el calamar y el atún, genera una competencia desigual con las flotas domésticas industriales y de pequeña escala [29,30]. Este desequilibrio se ve intensificado por los subsidios externos y el uso de pabellones de conveniencia, que crean asimetrías de mercado y presiones sobre la seguridad alimentaria de las comunidades locales [31]. Paralelamente, estas dinámicas reflejan la expansión de las pesquerías no reglamentadas, como las del calamar, que explotan lagunas institucionales en áreas de alta mar y en los márgenes de las jurisdicciones nacionales [32]. Este desafío se ve agravado por la ausencia de Brasil y Argentina en el AMERP. La proximidad geográfica entre Uruguay, Brasil y Argentina debilita la efectividad de este Acuerdo, que se basa en parte en la dificultad de acceder a puertos fuera del marco del AMERP. Cuando los Estados miembros del AMERP colindan con Estados no miembros, los buques extranjeros pueden desviar su ruta hacia puertos no pertenecientes al AMERP o re-enarbolar oportunistamente pabellones de registros domésticos, práctica conocida como "domesticación de pabellón" [31]. Entre 2016 y 2021, el número de visitas portuarias de buques que re-enarbolan pabellón doméstico en Brasil y Uruguay aumentó aproximadamente un 27% y un 57%, respectivamente [31]. Si bien la ratificación del AMERP representa un paso importante para combatir la pesca INDNR en la región, su efectividad depende en última instancia de la implementación, la coordinación y las medidas nacionales complementarias. En este contexto, el papel de Brasil como signatario (pero no como parte ratificante) y el estatus de Argentina como no signatario con controles portuarios existentes pone de relieve tanto las oportunidades como las limitaciones de depender del AMERP de forma aislada.

La disputa de soberanía entre Argentina y el Reino Unido sobre las Islas Malvinas/Falkland, las Islas Georgias del Sur y las Islas Sandwich del Sur, y las áreas marítimas circundantes, intensificada por la potencial explotación de los recursos marinos compartidos, sigue siendo un desafío geopolítico central. En este contexto, más de 42 comunidades pesqueras artesanales costeras (SSF) se distribuyen a lo largo de la costa patagónica de Argentina [33], con una gestión mayoritariamente independiente y escasos avances hacia acuerdos de investigación conjunta o gestión coordinada e inclusiva [34]. En este escenario, la diplomacia de Brasil, Uruguay y Argentina ha resistido el establecimiento de una Organización Regional de Ordenación Pesquera (OROP) para el OASO. Dicha resistencia obedece no solo a las disputas históricas de larga data, sino también a la preocupación de que la regulación multilateral pueda proporcionar un punto de apoyo legal para actores extra-regionales, diluyendo así la soberanía nacional y socavando la autonomía regional sobre los stocks pesqueros estratégicos [8]. La experiencia de los Estados insulares del Pacífico ofrece enseñanzas para la región: estos países temían que el establecimiento de la Comisión para la Pesca del Pacífico Occidental y Central (WCPFC) sirviera como punto de apoyo legal para que actores extra-regionales diluyeran la soberanía de los Estados ribereños. Estas preocupaciones llevaron al desarrollo de estrategias para resistir la inclusión de las naciones pesqueras de aguas distantes en la gestión pesquera, una vez que el Acuerdo de las Naciones Unidas sobre las Poblaciones de Peces (ANUP) proporcionó legitimidad jurídica internacional para su posición [35]. Además, al sur de los 45°S, valiosos stocks transfronterizos son explotados por flotas de diversas nacionalidades. Por ejemplo, la pesquería de cangrejo (explotación conjunta del centolla del sur *Lithodes santolla* y la centollón *Paralomis granulosa*) en el Canal Beagle es compartida entre Argentina y Chile, pero gestionada de forma independiente [34]. La gobernanza en esta región está fragmentada y es frecuentemente unilateral, sin que la evidencia científica se integre plenamente en la toma de decisiones. La cooperación pasada a través de la Comisión de Pesca del Atlántico Sur proporcionó algunas medidas conjuntas, pero ha estado suspendida desde 2020. Más recientemente, iniciativas de investigación bilateral, como las de Argentina y Chile sobre la merluza negra, muestran potencial para una mayor cooperación [36]. Desde una perspectiva puramente ecológica, una estrategia de gestión colaborativa parece prometedora. Sin embargo, las disputas de soberanía sobre las Islas Malvinas/Falkland convierten a esta zona en uno de los caladeros geopolítica y ambientalmente más complejos del mundo.

### Las brechas de datos limitan la conservación y la gestión pesquera efectivas

La conservación y gestión efectiva de las pesquerías en el OASO están limitadas por persistentes deficiencias de datos. Por ejemplo, las especies de preocupación para la conservación en la región, como los tiburones, cuentan con datos observacionales escasos [3]; la comprensión de la estructura de las comunidades de peces de arrecife se limita a subregiones específicas [37]; los ecosistemas de aguas profundas están prácticamente inexplorados visualmente [38]; y los datos pesqueros son frecuentemente incompletos [39]. Todas estas limitaciones tienen implicaciones para los esfuerzos regionales de proteger la biodiversidad marina y gestionar las pesquerías de forma sostenible.

Un obstáculo crítico para la gestión, incluida la gestión cooperativa, es la generalizada falta de datos fiables y consistentes sobre las pesquerías en toda la región, especialmente en el caso de las pesquerías de pequeña escala (PEA), que son crónicamente subdeclaradas en toda América Latina y el Caribe [39]. Aunque no es exclusivo de esta zona, este déficit general de datos puede ejemplificarse en el OASO con las PEA del norte de Brasil [40]. La recopilación sistemática de datos en Brasil ha sido inconsistente desde principios de la década de 2010, en gran medida debido a la inestabilidad institucional [40]. De 1990 a 2007, el Instituto Brasileño de Medio Ambiente (IBAMA) coordinó las estadísticas pesqueras nacionales con una amplia cobertura [41]. Sin embargo, las múltiples reformas institucionales posteriores desplazaron la responsabilidad hacia nuevos organismos, interrumpiendo la compilación de datos y resultando en una paralización casi total a nivel nacional [40]. Desde entonces, no se ha restablecido ningún programa nacional sostenido, y la información proviene principalmente de iniciativas estatales o académicas concentradas en el sur y sureste de Brasil, dejando al norte y noreste, donde las PEA superan las capturas industriales y sustentan la seguridad alimentaria local y los medios de vida, en una situación de severa falta de monitoreo [42--44]. En ausencia de un monitoreo sistemático, el alcance de esta conectividad (y el estado de los stocks compartidos adicionales) permanece mal determinado, lo que impide la gobernanza coordinada y la gestión adaptada al clima. Esta realidad tiene implicaciones adicionales para la gestión de los stocks transfronterizos en el norte/noreste de Brasil y la plataforma de las Guayanas, como el camarón tití (*Xiphopenaeus kroyeri*) y la corvina real (*Cynoscion acoupa*) [45,46].

### El cambio climático amplifica los desafíos existentes

El cambio climático está ya reconfigurado el tejido oceanográfico y ecológico del OASO, con la mayor parte de la región habiendo experimentado un calentamiento superficial sustancial durante las últimas cuatro décadas [7,47] (Fig. 3a). Los eventos compuestos de olas de calor marino, alta acidez y bajo nivel de clorofila también han aumentado rápidamente en el Atlántico ecuatorial y sur recientemente [48]. Estos cambios ecológicos impulsados por el clima ya están induciendo profundas transformaciones económicas, sociales y ambientales en el OASO. Por ejemplo, la intensificación de la Corriente de Brasil [7,20] está alterando la distribución espacial de los ensamblajes de peces y mariscos a lo largo de las plataformas de Brasil y del norte argentino-uruguayo, aumentando la prevalencia de especies de aguas cálidas y reduciendo los componentes de aguas frías. Los registros de capturas y los datos observacionales revelan una tropicalización de las pesquerías, con especies de aguas cálidas cada vez más prevalentes mientras las de aguas frías declinan, reflejando desplazamientos de distribución hacia los polos [49,50].

Las proyecciones futuras del clima en la región continuarán cambiando, aunque con un alto nivel de incertidumbre. Por ejemplo, las proyecciones futuras muestran una debilitación de la Circulación Meridional de Retorno del Atlántico (AMOC), que resultaría en un Atlántico Sur más cálido (en superficie y en profundidad), con un grado medio de incertidumbre [20,51]. Además, los cambios futuros en los patrones de viento superficial podrían alterar la mezcla entre las principales corrientes del OASO y los procesos de mezcla vertical, con impactos potenciales sobre los flujos de nutrientes hacia el océano superior, la conectividad biológica, la distribución de especies y las pesquerías. En efecto, los modelos ecosistémicos proyectan que, en el transcurso del siglo XXI, las dinámicas ambientales reconfigurarán los patrones de riqueza de especies, lo que requerirá priorizar esfuerzos para salvaguardar la biodiversidad ante un clima cambiante (Fig. 3b). Como consecuencia, la gestión pesquera se verá desafiada por los desplazamientos en la distribución de las especies transfronterizas de importancia comercial hacia el sur (Fig. 3c), incluida la aparición de nuevos stocks compartidos entre ZEE (Fig. 3d), así como el desplazamiento de especies solapantes hacia la alta mar (Fig. 3e) [52--54]. Por ejemplo, la Fig. 3e ilustra cómo el cambio climático podría modificar la proporción de la distribución de los stocks solapantes entre la alta mar y las ZEE. Estos posibles cambios (p. ej., un stock que se desplaza fuera de la ZEE al aumentar su proporción en la alta mar) reducen la efectividad de las medidas de gestión unilaterales, incrementan la exposición a la pesca INDNR (p. ej., por parte de flotas de aguas distantes) y aumentan el riesgo de conflictos de gobernanza, a medida que los stocks se desplazan progresivamente fuera de las jurisdicciones nacionales. Abordar estos desafíos requerirá estrategias de gestión adaptativas y colaborativas capaces de responder a las dinámicas cambiantes de los stocks solapantes a través de las fronteras políticas.

**Fig. 3. Impactos proyectados del cambio climático en la biodiversidad y los stocks compartidos del Océano Atlántico Sudoccidental.** a) Tendencia lineal de la temperatura superficial del mar (TSM) para el período 1982-2020 (datos de la Administración Nacional Oceánica y Atmosférica - Centro Nacional de Datos Climáticos, Interpolación Óptima SST versión 2, Radiómetro Avanzado de Muy Alta Resolución). b) Cambios en la riqueza de especies proyectados para 2050 (datos de AquaMaps/AquaX). c) Cambios en la proporción compartida de stocks transfronterizos entre ZEE para 2050 (adaptado de [54]). d) Nuevos stocks que llegan para 2100 (adaptado de [52]). e) Cambios en la proporción de stocks solapantes entre ZEE y la alta mar para 2050 (adaptado de [53]). Todas las proyecciones representan un escenario de alto nivel de emisiones de cambio climático.

---

## Avanzando

En un momento en que los océanos enfrentan desafíos sin precedentes derivados de las actividades antropogénicas, el multilateralismo está siendo erosionado por las tensiones geopolíticas y las sociedades de todo el mundo experimentan una creciente polarización, el océano sigue siendo un conector y un interés compartido para la humanidad [55]. La gobernanza oceánica integrada y colaborativa ya no es una opción, sino una necesidad urgente para detener la degradación de los ecosistemas y fomentar la sostenibilidad a largo plazo [36]. Aunque los esfuerzos en materia de gobernanza, conservación y recopilación de datos en el OASO siguen siendo limitados, restricciones similares se observan incluso en regiones comparativamente más ricas en datos y con mayor desarrollo institucional. El desafío clave en el OASO no es, por tanto, la ausencia de capacidad en sí misma, sino la falta de mecanismos coordinados a escala regional que alineen el conocimiento científico existente, los esfuerzos de monitoreo y los instrumentos de gobernanza entre jurisdicciones. Así, el impulso político en América Latina puede beneficiar a la gobernanza oceánica al trascender las fronteras geopolíticas y las divisiones sectoriales, reconociendo al mismo tiempo que los procesos ecológicos y climáticos operan a escalas muy superiores a las jurisdicciones nacionales.

### Aprovechar el impulso político latinoamericano

El momento para iniciar diálogos regionales sobre el establecimiento de marcos cooperativos y el reposicionamiento de la región del OASO en el panorama global de gobernanza oceánica no podría ser más crítico. Mientras las tensiones geopolíticas erosionan aspectos del multilateralismo global, esta tendencia puede también crear espacios para el fortalecimiento de iniciativas de gobernanza global y regional, como lo ejemplifica el reciente acuerdo entre el bloque comercial sudamericano (MERCOSUR) y la Unión Europea sobre agricultura, un acuerdo cuyas negociaciones comenzaron hace más de 20 años [56]. En el OASO, los discursos emergentes enmarcan cada vez más la cooperación regional no solo como respuesta a las brechas de gobernanza global, sino también como una oportunidad para afirmar la autonomía estratégica y la gestión compartida de los recursos marinos [8]. Además, Brasil ocupa actualmente un papel central en la agenda ambiental global, siendo sede de una secuencia de reuniones internacionales, incluida la Conferencia de las Partes (COP) 30 de la Convención Marco de las Naciones Unidas sobre el Cambio Climático (CMNUCC) en Belém en noviembre de 2025, así como el 3.er Simposio del Acuerdo BBNJ en marzo de 2026 y la Conferencia de la Década de los Océanos de la ONU en Río de Janeiro en 2027, entre otras. La COP30 en particular amplificó la urgencia de los vínculos entre clima y océano, reforzando la necesidad de estrategias de adaptación integradas para abordar el calentamiento de los mares, el desplazamiento de los stocks pesqueros, la acidificación y la pérdida de biodiversidad [57,58]. Brasil, durante la 3.ª Conferencia de las Naciones Unidas sobre los Océanos (CNUO3) en Niza, Francia (junio de 2025), integró una red de países que lanzaron el Desafío de las Contribuciones Determinadas a Nivel Nacional Azules (CDN Azules), un llamamiento global para que los países incluyan el océano en sus planes de acción nacionales y ambiciones climáticas. Una estrategia clave de las CDN Azules es fomentar pesquerías sostenibles y resistentes al clima, basadas en la gestión por ecosistemas y marcos de riesgo integrados. Paralelamente, con el Acuerdo BBNJ cerca de su ratificación y Chile impulsando activamente la posibilidad de albergar su secretaría permanente, transformar las oportunidades diplomáticas en estrategias concretas sobre pesquerías, conservación y resiliencia climática que sirvan a los intereses regionales y globales podría convertirse en una realidad. Finalmente, la Conferencia de la Década de los Océanos de la ONU subraya aún más el papel de la diplomacia científica oceánica como puente entre la producción de conocimiento y la acción política, alineándose con el llamamiento global a soluciones transformadoras impulsadas por la ciencia.

Estos eventos representan no solo hitos en la diplomacia ambiental global, sino también una rara confluencia de oportunidades para que la región consolide una estrategia coherente para el OASO. Los países pueden aprovechar estos eventos para articular prioridades compartidas, negociar marcos cooperativos y fortalecer los compromisos con una gestión basada en ecosistemas y resistente al clima. Los acuerdos internacionales, como el AMERP y el Acuerdo BBNJ, ofrecen plataformas ya elaboradas que pueden adaptarse a las realidades regionales, proporcionando legitimidad y capacidad de aplicación. La urgencia reside no solo en responder a la aceleración del cambio ambiental, sino también en aprovechar este impulso diplomático histórico para avanzar en una agenda sistemática, basada en la ciencia y fundamentada regionalmente para la gobernanza oceánica, incluido el OASO.

### Fortalecer la diplomacia científica oceánica

Avanzar requiere un cambio de paradigma en el marco de gobernanza del OASO. En concreto, la base para la cooperación, la gobernanza sostenible de las pesquerías y la conservación requiere un enfoque sistemático de diplomacia científica oceánica procedimental que integre las consideraciones del cambio climático, armonice los regímenes fragmentados y fortalezca el papel de la ciencia [59].

La diplomacia científica oceánica ofrece una lente útil para comprender y potencialmente salvar estas divisiones [60]. Al posicionar la ciencia tanto como fuente de conocimiento como herramienta para la gestión, la diplomacia científica oceánica busca conciliar los imperativos de soberanía con la necesidad de gobernanza cooperativa en un panorama institucional fragmentado. La Comisión Internacional para la Conservación del Atún Atlántico (CICAA) ilustra esta paradoja. Si bien representa un foro importante para la colaboración transnacional, ha recibido críticas por su limitada efectividad para garantizar una gestión sostenible del atún, a pesar de contar con mecanismos para la toma de decisiones basada en evidencia [61]. Esto demuestra tanto las oportunidades como las deficiencias de las OROP existentes, que proporcionan arenas estructuradas para la diplomacia pero se ven socavadas por asimetrías científicas y procedimentales entre los regímenes. El fortalecimiento de las interfaces ciencia-política puede ayudar a traducir señales ambientales complejas en estrategias de gestión viables. En este contexto, la diplomacia científica oceánica puede conciliar las preocupaciones de soberanía con la cooperación, posicionando el conocimiento como una herramienta activa de negociación. Los sistemas de monitoreo compartidos, las metodologías armonizadas y las evaluaciones conjuntas serán esenciales para generar datos robustos y comparables.

El cambio climático hace que esta integración sea aún más urgente, ya que el desplazamiento de los stocks y las transformaciones de los ecosistemas trascienden las fronteras, exigiendo respuestas coordinadas. Una solución capaz de abordar la complejidad de las preocupaciones multilaterales demanda integrar marcos y comportamientos cooperativos fundamentales para aumentar la confianza en las instituciones, así como asumir una visión compartida. Tal enfoque fomentaría enfoques regionales espaciales basados en la ciencia para coordinar la gestión sostenible y la conservación de las especies transfronterizas. Esto implica ir más allá de criterios geográficos únicos hacia la priorización de desafíos compartidos entre regiones ecológicamente similares, cada vez más afectadas por el calentamiento oceánico. Dichas amenazas abarcan múltiples dimensiones, incluyendo la disponibilidad de recursos humanos y financieros institucionales, los intereses de los actores, las tendencias dinámicas del mercado, los marcos normativos, las prácticas culturales y las vulnerabilidades específicas de las especies, requiriendo negociaciones que fortalezcan la convergencia hacia objetivos compartidos y la apertura a la innovación para gestionar los dinámicos desafíos a mediano plazo. Ante las tensiones geopolíticas, la diplomacia científica puede crear espacios neutros donde los Estados puedan colaborar hacia objetivos comunes.

A pesar de los claros beneficios en términos de coordinación y sostenibilidad, la viabilidad de esta transformación sigue siendo contingente a la voluntad política, las sensibilidades de soberanía y la capacidad de conciliar distintas prioridades nacionales. Aprovechando el largo historial de cooperación científica de la región y el precedente establecido por mecanismos anteriores, el desarrollo de un marco institucional renovado podría servir como un primer paso pragmático y efectivo para fomentar una ciencia oceánica más integrada y cooperativa en el OASO. Al ir más allá de los esfuerzos de investigación aislados hacia una colaboración regional e institucional construida sobre una visión compartida, misión y agenda a largo plazo, los científicos podrían ayudar a trazar el camino hacia un OASO integrado. Es importante destacar que, como investigadores comprometidos, no es necesario esperar a que cambien los vientos cruzados del sistema político. Las iniciativas científicas colectivas pueden impulsar esta agenda a través de infraestructuras de datos compartidas, el desarrollo de expediciones de investigación conjuntas, la armonización de protocolos de monitoreo y la promoción de programas de intercambio de capacidades que conecten instituciones de toda la región. La revitalización e implementación de la ZOPACAS, por ejemplo, podría proporcionar una plataforma prometedora para fomentar la cooperación científica en asuntos oceánicos, incluida la investigación pesquera en el OASO [62]. Una colaboración similar basada en la ciencia tiene el potencial de fortalecer la gobernanza regional y promover la gestión compartida de los recursos marinos del OASO. Asimismo, en 2024, un grupo de científicos (incluyendo autores de este artículo) se reunió en el 20.° *Congreso Latinoamericano de Ciencias del Mar* (COLACMAR), bajo los auspicios de la *Asociación Latinoamericana de Ciencias del Mar* (ALICMAR, [https://www.alicmar.org/](https://www.alicmar.org/)), en Brasil, para discutir precisamente los temas aquí explorados, desde una perspectiva científica. Dado su papel de larga trayectoria como organización científica regional, ALICMAR podría también servir como base para impulsar la gobernanza oceánica colaborativa en el OASO. La investigación en diplomacia científica oceánica muestra que la cooperación científica puede apoyar el mejoramiento de la gobernanza regional fomentando la confianza, el conocimiento compartido y el fortalecimiento de capacidades. Si bien no podemos garantizar que la integración científica repercuta en reformas de gobernanza, sí incentiva la coordinación entre jurisdicciones y destaca los beneficios mutuos de trabajar juntos hacia la sostenibilidad oceánica.

### Avanzar hacia una gobernanza y gestión oceánica integrada y multiescalar

La gobernanza oceánica en el OASO sigue fragmentada, en gran medida confinada a acuerdos bilaterales o mandatos sectoriales que no logran capturar la conectividad ecológica y la interdependencia socioeconómica de la región. Dicha fragmentación contrasta con la existencia de marcos de integración regional más amplios, como el MERCOSUR que, a pesar de resultados mixtos, ha proporcionado espacios institucionales para la cooperación en algunos ámbitos de política no oceánica. A pesar de estos marcos más amplios, la brecha más urgente en la gobernanza oceánica del OASO reside en la ausencia de un marco cooperativo que integre de manera significativa a Brasil con los acuerdos bilaterales existentes entre Argentina y Uruguay. Esto sugiere que las limitaciones para la gobernanza oceánica regional van más allá de la ausencia de instituciones regionales per se. Las experiencias de otras regiones, como la Asociación de Naciones del Sudeste Asiático (ASEAN) y la WCPFC, sugieren además que la cooperación incremental y de generación de confianza es posible incluso en contextos marítimos en disputa, ofreciendo lecciones potenciales para la gobernanza oceánica, incluso más allá del sector pesquero. Dada la conectividad ecológica de los sistemas de plataforma y la naturaleza transfronteriza de los stocks clave, un enfoque regional, pero flexible y policéntrico, representa una vía viable para enfrentar los desafíos que afronta la región. Dicho marco debería estar anclado en una gestión adaptativa y basada en la ciencia, un intercambio de datos fortalecido y la participación inclusiva de las partes interesadas y las comunidades locales. Esta transformación no ocurrirá de la noche a la mañana; requiere tiempo para cultivar la capacidad y la solidez institucional necesarias, pero la persistencia a largo plazo en la cooperación regional puede arrojar resultados incluso en medio de circunstancias geopolíticas difíciles. También debe ser habilitada por una vía plausible, viable y justa, anclada en una visión a largo plazo y en una agenda de investigación regional. Lejos de amenazar la soberanía, el establecimiento de una organización regional para la gobernanza cooperativa (p. ej., una OROP) podría fortalecerla al proporcionar a Argentina, Brasil y Uruguay un frente unido para defender sus recursos compartidos. Además, aunque la falta de una organización de cooperación regional mantiene la soberanía y autonomía de cada Estado, socava la resiliencia al cambio climático, las brechas de gobernanza y el avance de las flotas de aguas distantes [30]. Por tanto, la gobernanza efectiva en el OASO no puede limitarse únicamente a los Estados costeros. La creciente presencia de flotas pesqueras de aguas distantes, particularmente de China, España y Taiwán, que explotan stocks solapantes en las áreas de alta mar adyacentes, requiere una participación negociada con actores extra-regionales a través de los instrumentos internacionales existentes [30].

La gestión oceánica en la región debería apuntar a medidas de gestión adaptativas y basadas en ecosistemas que aumenten la resiliencia de los ecosistemas y los stocks pesqueros ante el cambio climático [63]. El concepto de gestión resiliente al clima se fundamenta en la precaución, la eficiencia y la capacidad de respuesta política, y está diseñado para abordar las incertidumbres y las respuestas de los sistemas socioecológicos marinos, considerando al mismo tiempo la integración de políticas, herramientas y medidas a través del espacio y el tiempo [64]. Por tanto, debe ser inclusiva de diversas partes interesadas, como la academia, los pescadores artesanales, la industria y las organizaciones no gubernamentales, a fin de establecer espacios formales para integrar sistemas de conocimiento plural y aspiraciones diversas. La bioregionalización de las áreas costeras y de plataforma [4] proporciona un marco macroescalar sólido para fortalecer el ajuste socioecológico e institucional. La aplicación de este enfoque al OASO puede identificar hábitats sensibles y ecosistemas vulnerables, orientar medidas de gestión focalizadas y revelar impulsores ecológicos actualmente enmascarados por observaciones fragmentadas. Alinear las estructuras institucionales con estas dinámicas ambientales a gran escala fomentaría una gestión regional más efectiva, pesquerías resilientes y una mayor conservación de la biodiversidad. Por ejemplo, a medida que los países del OASO amplían sus áreas marinas protegidas (AMP) para alcanzar los objetivos 30x30 del CDB, la conservación regional puede fortalecerse mediante el establecimiento de una amplia red de AMP transfronterizas. Construyendo sobre las grandes AMP ya designadas en Argentina y Brasil, una red de conservación del OASO podría mejorar la protección de la biodiversidad, contribuir a la recuperación de los stocks sobreexplotados, mantener los servicios ecosistémicos, incrementar la conectividad ecológica y fomentar la resiliencia ante un clima cambiante [65]. Si bien estas grandes AMP representan logros de conservación significativos, también intersectan con dinámicas geopolíticas y de soberanía (p. ej., la disputa por las Islas Malvinas/Falkland). Por tanto, las iniciativas de conservación pueden simultáneamente avanzar objetivos de biodiversidad y complicar la cooperación regional, subrayando la necesidad de estrategias de conservación que sean ecológicamente sólidas, políticamente conscientes e inclusivas a nivel regional. Además, dicha red debería estar conectada a la alta mar a través del Acuerdo BBNJ, y podría incluir áreas ya designadas como Áreas de Importancia Ecológica o Biológica (AIEB) del CDB, como la Zona de Fractura Ecuatorial Atlántica ([https://livinghighseas.org](https://livinghighseas.org)) o el Hoyo Azul, una zona de alta productividad justo fuera de la ZEE de Argentina bajo intensa actividad pesquera por parte de flotas de aguas distantes [66,67].
