---
title: 'A governança oceânica integrada é necessária no Oceano Atlântico Sudoeste para promover a pesca, a conservação e a resiliência às mudanças climáticas'
subtitle: "Juliano Palacios-Abrantes, Facundo Llompart, Luís Gustavo Cardoso, Omar Defeo, Ignacio Gianelli, Andrés J. Jaureguizar, Priscila F. M. Lopes, José Angel A. Perez, Natali I. P. Piccolo, Alberto R. Piola, Andrei Polejack, Luciana F. Prado, Martin Saraceno"
date: "2026"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: true
  pdf_document:
    toc: false
urlcolor: blue
---



-   **NOTA: Esta é uma tradução ao português do artigo:** *Integrated ocean governance is needed in the Southwest Atlantic Ocean to foster fisheries, conservation and resilience to climate change*, escrito por Palacios-Abrantes J. e colaboradores. Disponível [online](https://doi.org/10.1007/s44289-026-00134-4). 


    - Traduzido por Juliano Palacios. Revisão técnica de Luis Gustavo Cardoso, Luciana Prado e Priscila Lopes.  

-   **Referência**: Palacios-Abrantes, J., Llompart, F., Cardoso, L. G., Defeo, O., Gianelli, I., Jaureguizar, A. J., Lopes, P. F. M., Perez, J. A. A., Piccolo, N. I. P., Piola, A. R., Polejack, A., Prado, L. F. and Saraceno, M., 2026. Integrated ocean governance is needed in the Southwest Atlantic Ocean to foster fisheries, conservation and resilience to climate change. Discover Oceans, 3 (1), 19.

<center><a span class="label label-success" href= "./swao_cc/swao_pt.pdf" >Descargar Artigo em Português</span></a></center>

<br>

<!-- Abstract rectangle -->


<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding:20px;}
</style>


